### ISSUE TITLE
article + [polish]babel + ragged2e = LaTeX Warning: Command \selectfont has changed.

### ISSUE THREAD

**Issue by ghost** [latex3/babel#103]
Feeding `pdflatex` with 
```
\documentclass{article}
\usepackage[polish]{babel}
\usepackage{ragged2e}
\begin{document}
\end{document}
```
results in the warning
```
LaTeX Warning: Command \selectfont   has changed.
               Check if current package is valid.
```
both in the log and on tty.  What to do exactly?  What could potentially go wrong? (Previously, the bug apparently occurred for the beamer class, cf. http://tex.stackexchange.com/questions/244215/beamer-with-ragged2e-and-babel-results-in-command-selectfont-has-changed-warn)

**Comment by jbezos** [comment]
Warnings are not bugs, they just warn about possible problems or incompatibilities. In this case, the warning is harmless, as explained in the link, so you can ignore it altogether. I'm not sure if `polish` is currently maintained by the original authors (Michael Janich, Elmar Schalück), but you can try to contact them or even ask the Polish user group. If there is no answer, I'll try to ‘hide’ this message somehow.

**Comment by MdAyquassar** [comment]
> In this case, the warning is harmless, as explained in the link, so you can ignore it altogether.

The link does not *say* it is harmless, but „It is just telling you this has been done. This is part of what you pay babel to do.“, whatever this means and whichever implications this might have. However, if *you* do say it's harmless, I gladly take this. Is the definition of `\selectfont` changed only when the language is polish or globally for all languages?

Thanks!

**Comment by FrankMittelbach** [comment]
It is not harmless Javier. the polish option changes \selectfont by overwriting and ragged2e does so by overwriting and as a result the polish change is no longer present. At the current point in time it simply means the two packages do not work  together (suppressing the message is therefore not the right option). 

Midterm I think both have to change (to use the new hook mechanism instead of this incompatible overwriting, but ragged2e is no longer maintained by Martin and I haven't gotten around looking at how it should be changed.

**Comment by MdAyquassar** [comment]
@FrankMittelbach If in my non-mwe source code I always have `\RaggedLeft` or `\RaggedRight` in non-Polish contexts only, and the only Polish context is, say, `\foreignlanguage{polish}{Stanisław Herman Lem}` somewhere deep in the bibliography, can I ignore this warning or should I take any steps?

**Comment by FrankMittelbach** [comment]
I doubt that it makes any difference if you use the opition option just for individual names in the biblio, but I haven't looked in detail at what that tries to do to \selectfont, it seems to set up some special font things if typesetting Polish but that gets lost when ragged2e is loaded.

**Comment by jbezos** [comment]
I've re-opened it.

**Comment by jbezos** [comment]
But please remember warnings are neither errors nor bugs by themselves, and the MWE is too minimal 🙂 in the sense it doesn't show any anomalous result in the document.

**Comment by u-fischer** [comment]
The problem are a few chars in \ttfamily with OT1 encoding. In this encoding, polish has to fake a few chars, and so patches selectfont to switch a few definitions, and everysel (loaded by ragged2e) destroys this patch. 

There is no problem with T1 or TU. 

~~~~
\documentclass{article}
%\usepackage[T1]{fontenc}

\usepackage[polish]{babel}
\RequirePackage{everysel}

\begin{document}

\Huge 
\lpb \Lpb \zkb \Zkb

\ttfamily  \lpb \Lpb \zkb \Zkb \quad 
\telepl \lpb \Lpb \zkb \Zkb

\rmfamily \lpb \Lpb \zkb \Zkb \quad 
\textpl \lpb \Lpb \zkb \Zkb
\end{document}
~~~~

Probably polish should simply force T1-encoding. And everysel should be replaced by some proper kernel hooks and taken out.

**Comment by MdAyquassar** [comment]
> But please remember warnings are neither errors nor bugs by themselves, and the MWE is too minimal slightly_smiling_face in the sense it doesn't show any anomalous result in the document.

In my large non-MWE document, I don't observe any anomalies yet.  But: (1) I cannot say anything about things which are hard to observe, such as micro-typesetting. (2) The amount of stuff I've typeset in Polish has been really low so far. In fact, it is just one occurrence `\foreignlanguage{polish}{Leszek Gąsieniec}`.

**Comment by jbezos** [comment]
Thank you for the MWE (and sorry if I've seemed rude).

**Comment by FrankMittelbach** [comment]
Am 27.10.20 um 10:48 schrieb Ulrike Fischer:
> Probably polish should simply force T1-encoding. And everysel should be 
> replaced by some proper kernel hooks and taken out.

agreed, what I'm not sure about is whether \selectfont should get a 
kernel hook or whether this isn't overkill and the whole thing should be 
handled differently. I've marked it as a candidate but we'll see what is 
best there.

**Comment by MdAyquassar** [comment]
> Michael Janich, Elmar Schalück

@jbezos I tried to find the current e-mail addresses but found only extremely dated ones listed in polish.dtx.  I sent an e-mail there and to J.L. Braams anway.  Elmar's address returned an error already.  If you have working e-mail addresses of the two, please feel free to make the folks aware of this bug report. Thank you in advance.

**Comment by jbezos** [comment]
I'll make a few last attempts to contact them. If they fail, I will correct it myself.

**Comment by PeterMuellerr** [comment]
Given the recent changes in ragged2e , could I kindly ask anyone with a fresh installation of TeX Live (which I, unfortunately, cannot install at this very moment myself locally) whether the issue still exists? Thx!

**Comment by jbezos** [comment]
Fixed: https://www.ctan.org/ctan-ann/id/mailman.1593.1647209067.3195.ctan-ann@ctan.org
