### ISSUE TITLE
HELP! Errors on 2018 documents that worked before.

### ISSUE THREAD

**Issue by dexington** [latex3/babel#116]
A book I wrote in 2018 no longer compiles on a fresh installation on Ubuntu 16 or Mint 20 (I use texlive-full, miktex, texmaker).  Everything was working perfectly before. 

The first error that pops up is a \spacefactor complaint. Among all the packages that I use, Babel seems to be the one most active with the most recent update.

I'd appreciate assistance to get this fixed so I can get to my work!

I've attached:
-  skeleton versions of my main .tex files for testing 
-  screenshots of some of the errors

[Broken Babel.tar.gz](https://github.com/latex3/babel/files/5937869/Broken.Babel.tar.gz)

![image](https://user-images.githubusercontent.com/78667234/107132372-54205200-68ac-11eb-95d8-c3b9b24866de.png)
![image](https://user-images.githubusercontent.com/78667234/107132389-7f0aa600-68ac-11eb-8cfb-0352880b6c09.png)

**Comment by u-fischer** [comment]
The textalpha.sty is probably the source of the problem. It issues an \makeatother where it shouldn't.  Report it to the greek-fontenc maintainer.

**Comment by davidcarlisle** [comment]
in addition to  the error in textalpha

Your chapter file generates a warning about end occurring at level 1 as it
has a spurious unclosed brace here{

\chapter{Chapter X}{\index{chapter x}

                                 ^

should be

\chapter{Chapter X}\index{chapter x}

You can locally fix textalpha by commenting out the two lines shown


\AtBeginDocument{
  \@ifl@aded{def}{puenc}{
%    \makeatletter % required inside \AtBeginDocument
    \input{puenc-greek.def}
    \textalpha@define@breathings{PU}
    \pdfstringdefDisableCommands{\let\TextOrMath\@firstoftwo}
%    \makeatother
  }{}
}

(lines 273 and 277)

**Comment by dexington** [comment]
@davidcarlisle: BRILLIANT! Now it compiles. Is there a chance that commenting out those lines might break anything else? 
@u-fischer: I've sent an email to Gunter Milde as you suggested

Thank you so much! I was sweating over this.
