### ISSUE TITLE
What Babel macros work in Plain TeX?

### ISSUE THREAD

**Issue by lemzwerg** [latex3/babel#120]
[Babel 3.54]

Right now, `babel.pdf` has zero information on which Babel macros are supported in Plain TeX, and which syntax should be used for those that are available.  It would be nice if there are some sentences that clarify the issue.

**Comment by jbezos** [comment]
@lemzwerg It's a question I have been dreading for a long time 🙂. I was aware a more complete documentation in this regard was necessary, because all I'd done was to copy the original `bbplain.dtx` with the minimal changes necessary to ensure `babel` continued to work with Plain. There are some hints in the code part, but I’ll try to improve the documentation.

**Comment by lemzwerg** [comment]
Great!  What I want to do is to use recent German hyphenation patterns (or rather, I want to document how this can be done in plain TeX).  I tried
```tex
\input ngermanb.sty
\begindocument
\babelprovide[hyphenrules=ngerman-x-latest]{ngerman}
\showhyphens{Fassade modernste Abendstern Mordopfer}
\bye
```
but this fails with
```tex
! Undefined control sequence.
<to be read again> \InputIfFileExists 
                                      {babel-ngerman.tex}{}{}
\bbl@exp@aux ...ileExists {babel-ngerman.tex}{}{}}
                                                  \catcode `\%=14\relax \cat...

\bbl@input@texini ...\\}=\the \catcode `\}\relax }
                                                  \bbl@esphack 
<argument> ...d \relax \bbl@input@texini {ngerman}
                                                  \else \setbox \z@ \hbox {\...

\@firstoftwo #1#2->#1
                     
\\babelprovide ...space >}\fi \bbl@load@basic {#2}
                                                  \ifx \bbl@KVP@script \@nil...
l.3 ...vide[hyphenrules=ngerman-x-latest]{ngerman}
```
Can I actually use this command in plain TeX?  Or is there a different syntax to be used, maybe?

**Comment by jbezos** [comment]
I'm working on it. See https://github.com/latex3/babel/blob/master/news-guides/guides/using-babel-with-plain.md .

**Comment by lemzwerg** [comment]
Looks very promising, thanks!
