### ISSUE TITLE
hyphenrules don't work with MiKTeX

### ISSUE THREAD

**Issue by erik-f** [latex3/babel#124]
I want to use the hyphenrules `ngerman-x-latest`. To do so, I compiled the following MWE.
```LaTeX
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
\babelprovide[hyphenrules=ngerman-x-latest]{ngerman}

\begin{document}
    Test

    \showhyphens{Abendstern}
    \showhyphens{Mordopfer}
\end{document}
 ```
This works fine with TeX Live (tested with Ubuntu and Archlinux):
```
[] \T1/cmr/m/n/10 Abend-stern

[] \T1/cmr/m/n/10 Mord-op-fer
```
However, when I compile this with MiKTeX on Windows, the old hyphenrules are loaded:
```
[] \T1/cmr/m/n/10 Abends-tern

[] \T1/cmr/m/n/10 Mor-dop-fer
```
Also, the line `Package babel Info: \l@ngerman = using hyphenrules for ngerman-x-2019-04-04` is missing in the logs here.

At first, I didn't have `dehyph-exptl` (and therefore `ngerman-x-latest` installed).
I expected MiKTeX to install it automatically when requested, which didn't happen, so I installed `dehyph-exptl` manually.
However, this didn't change anything; the hyphenrules are still not loaded.

Is there anything else I need to do to make this work, or is this a bug with either `babel` or MiKTeX?

**Comment by u-fischer** [comment]
Works fine for me in a current miktex. There was a bug two weeks ago, but it has been resolved: https://github.com/MiKTeX/miktex-packaging/issues/233

**Comment by erik-f** [comment]
My `languages.ini` looks fine, though:
```
[ngerman-x-2021-02-26]
loader=dehyphn-x-2021-02-26.tex
lefthyphenmin=2
righthyphenmin=2
synonyms=ngerman-x-latest
patterns=hyph-de-1996.pat.txt
hyphenation=hyph-de-1996.hyp.txt
```
But with `hyphsubst` it fails with:
```
oberdiek\hyphsubst.sty:227: Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.
```

**Comment by u-fischer** [comment]
which means that it is not a babel problem, so you are here at the wrong place. Open an issue in the miktex tracker.

**Comment by erik-f** [comment]
Alright, thank you!
