### ISSUE TITLE
Loading hyphenrules fails quietly

### ISSUE THREAD

**Issue by efaulhaber** [latex3/babel#125]
I understand that the docs say "If none of the listed hyphenrules exist, the default behavior applies", but I strongly disagree with this behavior.
If I want to load different hyphenrules for my thesis (say, the default hyphenrules for my language are awful), I would expect `babel` to show at least a warning if the hyphenrules couldn't be found for some reason.

This doesn't have to be the default behavior, but I would want to have at least an option to turn on some kind of "fail-safe mode", in which the compilation fails if my requested hyphenrules can't be loaded (or at least if none of them could be loaded if I specified multiple hyphenrules).
If I take my source files to another machine, I want to be sure that I get a proper output if compilation succeeded without errors and warnings. I don't want to compile them on some other machine without warnings, just to find multiple incorrectly broken words in my printed thesis later.

**Comment by jbezos** [comment]
It makes sense. I'll study it.
