### ISSUE TITLE
\shorthandoff*{^} is not revertible

### ISSUE THREAD

**Issue by wehro** [latex3/babel#126]
An active `^` character (as defined by babel-esperanto and some other languages) may cause problems under certain circumstances. To turn this shorthand off, the babel manual advises to use `\shorthandoff*{^}` (starred form) instead of `\shorthandoff{^}` aiming to keep `^` intact in math mode.
However, when using the starred form, it seems not to be possible to turn `^` on again with `\shorthandon{^}`.
I ran into this issue when experimenting with babel-latin, which I am revising at the moment, but for the sake of simplicity, let me demonstrate with Esperanto:
```
\documentclass{article}
\usepackage[esperanto]{babel}

\begin{document}
\shorthandoff*{^}
^^51 % the letter Q
$a^2+b^2=c^2$

\shorthandon{^}
^c
$a^2+b^2=c^2$
\end{document}
```
Error message:
```
! Undefined control sequence.
l.10 ^
      c
```

**Comment by jbezos** [comment]
Confirmed.

**Comment by wehro** [comment]
Thank you, @jbezos. `\shorthandoff*{^}` and `\shorthandon{^}` now work as expected.

But what is the reason the following code does not work?
```
\documentclass{article}
\usepackage[esperanto]{babel}

\def\Off{\shorthandoff*{^}}
\def\On{\shorthandon{^}}

\begin{document}
\Off
^^51 % the letter Q
$a^2+b^2=c^2$

\On
^c
$a^2+b^2=c^2$
\end{document}
```
Error message:
```
! Missing $ inserted.
<inserted text> 
                $
l.13 ^
      c
```

**Comment by jbezos** [comment]
Fixed (so I hope).

**Comment by wehro** [comment]
Both examples above now run without errors, but here is the next one which does not. :(
```
\documentclass{article}
\usepackage[esperanto,english]{babel}

\begin{document}
\shorthandoff*{^}
^^51 % the letter Q
$a^2+b^2=c^2$

\selectlanguage{esperanto}
\shorthandon{^}
^c
$a^2+b^2=c^2$
\end{document}
```
Error message:
```
! Missing $ inserted.
<inserted text> 
                $
l.11 ^
      c
```

**Comment by jbezos** [comment]
Fixed. (Have I finally managed to do it? 🙂.)

**Comment by wehro** [comment]
> Fixed. (Have I finally managed to do it? slightly_smiling_face.)

Yes, everything seems to wort now. Thanks.
