### ISSUE TITLE
texlive 2021's babel using US instead of UKenglish hyphenations

### ISSUE THREAD

**Issue by floriandk** [latex3/babel#127]
babel Version 3.57 (as installed by default by texlive 2021) fails to use British hyphenation rules and defaults to US-rules.
The pdfs for 
```
\documentclass{book}

\usepackage[USenglish]{babel}
%\usepackage[UKenglish]{babel}

\usepackage{showhyphens}

\begin{document}

We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, --That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.--Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government. The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a candid world.

\end{document}
```

are identical with each other and with earlier (texlive2020) US-hyphenations.

Any workarounds would be highly appreciated!

**Comment by u-fischer** [comment]
I tried with the word alternate and get different hyphenation:

~~~~

\documentclass{book}

\usepackage[UKenglish,USenglish]{babel}

\usepackage{showhyphens}
\textwidth=1mm
\begin{document}

\showhyphens{alternate} % al-tern-ate british al-ter-nate american

alternate

\selectlanguage{UKenglish}

\showhyphens{alternate} % al-tern-ate british al-ter-nate american

alternate

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/114405454-fe676f00-9ba6-11eb-89e4-5531452a92af.png)

**Comment by floriandk** [comment]
strange... I get "al-ter-nate" (US) twice. Could this be OS-dependant? I am on macOS.

<img width="72" alt="Screen Shot 2021-04-12 at 16 35 19" src="https://user-images.githubusercontent.com/954598/114412669-99fbde00-9bad-11eb-84f2-ccabdd1211a7.png">

**Comment by u-fischer** [comment]
try with usenglish, ukenglish instead of USenglish, UKenglish , or with british and american.   Windows is case insensitive, but on your OS it could matter.

**Comment by FrankMittelbach** [comment]
they are called USenglish and UKenglish on MacOS too and the file works for me  (with correct hyphenation) with TL21 (and luatex)

But there seems to be a bug in showhyphens.sty (or maybe even in the kernel files). I first tried it with pdftex and that gives me
```
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/ifluatex.sty
(/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty))
(/usr/local/texlive/2021/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/local/texlive/2021/texmf-dist/tex/luatex/ctablestack/ctablestack.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/ltluatex.tex
/usr/local/texlive/2021/texmf-dist/tex/latex/base/ltluatex.tex:55: Undefined co
ntrol sequence.
l.55 \ifnum\luatexversion
                         <60 %
? 
```
which doesn't look ok

**Comment by floriandk** [comment]
Thank you for your time!

@u-fischer same with british

@FrankMittelbach it doesn't seem to have anything to do with showhyphens. Removing it from Ulrike's example I do get the same results: Different hyphenations with TL20 (babel 2021/03/03 3.55), same (US-)hyphens with TL21 (babel 2021/04/07 3.57)

I attach my log.

Also pdflatex is displaying the same behaviour as lualatex.

[TL21babelAlternatetest.log](https://github.com/latex3/babel/files/6297890/TL21babelAlternatetest.log)

**Comment by u-fischer** [comment]
you have much less languages setup than me.

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach it doesn't seem to have anything to do with showhyphens. Removing it from Ulrike's example I do get the same results: Different hyphenations with TL20 (babel 2021/03/03 3.55), same (US-)hyphens with TL21 (babel 2021/04/07 3.57)

your problem has nothing to do with the showhyphen, that was more re general remark towards Ulrike because it seems to indicate another but a totally different problem. Yours seems to be that the UK hyphenation patterns are for some reason not in the format  (babel resorts to us-english if it can't find patterns) so maybe your installation doesn't have them.  you need to check the logs of the fomat generation.

**Comment by FrankMittelbach** [comment]
you have
```
(/usr/local/texlive/2021/texmf-dist/tex/generic/babel/luababel.def
\bbl@readstream=\read2
\l@dumylang=\language2
Package babel Info: Non-standard hyphenation setup on input line 117.
\l@nohyphenation=\language3
\babelcatcodetablenum=\catcodetable12
\bbl@pattcodes=\catcodetable13
)
```
At that point I have
```
(/usr/local/texlive/2021/texmf-dist/tex/generic/babel/luababel.def
\bbl@readstream=\read2
\l@dumylang=\language2
Package babel Info: Non-standard hyphenation setup on input line 117.
\l@nohyphenation=\language3
\l@german-x-2021-02-26=\language4
\l@ngerman-x-2021-02-26=\language5
\l@afrikaans=\language6
\l@ancientgreek=\language7
\l@ibycus=\language8
\l@arabic=\language9
\l@armenian=\language10
\l@basque=\language11
\l@belarusian=\language12
\l@bulgarian=\language13
\l@catalan=\language14
\l@pinyin=\language15
\l@churchslavonic=\language16
\l@coptic=\language17
\l@croatian=\language18
\l@czech=\language19
\l@danish=\language20
\l@dutch=\language21
\l@ukenglish=\language22
\l@usenglishmax=\language23
\l@esperanto=\language24
\l@estonian=\language25
\l@ethiopic=\language26
\l@farsi=\language27
\l@finnish=\language28
\l@schoolfinnish=\language29
\l@french=\language30
\l@friulan=\language31
\l@galician=\language32
\l@georgian=\language33
\l@german=\language34
\l@ngerman=\language35
\l@swissgerman=\language36
\l@greek=\language37
\l@monogreek=\language38
\l@hungarian=\language39
\l@icelandic=\language40
\l@assamese=\language41
\l@bengali=\language42
\l@gujarati=\language43
\l@hindi=\language44
\l@kannada=\language45
\l@malayalam=\language46
\l@marathi=\language47
\l@oriya=\language48
\l@pali=\language49
\l@panjabi=\language50
\l@tamil=\language51
\l@telugu=\language52
\l@indonesian=\language53
\l@interlingua=\language54
\l@irish=\language55
\l@italian=\language56
\l@kurmanji=\language57
\l@classiclatin=\language58
\l@latin=\language59
\l@liturgicallatin=\language60
\l@latvian=\language61
\l@lithuanian=\language62
\l@macedonian=\language63
\l@mongolian=\language64
\l@mongolianlmc=\language65
\l@bokmal=\language66
\l@nynorsk=\language67
\l@occitan=\language68
\l@piedmontese=\language69
\l@polish=\language70
\l@portuguese=\language71
\l@romanian=\language72
\l@romansh=\language73
\l@russian=\language74
\l@sanskrit=\language75
\l@serbian=\language76
\l@serbianc=\language77
\l@slovak=\language78
\l@slovenian=\language79
\l@spanish=\language80
\l@swedish=\language81
\l@thai=\language82
\l@turkish=\language83
\l@turkmen=\language84
\l@ukrainian=\language85
\l@uppersorbian=\language86
\l@welsh=\language87
\babelcatcodetablenum=\catcodetable12
\bbl@pattcodes=\catcodetable13
)
so babel basically doesn't find patterns

**Comment by jbezos** [comment]
What does `\usepackage[showlanguages]{babel}` show in the log file with pdflatex? There must be something like:
```
<*languages>
0	english	hyphen.tex	
0	usenglish		
0	USenglish		
0	american		
1	dumylang	dumyhyph.tex	
2	nohyphenation	zerohyph.tex	
3	german-x-2021-02-26	dehypht-x-2021-02-26.tex	
3	german-x-latest		
4	ngerman-x-2021-02-26	dehyphn-x-2021-02-26.tex	
4	ngerman-x-latest		
5	afrikaans	loadhyph-af.tex	
6	ancientgreek	loadhyph-grc.tex	
7	ibycus	ibyhyph.tex	
8	arabic	zerohyph.tex	
9	armenian	loadhyph-hy.tex	
10	basque	loadhyph-eu.tex	
11	belarusian	loadhyph-be.tex
           <and many other entries>
```
If it only shows those for USenglish (ie, the ‘0th’ ones), I'd say there is a problem in the configuration of your TeXLive.

**Comment by davidcarlisle** [comment]
> 
> 
> they are called USenglish and UKenglish on MacOS too and the file works for me (with correct hyphenation) with TL21 (and luatex)
> 
> But there seems to be a bug in showhyphens.sty (or maybe even in the kernel files). I first tried it with pdftex and that gives me
> 
> ```
> (/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/ifluatex.sty
> (/usr/local/texlive/2021/texmf-dist/tex/generic/iftex/iftex.sty))
> (/usr/local/texlive/2021/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
> (/usr/local/texlive/2021/texmf-dist/tex/luatex/ctablestack/ctablestack.sty
> (/usr/local/texlive/2021/texmf-dist/tex/latex/base/ltluatex.tex
> /usr/local/texlive/2021/texmf-dist/tex/latex/base/ltluatex.tex:55: Undefined co
> ntrol sequence.
> l.55 \ifnum\luatexversion
>                          <60 %
> ? 
> ```
> 
> which doesn't look ok


that error is that luatexbase is luatex-only but does not guard for that (and neither does showhyphens)

```
\documentclass{book}


\RequirePackage{luatexbase}

\begin{document}



\end{document}
```

`luatexbase` is  me and @josephwright  according to ctan so I guess we can give a more sensible error message there

**Comment by FrankMittelbach** [comment]
ah I see, I overlooked the fact that iftex already finished loading.  but why is there a load of iftex when it is then not really used?  --- strange :-)

**Comment by floriandk** [comment]
@jbezos 
I get 
```
Package: babel 2021/04/07 3.57 The Babel package
<*languages>
0	english	hyphen.tex	
0	usenglish		
0	USenglish		
0	american		
1	dumylang	dumyhyph.tex	
2	nohyphenation	zerohyph.tex	
```

So you are obviously right that babel doesn't find its languages though tlmgr showed me English, German and a couple of others as installed. I had tried a slim install and only chosen the languages I really need but now I got tlmgr to (re)install them all together with a reinstall of babel itself but `showlanguages` still produces the same list.
All other optional packages that I have installed in the same way work as expected.
Is there anything else I could try or is a fresh start for TL21 the easiest solution?

Another thing that is intriguing me is: Why isn't there an error message? If I try to call an uninstalled language, say `lowersorbian` I get 
```
babel Error: Unknown option `lowersorbian'. Either you misspelled it
(babel)                or the language definition file lowersorbian.ldf was not
 found.
```
but as you see I don't get anything like that for the two Englishes or any of the not working ones once they are installed by tlmgr.

**Comment by wehro** [comment]
Obviously, babel-english is correctly installed on your system. This package contains the files english.ldf, british.ldf, UKenglish.ldf, USenglish.ldf and others. Hyphenation patterns are not part of babel, they are only loaded by babel.
All language definition files of babel-english point to english.ldf. This file does not output an error message and not even a warning as long as one set of English patterns is available, even if it does not correspond to the chosen variant. (This is bad style in my opinion.)
You have to check if the hyphen-english package is installed.

**Comment by floriandk** [comment]
@wehro Great! that was the problem: the tlmgr `babel`- and `babel-anylanguage`-install doesn't install the corresponding hyphenation patterns. I hadn't understood this before now. Thank you!

Suggestion for the maintainers of tlmgr and babel respectively: `tlmgr install babel-anylanguage` should by default also install the related hyphenation pattern. If they are missing, as in my case, a strong error-message during the compilation would be very helpful. :)

**Comment by floriandk** [comment]
I also second @wehro 's opinion that *silently* defaulting to another hyphenation style within the same language is unfortunate.

**Comment by jbezos** [comment]
The list of loaded languages is not fixed, and loading just English is not an error at all. The only way to know if `language.dat` has been correctly read is, well, by reading it. The log file shows which patterns are actually loaded. In your case:
```
Package babel Info: \l@british = using hyphenrules for english
(babel)             (\language0) on input line 82.
Package babel Info: \l@UKenglish = using hyphenrules for english
(babel)             (\language0) on input line 83.
Package babel Info: \l@canadian = using hyphenrules for english
(babel)             (\language0) on input line 102.
Package babel Info: \l@australian = using hyphenrules for english
(babel)             (\language0) on input line 105.
Package babel Info: \l@newzealand = using hyphenrules for english
(babel)             (\language0) on input line 108.
```
I'll consider a stronger message in `babel`, like a warning instead of an info, but my experience tells me many people think warnings are errors to be fixed somehow, and in this case very often the replacement is fine and, in fact, intended. Anyway, the problem was ultimately in the installation of TeXLive.

**Comment by floriandk** [comment]
Certainly my fault and perhaps a bit tlmgr's ;)

My problem was partly that I didn't see any problem with the messages: `UKenglish = using hyphenrules for english` sounds completely unproblematic... (Though I should have known that TeX thinks English is USenglish by default)

Asking for one set of rules and getting another (though a sensible stand-in) is in my book definitely something that I should fix, either by installing the correct patterns or, if I am happy with the stand-in, I should change my code so that it doesn't ask for the other flavour. In any case I personally would think it would warrant an error...

And, let's face it, nobody is looking at the log if there isn't an error or at least a warning.

**Comment by jbezos** [comment]
> And, let's face it, nobody is looking at the log if there isn't an error or at least a warning.

Definitely 🙂.

**Comment by wehro** [comment]
Most ldf files use the `\@nopatterns` command provided by babel if no patterns are available for the respective language. german.ldf, dutch.ldf, and afrikaans.ldf also use this command if they replace the regular patterns by other ones.
What about a `\@replacepatterns` command for these cases? It could also be used by babel-english and babel-latin.

**Comment by jbezos** [comment]
What would that new macro do?

**Comment by wehro** [comment]
Well, quite the same as `\@nopatterns`, but also reporting the replacement, e.g.
```
\def\@replacepatterns#1#2{%
  \bbl@warning
    {No hyphenation patterns were found for\\%
     the language `#1'.\\%
     Please try to install them. Now I will use the patterns\\%
     for `#2' instead}}
```

**Comment by jbezos** [comment]
I'll close this issue because it was a problem in the TeXLive configuration. As to the message, I don't think raising a warning for a requested change is a good idea, but I've modified the message because it was certainly misleading. Now it's something like:
```
Hyphen rules for 'newzealand' set to \l@ukenglish
(\language22). Reported on input line xx
```
