### ISSUE TITLE
\shorthandoff*{^} causes error for \section command

### ISSUE THREAD

**Issue by wehro** [latex3/babel#129]
```
\documentclass{article}
\usepackage[esperanto]{babel}

\begin{document}
\section{^c}
\shorthandoff*{^}
\end{document}
```
Error message:
```
! Undefined control sequence.
<write> ...ine {section}{\protect \numberline {1}^
                                                  c}{\thepage }{}\protected@...
l.7 \end{document}
```
It works without problems with the unstarred form `\shorthandoff{^}`, so I think it should also work with the starred form.

**Comment by jbezos** [comment]
This is a more complicated, and I'm not sure if it's entirely ‘legal’, because these macros are for temporary changes. But the following is clearly legal and also fails:
```tex
\section{^c}
\shorthandoff*{^}
Blah
\newpage
\shorthandon{^}
Blah
```
I have to deal with the output routine, which is not always easy.
