### ISSUE TITLE
Can't change page numbering with arabic ldf (pdflatex)

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#136]
I can't change  page numbering format even if Arabic is added as a secondary language !! 

https://tex.stackexchange.com/questions/601437/issue-in-pagenumbering-with-arabic-ldf-babel

```latex
\documentclass[12pt]{report}
\usepackage[T1]{fontenc}
%\usepackage[french]{babel}
\usepackage[arabic,spanish]{babel}

\begin{document}

\renewcommand{\thepage}{foo}
%\pagenumbering{roman}

\chapter{First chap}
\section{First sec}

\newpage
text 
\newpage
text 

\end{document}
```

**Comment by jbezos** [comment]
The support for the Arabic language is a separate package. See https://ctan.org/pkg/arabi . Anyway, I've posted a workaround in tex.stackexchange.com .
