### ISSUE TITLE
Portuguese/Brazilian uses old font command \rm to define ordinal macros

### ISSUE THREAD

**Issue by gusbrs** [latex3/babel#137]
`babel` defines four convenience macros for ordinals to be available for Portuguese/Brazilian: `\ord`, `\orda`, `\ro`, and `\ra`. However, these macros are defined using the old LaTeX 2.09 `\rm` command.  This is done at lines 161-163 of `brazilian.ldf`, `brazil.ldf`, `portuges.ldf` and `portuguese.ldf` (I suppose these files are generated, but I can't find their source in the repository) with:

```latex
\def\ord{$^{\rm o}$}
\def\orda{$^{\rm a}$}
\let\ro\ord\let\ra\orda
```
A don't think a MWE is of great use for this, but one could be:

```latex
\RequirePackage{latexbug}

\RequirePackage[l2tabu, orthodox]{nag}

\documentclass{article}

\usepackage[portuguese]{babel}

\begin{document}

1\ord{} teste 2\ro{} teste 3\orda{} teste 4\ra{} teste

\end{document}
```

This, of course, makes `latexbug` complain about:
```
(latexbug)                This test file uses third-party file(s)
(latexbug)                
(latexbug)                ==============
(latexbug)                nag.sty
(latexbug)                nag-l2tabu.cfg
(latexbug)                nag-orthodox.cfg
(latexbug)                portuguese.ldf
(latexbug)                ==============
```

`portuguese.ldf` to the best of my knowledge is part of `babel`, that's the reason I'm reporting here (if I'm wrong, my apologies). And `nag` is just used to have something to show in the MWE. Indeed, it warns us of:

```
Package nag Warning: Command \rm is an old LaTeX 2.09 command. 
(nag)                Use \rmfamily or \textrm instead on input line 11.
```

**Comment by jbezos** [comment]
Fixed and submitted to CTAN.

**Comment by gusbrs** [comment]
Thank you!
