### ISSUE TITLE
Add/Remove tabular layout  locally  

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#14]
This is a feature request see
https://tex.stackexchange.com/q/486105/54817
I think it is better if we can add or remove layouts locally (In particular `tabular` and `column` ) 
with commands like `\addlayout{...}` and `\removelayout{...}`, thanks.

**Comment by jbezos** [comment]
It could be useful, indeed. Could you provide a more real use case?

**Comment by seloumi** [comment]
Sometimes we need to include two column page with LTR contents in RTL document, I think it would be better if we deactivate column layout to start column from left 
```latex 
\documentclass{article}
\usepackage[nil,bidi=basic-r,layout=tabular]{babel}
\babelprovide[import, main]{arabic}
\babelfont{rm}{Amiri}
\usepackage{lipsum}

\begin{document}

right to left contents 

% columns for the next page should be LTR 
\selectlanguage{nil}

\twocolumn

\lipsum[1-4]

\end{document}
```

**Comment by seloumi** [comment]
Sorry I tested layouts and the issue occur only with `tabular`  layout, in RTL document   tabular can be RTL or LTR and can be changed locally inside document.

**Comment by jbezos** [comment]
`\babeladjust` will provide these kinds of adjustements in 3.36.
