### ISSUE TITLE
[Arabic justification] marks does not placed good on jalted gylphs

### ISSUE THREAD

**Issue by hubaishan** [latex3/babel#142]
![بدون عنوان](https://user-images.githubusercontent.com/2285457/128631526-e4bd2f25-7d2e-4982-9886-0393ef6e6de9.png)
It seems mark lookups do not  work on jalted gylphs

**Comment by jbezos** [comment]
Support for JALT variants is still experimental and not yet usable in real documents. The current implementation is basically for demonstration purposes, so that people can provide some feedback. Please, could you provide an extended TeX example including both typical cases and more complex ones?

**Comment by hubaishan** [comment]
Another Bug: In Kashida mode it adds khasida in some ligatures when they have marks in middle of ligature
![image](https://user-images.githubusercontent.com/2285457/128671332-104c9d29-efb7-458e-8470-76e9a54031af.png)

no bug with Sokon)ْ)

**Comment by jbezos** [comment]
Please, send a minimal example showing the issue. Arabic justification is still tentative and your reports are very useful to improve it, but I need the concrete LaTeX examples to work on it.

**Comment by hubaishan** [comment]
As I see justification engine puts kashida between gylphs and do not reapply font rules on it , I suggest another justification engine that puts kashidas between letters and reshape whole word after.

**Comment by jbezos** [comment]
Yes, this is certainly one the options I have to investigate. For the moment, you can create your own rules adapted to the fonts you are using. As soon as I’ve finished preparing the current version, I’ll resume the work related to the Arabic writing. Of course, any contribution will be greatly appreciated.

**Comment by jbezos** [comment]
Please, can you provide the `tex` file for the original question, too?

**Comment by jbezos** [comment]
As to the bug with the laam alif with diacritics, I’ve fixed it, and I’ll release it in a few days.

**Comment by jbezos** [comment]
I'm closing this issue (again) because no MWE is provided for the original question, and the bug with the laam alif has been fixed. Feel free to re-open it with some actual code and a minimal document.
