### ISSUE TITLE
Tabular layout cause issue with array package 

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#15]
In this example addition  of `array`  package produces this error 

> Missing # inserted in alignment preamble

```latex
\documentclass[11pt]{article}
\usepackage{array}
\usepackage[bidi=basic-r,layout=tabular]{babel}

\babelprovide[import=ar, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\begin{tabular}{c|c}
text & text 
\end{tabular}

\end{document}
```

**Log file**
[test.log](https://github.com/latex3/babel/files/3138967/test.log)

**Comment by jbezos** [comment]
LaTeX does some tricky things in `tabular` with the math mode, and `babel` attempts to handle them with even trickier things. I'll must investigate.

**Comment by jbezos** [comment]
Fixed. I'll publish a new version tomorrow.
