### ISSUE TITLE
Problem with \usepackage[german]{babel}: Umlaute

### ISSUE THREAD

**Issue by BAMIP** [latex3/babel#157]
Sir,

\documentclass[a4paper,12pt]{article}
\usepackage[german]{babel}
\newcommand{\damals}{5. M"arz 2018}
\newcommand{\betr}{Zahlungs"ubersicht}
\begin{document}
{\damals}
{\betr}
\end{document}

will produce

5. M"arz 2018
Zahlungs"ubersicht

The correct compilation should produce

5. März 2018
Zahlungsübersicht

Is this a babel bug or an issue in my latex-file?

Thank you,

Michael

**Comment by u-fischer** [comment]
shorthands like `"` are only activated at the begin of the document.  Either move your definitions behind `\begin{document}` or activate them:

~~~~
\documentclass[a4paper,12pt]{article}
\usepackage[german]{babel}
\shorthandon{"} %<-------
\newcommand{\damals}{5. M"arz 2018}
\newcommand{\betr}{Zahlungs"ubersicht}
\begin{document}
{\damals}
{\betr}
\end{document}
~~~~

**Comment by jbezos** [comment]
Another alternative is:
```tex
\newcommand{\damals}{5. M\babelshorthand{"a}rz 2018}
\newcommand{\betr}{Zahlungs\babelshorthand{"u}bersicht}
```
Useful with shorthands like `"-` (see the example in section 1.10 of the `babel` manual), but definitely clumsy with letters. The best option, by far, is the one proposed by @u-fischer, namely, type directly `ä` and `ü`.
