### ISSUE TITLE
`\lll` defined by both polish.ldf and amssymb.sty

### ISSUE THREAD

**Issue by PeterMuellerr** [latex3/babel#160]
Dear maintainer(s) of polish.ldf,

I see `\let\lll=\l` in polish.ldf and `\DeclareMathSymbol{\lll}{\mathrel}{AMSa}{"6E}` in amssymb.sty. These definitions clash in various circumstances. E.g., depending on the order of loading [polish]babel and amssymb, you either get a warning or a failure of compilation (and, in neither case you get the expected ⋘):

```
\documentclass{article}
\usepackage[polish]{babel}
%%% Uncomment to make the bug go away (thanks to egreg!):
% \makeatletter
% \let\polish@l=\lll \let\polish@L=\LLL
% \let\lll\relax \let\LLL\relax % undefine them
% \def\plll{\polish@l}
% \def\pLLL{\polish@L}
% \makeatother
\usepackage{amssymb}
\begin{document}
\(\lll\)
\end{document}
```
It is probably more an issue with polish.ldf rather than amssymb.sty. An improvement could be, e.g., replacing `\lll` with something like `\polish@l` in polish.ldf.

More info: https://tex.stackexchange.com/q/106316 and https://tex.stackexchange.com/a/360831 .

I would be happy if my report finds attention.

PS. The e-mail addresses of Johannes and Elmar in polish.ldf are dead. I've already sent this report to massa at uni padeborn.

**Comment by eg9** [comment]
I see no reason for that really convoluted code that seems to be a relic of LaTeX2.09. And, anyway, such an `\lll` command is never described in the user manual, so its name, if the convoluted code has to be kept, should be changed.

**Comment by jbezos** [comment]
Fixed: https://www.ctan.org/ctan-ann/id/mailman.1593.1647209067.3195.ctan-ann@ctan.org
