### ISSUE TITLE
Incomplete \iffalse for mathtool's align-environment and lualatex

### ISSUE THREAD

**Issue by jnflk** [latex3/babel#162]
I updated babel via Tex Live's tlmgr to v3.68. With the new version, I cannot successfully compile documents with mathtool's align-environment using lualatex:

Minimal example:
```
% !TeX program = lualatex
\documentclass[]{article}
\usepackage[
    main=american
    ]{babel}
\usepackage{mathtools}

\begin{document}
Some
\begin{align}
	a = b \cdot c \label{some:label}
\end{align}
text.
\end{document}
```
gives the error:
```
! Incomplete \iffalse; all text was ignored after line 12.
<inserted text> 
\fi 
l.12 \end{align}
              
A forbidden control sequence occurred in skipped text.
This kind of error happens when you say `\if...' and forget
the matching `\fi'. I've inserted a `\fi'; this might work.

[1
```

Using pdflatex instead of lualatex, the document compiles.

In my case, I could downgrade to v3.67 using an older Tex Live repository https://www.texlive.info/tlnet-archive/ (e.g., https://www.texlive.info/tlnet-archive/2021/12/28/tlnet/) to build the document again with lualatex.

**Comment by davidcarlisle** [comment]
with amsmath rather than mathtools you get

```
! Undefined control sequence.
\bbl@truellap ->\ifcase \bbl@attr@dir 
                                      \expandafter \llap \else \expandafter ...

l.11 \end{align}
              
? 
```

**Comment by jbezos** [comment]
A missing test 🙁. I'll fix it asap.

**Comment by jbezos** [comment]
Just uploaded to CTAN. It should be available in TeXLive in a few hours.
