### ISSUE TITLE
New optional hyphenation patterns for Finnish language

### ISSUE THREAD

**Issue by tlikonen** [latex3/babel#164]
Latex package [hyph-utf8](https://www.ctan.org/pkg/hyph-utf8) contains new optional hyphenation patterns for Finnish language. The patterns are called "school" and are defined in files:

    tex/generic/hyph-utf8/patterns/ptex/hyph-fi-x-school.ec.tex
    tex/generic/hyph-utf8/patterns/tex/hyph-fi-x-school.tex
    tex/generic/hyph-utf8/patterns/txt/hyph-fi-x-school.pat.txt

I don't know Babel well but it seems that there is no easy option to use those optional Finnish hyphenation patterns. I suggest adding an option.

**Comment by jbezos** [comment]
Thank you. Once configured the system (usually with `language.dat`), there is a general way to change the hyphenation patterns in `babel` with something like `\babelprovide[hyphenrules=finnish-school]{finnish}` (provided this is the name assigned by the system). So, in regards to `babel`, this function is already available. (BTW, although unrelated, have a look at https://latex3.github.io/babel/news/whats-new-in-babel-3.70.html)

**Comment by tlikonen** [comment]
Ok. It's nice to hear that the functionality is already there. I tried some random things based on your hints and Babel manual but couldn't make those `hyph-fi-x-school` hyphenation patterns work. Normal users like me would need documentation or easier interface. I'll keep trying...

**Comment by FrankMittelbach** [comment]
```
\documentclass{article}

\usepackage[finnish]{babel}

% my language.dat file contains for finnish:
%
% from hyphen-finnish:
%  finnish loadhyph-fi.tex
%  schoolfinnish loadhyph-fi-x-school.tex
%
% thus:

\babelprovide[hyphenrules=finnishschool]{finnish}

\begin{document}

\showhyphens{place some suitable words in finnish in here to see if the hyphenation as as desired}

\end{document}
```

I don't speak Finnish so can't tell if the hyphenations are correct, but the above should apply them assuming your language.dat file also uses "finnishschool" as the interface name

**Comment by tlikonen** [comment]
Thank you. I could get "schoolfinnish" to load but the actual hyphenation didn't work. Maybe my manual installation of `hyph-utf8` isn't fully working. It will probably work when I get proper installation with Tex Live. Anyway, this is not a user support forum. It seems that this issue can be closed because there is already an option to load those alternative Finnish hyphenation patterns.

**Comment by jbezos** [comment]
As an additional help—`babel` takes a snapshot of the loaded hyphenation files. Just run the following document and look at the `log` file:
```tex
\documentclass{article}
\usepackage[showlanguages]{babel}
\stop
```
I’ll close this issue, as suggested.
