### ISSUE TITLE
Spanish babel incompatible with forloop?

### ISSUE THREAD

**Issue by Lobz** [latex3/babel#165]
This issue made me loose a few good hours until I managed to pinpoint babel as the culprit.
From looking at the logs, I think spanish redefines < and >, making the syntax of forloop impossible.
Here's a minimal example using the very example of forloop:

```latex
\documentclass{report}
\usepackage[spanish]{babel}

\usepackage{forloop}

\begin{document}
\newcounter{ct} \forloop{ct}{0}{\value{ct}<5}{\arabic{ct} }

\end{document}
```

**Comment by eg9** [comment]
It already breaks `ifthen`, which `forloop` is based upon.

```latex
\documentclass{report}
%\usepackage[spanish]{babel}
\usepackage{ifthen}

\begin{document}

\ifthenelse{3>2}{\typeout{YES}}{\typeout{NO}}

\end{document}
```

Uncommenting the `babel` line produces
```
! Missing = inserted for \ifnum.
<to be read again>
                   >
l.7 \ifthenelse{3>2}{\typeout{YES}}{\typeout{NO}}
```

**Comment by jbezos** [comment]
I’m closing this issue because it’s documented in the `spanish` docs. This (mis)feature made sense 25 years ago, but admittedly not today. Fortunately, it can be deactivated easily.
