### ISSUE TITLE
Hyperref links in TOC are misplaced

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#168]
The link is placed in the leaders and the page number and not in the title. It used to work, so a change to either `babel` or `hyperref` has broken it (when?). There is a similar problem with `\ref`.

**Comment by u-fischer** [comment]
Can you show an example?

**Comment by jbezos** [comment]
@u-fischer I was still investigating but the problem seems to be in `hyperref`:
```tex
\documentclass{article}

\usepackage{hyperref}

\begin{document}

\textdir TRT \pardir TRT % \bodydir TRT \pagedir TRT 

\section{Blah}
\label{blah}

Blah bla bla bla bla bla bla (((\ref{bla}))) bla bla bla.

\end{document}
```
With TeXlive 2020 it works as expected (tested in Overleaf), and the link is in the number, but with 2021 the link is misplaced and goes from the left of the ref to the end of the line.

**Comment by u-fischer** [comment]
That is due to an engine bug. I reported that in april last year and it was fixed revision 7431.
With luahbtex 1.14 it works (tested with miktex and a local binary) so I think it will be okay again in texlive 2022.

**Comment by jbezos** [comment]
👍 Not being a bug in `babel`, I’ll close it.
