### ISSUE TITLE
LuaLaTeX des not correctly render Sanskrit and Tamil scripts; XeLaTeX does: from the same source file with babel

### ISSUE THREAD

**Issue by kleinbottle** [latex3/babel#171]
```
% lua-xe-sa-ta-gk-lua.tex
%
\RequirePackage{latexbug}
\documentclass[12pt,a4paper]{article}
\usepackage{fontspec}
\usepackage[british]{babel}
%
\setmainfont[Scale=1,BoldFont={* Medium}]{Noto Serif}
\setsansfont[BoldFont={* Semibold}]{Source Sans Pro}
\setmonofont{Fira Mono}
%
% Fonts for sa, ta, gk
%
\newfontfamily\sanskritfont{Noto Serif Devanagari}[Scale=1.3]
\newfontfamily\tamilfont{Noto Sans Tamil}
\newfontfamily\greekfont{Noto Serif}
%
\babelprovide[import onchar=ids fonts]{sanskrit}
\babelprovide[import onchar=ids fonts]{tamil}
\babelprovide[import onchar=ids fonts]{greek}
%
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase,Renderer=Harfbuzz}
%
\setlength{\parindent}{0pt}
%
\begin{document}
%
\bigskip
Sanskrit in Devanāgarī

{\sanskritfont क्षिप्रं हि मानुषे लोके सिद्धिर्भवति कर्मजा ॥}

\medskip

Śrīmad Bhagavad Gītā 4:12

\bigskip

Tamil

{\tamilfont கற்க கசடறக் கற்பவை கற்றபின்\newline
நிற்க அதற்கு தக

\medskip

திருவள்ளுவர், திருக்குறள்} 40:391
\bigskip

Greek.

\medskip

{\greekfont Ὁδοὶ δύο εἰσί, μία τῆς ζωῆς καὶ μία τοῦ θανάτου, διαφορὰ δὲ πολλὴ μεταξὺ τῶν δύο ὁδῶν. }
\end{document}
```

Two image files showing the output from the above file with `lualatex` and `xelatex` are attached. The second one, produced by `xelatex` is correct.

Why is the `lualatex` output incorrect? Is `lualatex` still not quite ready for routine use with Indic scripts?
![lualatex-output](https://user-images.githubusercontent.com/193362/154672510-3ca7233f-c9ae-40ee-9393-48d24b3af030.png)
![xelatex-output](https://user-images.githubusercontent.com/193362/154672513-8d012433-6b12-4bb3-a2a3-0dc2282de791.png)

**Comment by u-fischer** [comment]
You need the harfbuzz renderer. So either move `\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase,Renderer=Harfbuzz}` before your font definitions, or use `Renderer=Harfbuzz` in the optional argument when declaring a font.

**Comment by kleinbottle** [comment]
I found that compound font-features like bold smallcaps are not displayed from the file given above. It appears that if the lines 
```
%
% Fonts for the British variant of English
%
\babelfont[british]{rm}[Scale=0.9]{Noto Serif}
\babelfont[british]{sf}[Scale=0.9]{Source Sans Pro}
\babelfont[british]{tt}[Scale=0.9]{Fira Mono}
```
are replaced by:
```
%
% Fonts set according to fontspec
%
\setmainfont[Scale=1,BoldFont={* Medium}]{Noto Serif}
\setsansfont[BoldFont={* Semibold}]{Source Sans Pro}
\setmonofont[Scale=0.9]{Fira Mono}
```
everything works as expected.

Obviously, the `\setmainfont` and friends invocation from `fontspec`is necessary.

**Comment by jbezos** [comment]
There declarations are not equivalent. Have you tried with the following?
```tex
\babelfont{rm}[Scale=1,BoldFont={* Medium}]{Noto Serif}
\babelfont{sf}[BoldFont={* Semibold}]{Source Sans Pro}
\babelfont{tt}[Scale=0.9]{Fira Mono}
```

**Comment by jbezos** [comment]
I’m closing this issue because it just seems an improper use of `\babelfont`.

**Comment by kleinbottle** [comment]
> I’m closing this issue because it just seems an improper use of `\babelfont`.

I am sorry I did not see your reply until today.

I thought I was using `\babelfont` properly. Kindly tell me why **what** I have done is "an improper use of `\babelfont`" and, if it is easy to understand, also **why**.

Are you saying that omitting the `BoldFont={* Medium}` declaration in `\babelfont` led me to lose the bold smallcaps, and that if that had been correctly done, I would have got the same results as with `\setmainfont`?

Thanks.

**Comment by jbezos** [comment]
Please, have you tried with the declarations above? Can you post a MWE with this particular issue?

**Comment by kleinbottle** [comment]
> Please, have you tried with the declarations above? Can you post a MWE with this particular issue?

I have tried what you have suggested. To make it an MWE, I have removed the foreign scripts. There are two versions of the file, one with a language declaration along with the font, and another without. It appears that setting the language of the main font causes the error I have encountered. The MWEs and the resulting outputs are shown below:
```
\documentclass[12pt,a4paper]{article}
\usepackage{fontspec}
\usepackage[british]{babel}
%
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase,Renderer=HarfBuzz}
%
% Without language declaration for the main language
%
\babelfont{rm}[Scale=1,BoldFont={* Medium}]{Noto Serif}
\babelfont{sf}[BoldFont={* Semibold}]{Source Sans Pro}
\babelfont{tt}[Scale=0.9]{Fira Mono}
%
\setlength{\parindent}{0pt}
%
\begin{document}
%
\section*{Latin Script}

\textrm{Roman}

\textsf{Sans Serif}

\texttt{Monospace}

\textsc{Small Caps}

{\bfseries\scshape Bold Small Caps}

{\bfseries\scshape\itshape Bold Small Caps Italic}

\textit{Italic}

\textbf{\textit{Bold Italic}}
%
\end{document}
```
gives
![without-main-language](https://user-images.githubusercontent.com/193362/156880745-cdd54915-ea0f-49f7-a8b9-217277518da4.png)
and this is both correct and as expected.  _Your suggestion works correctly_.

However, if the main language is specified, as in this MWE, the small caps bold does not work:
```
\documentclass[12pt,a4paper]{article}
\usepackage{fontspec}
\usepackage[british]{babel}
%
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase,Renderer=HarfBuzz}
%
% With language declaration for the main language
%
\babelfont[british]{rm}[Scale=1,BoldFont={* Medium}]{Noto Serif}
\babelfont[british]{sf}[BoldFont={* Semibold}]{Source Sans Pro}
\babelfont[british]{tt}[Scale=0.9]{Fira Mono}
%
\setlength{\parindent}{0pt}
%
\begin{document}
%
\section*{Latin Script}

\textrm{Roman}

\textsf{Sans Serif}

\texttt{Monospace}

\textsc{Small Caps}

{\bfseries\scshape Bold Small Caps}

{\bfseries\scshape\itshape Bold Small Caps Italic}

\textit{Italic}

\textbf{\textit{Bold Italic}}
%
\end{document}
```
and the result is: 
![with-main-language](https://user-images.githubusercontent.com/193362/156880790-70aa3b38-9303-46e9-8b95-193a12a65170.png)

It appears that the"improper use of `\babelfont` you have alluded to stems from declaring a language for the main language.

**Comment by jbezos** [comment]
I see. It seems related to https://github.com/latex3/babel/issues/92.

**Comment by kleinbottle** [comment]
Yes, indeed. So it seems.
