### ISSUE TITLE
latest Update and lualatex

### ISSUE THREAD

**Issue by hvoss49** [latex3/babel#175]
With latest update and running lualatex I get

```
[...]
(/usr/local/texlive/2021/texmf-dist/tex/generic/babel/luababel.def) (/usr/local/texlive/2021/texmf-dist/tex/generic/babel/luababel.def)
! Incomplete \ifnum; all text was ignored after line 1379.
<inserted text>
\fi
l.2444   \input luababel.def

```

It is from a bigger project, so I cannot easily produce a minimal example.
And with another document there is no problem.

**Comment by callegar** [comment]
I confirm the bug.

**Comment by callegar** [comment]
Minimal test case: seems to be enough to load `babel` after `amsmath` to trigger the issue
```
\documentclass{article}
\usepackage{amsmath}
\usepackage{babel}
\begin{document}
test
\end{document}
```

**Comment by hvoss49** [comment]
Ah, that explains why I had no problem with another document!

**Comment by callegar** [comment]
@hvoss49 
If you are on texlive and you have tlmgr configured to take backups, `tlmgr restore babel 62007` can temporarily fix the issue for you by reverting to a previous version of babel.

**Comment by hvoss49** [comment]
thanks, I already did this.

**Comment by callegar** [comment]
> thanks, I already did this.
I never recognize github usernames! Still hope the advice can be useful to others landing on this page!

**Comment by callegar** [comment]
Another possibility for those not having a backup can be to keep a local copy of `luababel.def` in the current project. For convenience, I have attached it below (you need to get rid of the final `.txt` extension that is there just to make github happy).

[luababel.def.txt](https://github.com/latex3/babel/files/8146166/luababel.def.txt)

**Comment by FrankMittelbach** [comment]
@jbezos Javier, given that you recently made a number of fixes in that space it might pay off to set up a few regression tests files just testing various combination of package loads; I guess many of the recent issues might have been found through simply testing a few of that combinations and ordering

**Comment by jbezos** [comment]
@FrankMittelbach The actual problem is combinations sometimes tends to infinite. I have more than one thousand test files, including the sample files for tlc2 tested with several combinations of babel options, which leads to several thousand tests. I’m running them right now. I don't know how it happened, but it happened.

**Comment by FrankMittelbach** [comment]
I know :-) but still a few key permutations might help. Note that most of the test if done with the typical regression setup do not show errors if they happen during loading unless you explicitly tell them so.
