### ISSUE TITLE
locale-templates/phn: What do I need to do to get it into locale?

### ISSUE THREAD

**Issue by hanetzer** [latex3/babel#176]
As above. I'd like to use the phoenician script in some bible related documents. Is all that
is required within the babel repo, or do changes need to be made elsewhere in latex?

**Comment by jbezos** [comment]
¿With `pdftex`, `xetex` o `luatex`? With the two former, the files under templates mostly work , but you need in addition a font. Copy the two files under `phn` to a place where LaTeX can find them (usually the working directory is a valid place). Here is an minimal example with `luatex`:
```tex
\documentclass{article}

\usepackage[english, bidi=basic]{babel}

\babelfont[phoenician]{rm}{Noto Sans Phoenician}

\begin{document}

Text \foreignlanguage{phoenician}{𐤊𐤍𐤀𐤍𐤌} Text

\end{document}
```
![phoenician](https://user-images.githubusercontent.com/1314536/160441795-56c0b6c5-deff-4d70-b6cb-527ad387dd92.jpg)

For further help, please ask in forums like tex.stackexchange. Remember this issue tracker is for bugs and suggestion,
