### ISSUE TITLE
Weird behavior when using \babelfont with two styles in LuaTeX

### ISSUE THREAD

**Issue by NudPiyapon** [latex3/babel#178]
**Note:** This issue stems from stackexchange forum: [https://tex.stackexchange.com/questions/637687/weird-behavior-when-using-babelfont-with-two-styles-in-luatex](https://tex.stackexchange.com/questions/637687/weird-behavior-when-using-babelfont-with-two-styles-in-luatex)

Consider these MWEs.
```latex
\documentclass{article}

\usepackage[english]{babel}
\babelprovide[onchar=ids fonts]{english}
\babelprovide[main,import]{thai}
\usepackage{fontspec}

% \babelfont[thai]{rm}[
%     Script=Thai,
%     UprightFont = *.otf,
%     BoldFont = *-Bold.otf,
%     ItalicFont = *-Italic.otf,
%     BoldItalicFont = *-BoldItalic.otf]
%     {Laksaman}
\babelfont[thai]{rm}{FreeSerif}
\babelfont[thai]{sf}[
    Script=Thai,
    UprightFont = *.otf,
    BoldFont = *-Bold.otf,
    ItalicFont = *-Italic.otf,
    BoldItalicFont = *-BoldItalic.otf]
    {Laksaman}

\begin{document}
    ข้อความทดสอบ Test text.
    \textsf{ข้อความทดสอบ Test text.}
\end{document}
```
The following code produces expected result. (Correctly apply serif and sans-serif style)
![image](https://user-images.githubusercontent.com/50803100/159169501-ce885209-1211-44c0-8765-3d17b5116b73.png)

However, when I changed the serif font of Thai to the same as sans-serif one (Laksaman), the product of this code is formatted **wrong**. (The last test text's style is *serif*, not *sans-serif*)
```latex
\documentclass{article}

\usepackage[english]{babel}
\babelprovide[onchar=ids fonts]{english}
\babelprovide[main,import]{thai}
\usepackage{fontspec}

\babelfont[thai]{rm}[
    Script=Thai,
    UprightFont = *.otf,
    BoldFont = *-Bold.otf,
    ItalicFont = *-Italic.otf,
    BoldItalicFont = *-BoldItalic.otf]
    {Laksaman}
% \babelfont[thai]{rm}{FreeSerif}
\babelfont[thai]{sf}[
    Script=Thai,
    UprightFont = *.otf,
    BoldFont = *-Bold.otf,
    ItalicFont = *-Italic.otf,
    BoldItalicFont = *-BoldItalic.otf]
    {Laksaman}

\begin{document}
    ข้อความทดสอบ Test text.
    \textsf{ข้อความทดสอบ Test text.}
\end{document}
```
![image](https://user-images.githubusercontent.com/50803100/159169567-0501a07a-f4d1-46ca-b2c5-75644d34925d.png)

So, could anyone explains to me what happened here? Thanks in advances!

**Comment by jbezos** [comment]
I’ve posted a workaround in stackexchange, but I’ll investigate a general solution to this issue once TeXLive 2022 is released (I'm taking a short break).

**Comment by jbezos** [comment]
While investigating how to deal with these cases and how to improve the current algorithm, I discovered a very dirty trick: add a dummy `RawFeature` (e.g. `RawFeature=+xxxx`) to the second font. Seems to work.

**Comment by jbezos** [comment]
The workaround based on the `RawFeature` doesn’t work anymore, and what’s worse, the working example (with the expected result) doesn’t work with TeXLive 2023... 🙁 (it worked with 2022).
