### ISSUE TITLE
\grq builds a ligature with ! in T1-encoding

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#19]
babel.def provides definitions for `\grq`. The definitions differ for OT1 and T1 encoding, and in T1-encoding one gets a ligature if there is a preceding !:

~~~~

\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
\begin{document}
a!\grq

\fontencoding{OT1}\selectfont 
a!\grq
\end{document}

~~~~

![image](https://user-images.githubusercontent.com/4047173/60396718-51dd0a00-9b45-11e9-918f-f17f511a21dc.png)

**Comment by eg9** [comment]
Characters produced with `\char` participate to ligatures: under the T1 encoding, if you say
```latex
\char"60\char"60
```
you get a double quote. In `babel.def` we read
```latex
\ProvideTextCommand{\grq}{T1}{%
  \textormath{\textquoteleft}{\mbox{\textquoteleft}}}
```
Perhaps
```
\ProvideTextCommand{\grq}{T1}{%
  \textormath{\kern\z@\textquoteleft}{\mbox{\textquoteleft}}}
```
might solve the issue.

**Comment by jbezos** [comment]
It will be fixed in the next version.
