### ISSUE TITLE
Strange hyphenation of Zeijlstra: Ze-ijlstra

### ISSUE THREAD

**Issue by jasperhabicht** [latex3/babel#194]
By chance, I discovered that using `\usepackage[dutch]{babel}` the name Zeijlstra gets hyphenated in a very strange way, namely at the diphtong eij: Ze-ijlstra. I am not Dutch, but I highly doubt that this is correct. I would expect something like Zeijl-stra.

I am unsure whether this is the right place for reporting language-specific hyphenation issues. Also, since this problem is regarding a proper name, it should probably not be addressed at all. Please feel free to let me know how to proceed. I also tried to get in touch with the maintainer of the NL hyphenation package regarding this issue.

**Comment by jbezos** [comment]
I’m not an expert in Dutch hyphenation, but (with eplain)
```tex
\catcode`@=11
\language\l@dutch
\showhyphens{Zeijlstra}
\bye
```
shows
```
[] \tenrm Ze-ijlstra
```
So, there is nothing wrong in `babel`. Hyphenation patterns are maintained here: https://github.com/hyphenation/tex-hyphen
