### ISSUE TITLE
Option handling is broken with braces

### ISSUE THREAD

**Issue by Skillmon** [latex3/babel#198]
If the global option list or the package option list of `babel` contains braces the checks for conflicts in the load order of languages due to global and local options is broken and leads to a `Missing \begin{document}` error. The problematic code is the code starting in line 4428 of the current `babel.sty`:

```latex
  \bbl@for\bbl@tempb\bbl@tempa{%
    \bbl@xin@{,\bbl@tempb,}{,\bbl@loaded,}%
    \ifin@\edef\bbl@tempc{\bbl@tempb}\fi}
```

MWE:

```latex
\documentclass[foo={bar}]{article}

\usepackage[english]{babel}

\begin{document}
\end{document}
```

**Comment by jbezos** [comment]
Formerly the braces were not allowed. I’ll adapt it to this new behavior.

**Comment by Skillmon** [comment]
@jbezos yes, they weren't. I just noticed that now that they are they break `babel` :) Thanks for the fix!
