### ISSUE TITLE
Deprecated \textlatin conflicts with Babel tags

### ISSUE THREAD

**Issue by adunning** [latex3/babel#2]
## Brief outline of the bug

Babel's deprecated `\textlatin` command conflicts with attempting to set up a `latin` language with `\babeltags`. (I am using this label specifically because Polyglossia uses `\textlatin` and the markup should ideally work with either package.) Given the deprecated status, I would expect the `\babeltags` definition to override the existing command.

## Minimal example showing the bug

```latex
\RequirePackage{latexbug}
\documentclass{article}
\usepackage[latin]{babel}
\babeltags{latin = latin}

\begin{document}

\textlatin{Tempto}

\end{document}
```

## Log file (required) and possibly PDF file  

[latin.log](https://github.com/latex3/latex2e/files/2721382/latin.log)

**Comment by jbezos** [comment]
I’ve considered several times to extended somehow `\babeltags`, but I’ve come to the conviction this is not the way to go. This macro is just a convenience tool for quick declarations of shortened language selectors, and it has exactly the same limitations as `\newcommand`. I think it must be kept simple, and, as pointed out by Ulrike above, “`babel` can’t start to overwrite some commands and give error on others”.
