### ISSUE TITLE
Exam class support

### ISSUE THREAD

**Issue by Felipe-Math** [latex3/babel#206]
There exists the interest in add support the `exam` class in the babel package?

The exam class use some labels that can be changed with simple commands like `\chpword{Pontos}`.

For my exams in Portuguese Brazillian I translate the labels, so It is easy to adapt it to be used in babel package.

If the babel team accept to support the exam class, I could implement the brazilian portuguese version.

**Comment by jbezos** [comment]
`babel` provides the framework for packages and classes to localize documents. The localized strings for the `exam` class must be defined in the class, so you should contact its authors.
