### ISSUE TITLE
Incorrect link box in end of line if  it is preceded  by a non-Arabic character

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#207]
This example shows the problem 
```latex
\documentclass{article}
\usepackage{hyperref}
\usepackage[bidi=basic]{babel}
\babelprovide[import, main]{arabic}
\babelfont{rm}{Amiri}


\begin{document}

\begin{figure}
\centering
\rule{4cm}{4cm}
\caption{test}
\label{im}
\end{figure}

A
\ref{im}   % Wrong 

تجريب A
\ref{im}   % Wrong

تجريب
\ref{im}   % Fine

A
\ref{im} . % Wrong

A
\ref{im} B % Fine

\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/206568257-14a0374b-051e-4514-b052-7bd2ae6ca91e.png)

**Comment by u-fischer** [comment]
looks ok here:

![image](https://user-images.githubusercontent.com/4047173/206576342-1cf898e4-b92d-4afd-b37f-36835513c9d4.png)


Are you using a current luatex?

**Comment by jbezos** [comment]
I’m reopening the issue because the current fix is somewhat simplistic and only works with some typical cases.
