### ISSUE TITLE
Enhancement request: Make as as many package options as possible settable post loading

### ISSUE THREAD

**Issue by EvanAad** [latex3/babel#209]
Please make as as many package options as possible settable post loading. Some document classes, such as `beamer`, load `babel`, in which case the only way to pass `babel` package options is by including them in the class option list. This makes it unwieldy and ugly. Take `layout`, for instance. Is it necessary to pass it as a package option? Can it not be specified post loading? A mechanism similar to `enumitem`'s `\setlist` or to `tikz`'s `\tikzset` would be great. And then perhaps mutliple values can also be separated by commas, as is usual, rather than by dots.

**Comment by jbezos** [comment]
`babel` is a huge package and there is no point in storing everything in memory just in case. If you want to add options to `babel`, use `\PassOptionsToPackage{<options>}{babel}` before loading it (eg, before `\documentclass`). Alternatively,  `\PassOptionsToPackage{base}{babel}` makes `babel` to almost immediately exit in such a way a second `\usepackage[<options>]{babel}` is possible.
