### ISSUE TITLE
Copy and Paste in Manual: "p i n y i n" vs "pinyin" (Version 3.32)

### ISSUE THREAD

**Issue by manuel-kuehner** [latex3/babel#21]
- When I copy and paste text from the manual of Version 3.32, then the text has additional spaced in it.
- This makes it hard to search the PDF, since "pinyin" is not found for example, whereas "p i n y i n" is found.
- I use a current Adobe Reader (DC) installation on a Windows 10 computer.
- Is this a local problem to me or do others have similar problems?

**Comment by jbezos** [comment]
It seems a bug in the fonts I'm using (in Sumatra they work, but not in Adobe or PDF-XChange). I'll update them.
