### ISSUE TITLE
Support using the Swash Kaf character for Arabic justification

### ISSUE THREAD

**Issue by amarakon** [latex3/babel#222]
In Arabic, I use kashida justification which inserts the Tatweel character (`U+0640`) between letters at the correct length to justify the text. Of course, I can change the factor of kashida to space by setting `Babel.arabic.justify_factor` to any value between 0 and 1. I think it would be great if there was a justification feature to automatically replace instances of the regular Kaf character (`U+0643`) with the Swash Kaf character (`U+06AA`), which is slightly wider. Then, as a fallback if the line still isn't justified, it should fall back to regular justification (kashida or space). If the Swash Kaf is too wide to justify the line, or if there are no longer any Kafs on the line, regular justification should be used. I don't know how difficult it is to implement this. Please let me know if this is possible or planned for the future.

**Comment by jbezos** [comment]
It’s certainly planned, by I originally thought of it as part of the `elongated` justification mode (with the JALT OpenType table). I would make sense to provide it as a separate feature with kashida. There is another planned mode, based on the breaking of ligatures, but sadly I’ve found no time the develop them and furthermore information about the JALT table is scarce.

**Comment by amarakon** [comment]
Okay. Could the swash kaf idea I proposed still work on a font that doesn't support elongated glyphs?

**Comment by jbezos** [comment]
Yes, it should, because every font for Arabic (or most of them) contain the swash kaf (it‘s encoded as a separate character because it’s a letter on its own in Sindhi). I'll to reconsider my priorities, because, unlike the JALT variants, I think  it can be done more or less straightforwardly (or so I hope).

**Comment by jbezos** [comment]
I‘m closing this issue because it’s now listed in [Enhancements requests](https://github.com/latex3/babel/projects/1). This doesn’t mean it’s rejected, just moved to a specific page for enhancements.
