### ISSUE TITLE
Korean - \localecounterl \localenumeral - typo

### ISSUE THREAD

**Issue by J-J-Chiarella** [latex3/babel#225]
For `\localecounter` and `\localenumeral` one of the styles for Korean reads `syllabe` instead of `syllable`.

The options are:

`consonant`, `syllabe`, `hanja.informal`, `hanja.formal`, `hangul.formal`,
`cjk-earthly-branch`, `cjk-heavenly-stem`, `circled.ideograph`,
`parenthesized.ideograph`, `fullwidth.lower.alpha`, `fullwidth.upper.alpha`

By `syllabe`, I assume this is "syllable" (should be `syllable`). This is `가`, `나`, `다`, `라`, `마`, `바`, `아`, `사`, `자`, `차`, `카`, `타`, `파`, and `하`. Imagine going "Ah," "Bah," "Cah," "Dah," "Fah," Gah," etc.

I am only just starting to mess around with `babel` after learning LaTeX for a dissertation and liking LaTeX enough to try to use it for everything. I am not versed enough in LaTeX or programming to check `.sty` files or anything, and so this mistake may be consistent. (Fixing it could make this package more intuitive but "break" current templates unless people fix this typo ... but Korean adoption of LaTeX is in the ballpark of 10, 12 users. This isn't a problem.) Or, this mistake may only be in the CTAN documentation.

Refer to the documentation: <https://mirror.math.princeton.edu/pub/CTAN/macros/latex/required/babel/base/babel.pdf> (p. 3)

Thank you for your time.

**Comment by jbezos** [comment]
Thanks. It’s a typo and therefore should be considered a bug to be fixed.
