### ISSUE TITLE
Set a maximum stretchability for kashida in Arabic

### ISSUE THREAD

**Issue by amarakon** [latex3/babel#242]
I know that I can control the ratio of kashida to space justification with `\directlua{Babel.arabic.justify_factor = n}` where *n* is any number between 0 and 1. I always like to set this to 1. Full kashida justification looks good on lines that aren’t stretched too much. But on lines that are unluckily extremely stretched, it looks bad, and I would prefer to start use spacing to justify that line. In the following image, you will see that all of the lines look great, except for the second line which has too much kashida.

![import-2023-05-11_20:35:30](https://github.com/latex3/babel/assets/92645199/4ffd900a-7be9-448a-9141-4d01c98161f8)

The problem with `Babel.arabic.justify_factor` is that it applies globally. I propose for the ability to set the maximum amount the kashida is allowed to stretch and from then it should start using spacing to achieve justification, regardless of the justification factor.

**Comment by amarakon** [comment]
I initially thought to be able to set a length of the maximum amount the tatweel can be. But I did not know that the tatweel can't be stretched arbitrarily, and that there has to be an integer number of tatweel. So to answer your question: Yes, I want to be able to force a maximum in the number of tatweel.

**Comment by jbezos** [comment]
There is a Unicode character for the tatweel (U+0640). `babel` adds it at the appropriate places as set by the active transforms, and in the appropriate number. This feature will be available in the next release (written, but not yet committed).
