### ISSUE TITLE
Hyphenation of the Estonian word "mõistmisel" is incorrect. 

### ISSUE THREAD

**Issue by piiskop** [latex3/babel#245]
The input:

```
\documentclass{report}
	\usepackage[estonian]{babel}
	\setlength{\columnsep}{512pt}
\begin{document}
\twocolumn
	hilisemal mõistmisel 
\end{document}
```

The output:

> hilisemal
> mõist-
> mis-
> el
> 1

The expected output:

> hilisemal
> mõist-
> mi-
> sel
> 1

**Comment by jbezos** [comment]
Thank you, but hyphenation patterns are not part of babel and are maintained separately: https://github.com/hyphenation/tex-hyphen.
