### ISSUE TITLE
extras layout is broken

### ISSUE THREAD

**Issue by Udi-Fogiel** [latex3/babel#246]
The extras layout is patching `\underline` with `\bbl@sreplace\underline{$\@@underline}{\bbl@nextfake$\@@underline}`, but  [\underline was robustified](https://github.com/latex3/latex2e/commit/96832b85fe483a7d3209e75f86442f7458f7fe53#diff-5187be7e3233f8844e8427516e0b38b61ca8ebf4706bde7fbb985a21107e19c2R1143) a few years back.  

I think this patch fails as `\bbl@sreplace`  is not really aware of robustified commands (and the output they give in `\meaning`). 

Here is a small example to demonstrate the error

```Latex
\documentclass{article}
\usepackage[layout = extras]{babel}

\begin{document}
	
\end{document}
```

With `\xpatchcmd` it seems to work:

```Latex
\documentclass{article}

\usepackage[bidi = basic, hebrew, provide=*, layout = tabular]{babel}

\babelfont[hebrew]{rm}{David CLM}

\usepackage{xpatch}
\makeatletter
\xpatchcmd\underline{$\@@underline}{\bgroup\bbl@nextfake$\@@underline}{}{}
\xpatchcmd\underline{$\relax}{$\egroup\relax}{}{}
\makeatother

\begin{document}
    \underline{שלום $C^n$}
\end{document}
```

or maybe redefinition would be preferable:

```Latex
\documentclass{article}

\usepackage[bidi = basic, hebrew, provide=*, layout = tabular]{babel}

\babelfont[hebrew]{rm}{David CLM}

\makeatletter
\DeclareRobustCommand\underline[1]{%
    \relax
    \ifmmode\@@underline{#1}%
    \else 
    \bgroup\bbl@nextfake$\@@underline{\hbox{#1}}\m@th$\egroup\relax\fi} 
\makeatother

\begin{document}
    \underline{שלום $C^n$}
\end{document}
```

[Related post from TeX.SE](https://tex.stackexchange.com/questions/690060/math-direction-changes-inside-underline-when-using-babel-with-bidi)

**Comment by jbezos** [comment]
Fixed in https://github.com/latex3/babel/commit/ea1b21935952d73638a8be4fbd23ba331ff1eec7
