### ISSUE TITLE
Tibetan line breaks

### ISSUE THREAD

**Issue by BenjaminGalliot** [latex3/babel#250]
I have many problems with line breaks (and justification) for Tibetan, especially with LuaLaTeX but not only...

From what I've noticed:
- with LuaLaTeX, I couldn't get line breaks at all...
- with XeLaTeX, 3 cases:
  - if a CJK language has been used before, there are line breaks (and the lines are justified);
  - if `\XeTeXlinebreaklocale` has been activated, same (but lines are not justified);
  - otherwise, no line breaks...

My goal is to keep LuaLaTeX, but I have no clue how to go about it...

MWE:

```latex
\documentclass{book}

\usepackage{multicol}
\usepackage[french]{babel}

\babelprovide[import]{tibetan}

\babelfont[french]{rm}{Liberation Serif}
\babelfont[tibetan]{rm}{Noto Serif Tibetan}
\babelfont[chinese]{rm}{Noto Serif CJK TC}

\setlength{\parindent}{0pt}

\begin{document}

% \XeTeXlinebreaklocale "bo"

\begin{multicols}{3}

\selectlanguage{french}

Test : bonjour !

% \selectlanguage{chinese}

% 中文

\selectlanguage{tibetan}

སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།

\end{multicols}

\end{document}
```

Have I missed something?

Edit 1:

For information, with Polyglossia, it works with both engines (without using CJK language nor the `XeTeXlinebreaklocale` command beforehand), but the management of justified lines (and spaces) is much less pretty with LuaLaTeX than with XeLaTeX.

MWE (Polyglossia):

```latex
\documentclass{book}

\usepackage{multicol}
\usepackage[french]{babel}

\usepackage{polyglossia}
\setdefaultlanguage{french}
\setotherlanguages{tibetan}

\newfontfamily\tibetanfont{Noto Serif Tibetan}

\setlength{\parindent}{0pt}

\begin{document}

% \XeTeXlinebreaklocale "bo"

\begin{multicols}{3}

\selectlanguage{french}

Test : bonjour !

% \selectlanguage{chinese}

% 中文

\selectlanguage{tibetan}

སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།སྒོ་ར་འདིའི་ནང་རྒྱ་རིགས་དང་། བོད་རིགས། ཁ་ཆེ་ཚང་མ་འདྲེས་བསྡད་ཡོད་རེད།

\end{multicols}

\end{document}
```

**Comment by jbezos** [comment]
With the following font setup (just to adapt the mwe to my configuration and to use Harfbuzz):
```tex
\babelfont[french]{rm}{Liberation Serif}
\babelfont[tibetan]{rm}[Renderer=Harfbuzz]{NotoSerifTibetan-Regular.ttf}
```
I’m getting with luatex:
![image](https://github.com/latex3/babel/assets/1314536/83ff703e-7926-4a81-bf93-1601dce157bb)

And with xetex (note the tshegs are slightly displaced to the left and spacing with shads is irregular):
![image](https://github.com/latex3/babel/assets/1314536/d9699174-06f9-439e-abfa-3b56cb849798)

**Comment by jbezos** [comment]
Also— Have a look at https://latex3.github.io/babel/news/whats-new-in-babel-3.81.html.

**Comment by BenjaminGalliot** [comment]
At first, it didn't change anything with what you said, which allowed me to see that I was still using Texlive 2021 (due to other tests). With Texlive 2023, it works fine (which is consistent with your last link, which dates from the end of 2022), and `[Renderer=Harfbuzz]` option changes indeed very finely some details that I do not notice with the eye.

Thank you!

**Comment by jbezos** [comment]
Glad it helped. If you need further help, just continue this thread.

**Comment by BenjaminGalliot** [comment]
Hello, I have a new issue with LuaLaTeX, with a line break problem when adding a parenthesis.

The new MWE:

```latex
\documentclass[12pt]{book}

\usepackage{multicol}

\usepackage{polyglossia}
\setdefaultlanguage{french}
\setotherlanguages{tibetan}

\newfontfamily\tibetanfont{Jomolhari-Regular.ttf}

\setlength{\parindent}{0pt}

\begin{document}

\begin{multicols}{3}

\selectlanguage{tibetan}
་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་་སྐད་(ཆེན་པོ་)བརྒྱབ་པ།ངས་སྐད་བརྒྱབ་པ་ཡིན། ཡིན་ནའང་ཁོང་གིས་གོ་མ་སོང་།སྐད་(ཆེན་པོ་)བརྒྱབ་པ།ངས་སྐད་བརྒྱབ་པ་ཡིན། ཡིན་ནའང་ཁོང་གིས་གོ་མ་སོང་།སྐད་(ཆེན་པོ་)བརྒྱབ་པ།ངས་སྐད་བརྒྱབ་པ་ཡིན། ཡིན་ནའང་ཁོང་གིས་གོ་མ་སོང་།སྐད་(ཆེན་པོ་)བརྒྱབ་པ།ངས་སྐད་བརྒྱབ་པ་ཡིན། ཡིན་ནའང་ཁོང་གིས་གོ་མ་སོང་།  
\end{multicols}

\end{document}
```

With LuaLaTeX:
![Screenshot_20240318_224121](https://github.com/latex3/babel/assets/23100612/68089662-8894-4fd9-a877-b27c738b5f67)

With XeLaTeX:
![Screenshot_20240318_224109](https://github.com/latex3/babel/assets/23100612/2cb34862-94e7-4fdc-8c0b-34601f94dd81)

As you can see in LuaLaTeX, a tsheg followed by a closing parenthesis will break the line right between them, instead of breaking the line after the closing parenthesis, as can be seen in XeLaTeX…

Another question: is there a simple way to prevent a single syllable from being alone on its line (beginning – in the case where the line incorporates other languages just before – or end)?

Thanks a lot!

**Comment by BenjaminGalliot** [comment]
Hello,

I've noticed another problem, involving Tibetan word breaks when there's another language on the same line.

This affects both XeLaTeX and LuaLaTeX, but with variations... 

The behavior seems to be improved with XeLaTeX if language changes are made with `selectlanguage` and not with `foreignlanguage`.

I'm using the latest version of Texlive 2024 (updated 2 days ago).

Here is the MWE:

```latex
\documentclass{article}

\RequirePackage{babel}
\babelprovide[import=bo]{tibetan}
\babelprovide[import=fr]{french}

\babelfont[french]{rm}{EB Garamond}
\babelfont[french]{sf}{EB Garamond}
\babelfont[french]{tt}{EB Garamond}

\babelfont[tibetan]{rm}{Jomolhari}
\babelfont[tibetan]{sf}{Jomolhari}
\babelfont[tibetan]{tt}{Jomolhari}

\begin{document}

\section{Everything foreignlanguage}

\foreignlanguage{tibetan}{དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།}

\foreignlanguage{tibetan}{དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།}

\section{Tibetan selectlanguage, Latin foreignlanguage}

\selectlanguage{tibetan}

དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།

དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ \foreignlanguage{french}{TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།

\section{Tibetan foreignlanguage, Latin selectlanguage}

\foreignlanguage{tibetan}{
དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།}

\foreignlanguage{tibetan}{དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།}

\section{Everything selectlanguage}

\selectlanguage{tibetan}

དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ TB ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།

དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད། དེང་སང་ {\selectlanguage{french}TB} ན་ཚ་ན་ནའང་སྨན་ཡག་པོ་བཟས་ན་གློ་བ་བཀོག་དགོས་མ་རེད།

\end{document}
```

Here are the screenshots:

LuaLaTeX:
![lualatex](https://github.com/latex3/babel/assets/23100612/30779840-6107-49a0-aa48-910d3be6ad6c)

XeLaTeX:
![xelatex](https://github.com/latex3/babel/assets/23100612/e51216da-d534-47c8-abce-7e9f1759e5e7)
