### ISSUE TITLE
Check and, if necessary, improve the hyphenation of “memorandum” in British English

### ISSUE THREAD

**Issue by AlMa0r** [latex3/babel#253]
According to The *New Oxford Spelling Dictionary, The Writers' and Editors' Guide to Spelling and Word Division* by Maurice Waite, 2005, ISBN 0-19-860881-0, ISBN 978-0-19-860881-3 (cf. an [online library](http://archive.org/details/newoxfordspellin0000unse_n6f1/page/313/mode/1up)), page 313, it's
```
memo|ran¦dum
memo|randa
memo|ran¦dums
```
The 5th, 6th, 7th, and 9th printed editions of Oxford Advanced Learner's Dictionary of Current English by A S Hornby also say
```
memo•ran•dum
```
Ideally, also the current version of these dictionaries as well as *The Oxford minidictionary of spelling and word division* should be consulted, but I don't have either of them.

However, the current LaTeX says `memor-andum`. This is probably (?) an error and should be improved.

Discussion: http://tex.stackexchange.com/questions/691742 .

**Comment by u-fischer** [comment]
Hyphenation patterns are not maintained by babel.  The patterns are part of the hyph-utf8 package https://www.ctan.org/pkg/hyph-utf8.
