### ISSUE TITLE
babel is not aware of \if@nonlatin conditional from bidi

### ISSUE THREAD

**Issue by Udi-Fogiel** [latex3/babel#256]
bidi use a separate conditional from `\if@RTL` called `\if@nonlatin` in several places in its code, this conditional is not set by `\RL`, `\setRL` etc., so babel need to set this conditional according to the script (see section 4.4 of bidi's manual). 

 The places I'm aware it is used are in equation tags (in `amsmath` and `mathtools`) to correct the parenthesis,  see [[1]](https://github.com/kvafa/bidi/blob/45c7f3025e2eb29f167cbf8dfe6ea8e92c41cb5b/bidi.dtx#L728) and [[2]](https://github.com/kvafa/bidi/blob/45c7f3025e2eb29f167cbf8dfe6ea8e92c41cb5b/bidi.dtx#L19775), in breqn (not sure for what), in `\text` from `amsmath` to correct the direction of the text, see [[3]](https://github.com/kvafa/bidi/blob/45c7f3025e2eb29f167cbf8dfe6ea8e92c41cb5b/bidi.dtx#L744), and in a code it inserts between numbers and dots and dashes via `\XeTeXinterchartoks`,  see [[4]](https://github.com/kvafa/bidi/blob/45c7f3025e2eb29f167cbf8dfe6ea8e92c41cb5b/bidi.dtx#L4865C1-L4865C20), which I guess suppose to correct the order in arabic, but is wrong for hebrew and other languages (so it should be disabled sometimes). 

Here is a code to demonstrate the problem with `\text` and tagged equations
```tex
\documentclass{article}

\usepackage{amsmath}
\usepackage[hebrew,provide=*,bidi=bidi-r]{babel}
\babelfont{rm}{David CLM}

\begin{document}
%\makeatletter\@nonlatintrue
\begin{equation}
1+2=3
\end{equation}

$\text{שלום עולם!}$
\end{document}
```

And this is a code to demonstrate the problem with the code that bidi inserts via `\XeTeXinterchartoks`
```tex
\documentclass{article}

\usepackage[hebrew,provide=*,bidi=bidi-r]{babel}
\babelfont{rm}{David CLM}

\begin{document}
\makeatletter\@nonlatintrue
1-2
\end{document}
```

**Comment by jbezos** [comment]
Interestingly, `\setlatin` and `\setnolatin` are not documented (but they are defined). Certainly `bidi` is about ‘Arabic bidi’ and I’m not sure the order must be fixed in `babel` or in `bidi`. I'm thinking about it.

**Comment by Udi-Fogiel** [comment]
>I’m not sure the order must be fixed in `babel` or in `bidi`. I'm thinking about it.
It always looked odd to me that bidi do that, isn't the script of the font should handle that by Itself?

FWIW, [this](https://github.com/reutenauer/polyglossia/commit/8c642fc94a6572a9fb61ac29e550a30c2bc545cb) is what polyglossia do (for several languages).
