### ISSUE TITLE
latvian together with titlesec cause error

### ISSUE THREAD

**Issue by leomayer** [latex3/babel#264]
I've encountered an issue and it was very well [analysed](https://tex.stackexchange.com/a/696891/48642). The MWE

```
\documentclass[a4paper,11pt]{article}
\usepackage[latvian,shorthands=off]{babel}
\usepackage{titlesec}

%%% ensure \chapter passes the \ifx\chapter\undefined test
%\let\chapter\undefined
%%%

\begin{document}
	\begin{figure}[!htbp]
		\caption{Sample text}
	\end{figure}
	
\end{document}
```

Changing to e.g. `french` the code compiles without problems. Perhaps the issue might appear in other languages as well?

**Comment by jbezos** [comment]
Fixed on the `titlesec` side. It remains to be fixed fixed on the `babel-latvian` side.

**Comment by jbezos** [comment]
Fix just submitted to CTAN.
