### ISSUE TITLE
ensureascii issues.

### ISSUE THREAD

**Issue by gmilde** [latex3/babel#265]
If I load font encoding T1, T2A, and LGR, the latinencoding is T1
but inside ensureascii, the encoding is T2A -- no matter which order I set T1 and T2A:
~~~
\documentclass{article}
\usepackage[T2A,T1,LGR]{fontenc}
% \usepackage[T1,T2A,LGR]{fontenc}
\usepackage[english,polish]{babel}
\makeatletter
\begin{document}
\textlatin{The latinencoding is \latinencoding}

\ensureascii{but inside ensureascii, the font encoding is \cf@encoding
(деиствительно).}

\end{document}
~~~
Maybe this has to do with the special status of T1: it is preloaded and
fontenc's `\@fontenc@load@list` is T1,OT1T2A,T1,LGR.

**Comment by jbezos** [comment]
`babel` ignores the preloaded languages and in fact it works for me as expected (the last ASCII encoding wins), but I have to update my TeXLive first.

**Comment by jbezos** [comment]
Updated TeXLive and still working. Please, copy the file list or the `log` file.

**Comment by gmilde** [comment]
I tested again with an up-to-date TeXLive23 and the TeXLive21 from Debian/bookworm.
The issue only manifetst with the legacy TeXLive21. With an up-to-date installation, the last ASCII-compatible encoding wins :)
Sorry for the noise.

There is, however another problem which persists: Thefont encoding LGI is not detected
as non-standard:
\documentclass{article}

\usepackage[T1,LGI,OT2]{fontenc}
\usepackage[english]{babel}
\makeatletter

\begin{document}

default \encodingdefault,
active \cf@encoding,
\ensureascii{ensureascii \cf@encoding},
\textlatin{latinencoding \latinencoding}.

\LaTeX

\ensureascii{this should be Latin script}
\end{document}

**Comment by gmilde** [comment]
One more non-standard encoding is T3.
Note the misleading name!

\documentclass{article}

\usepackage[T1,T3]{fontenc}
\usepackage[english]{babel}
\makeatletter

\begin{document}

Encodings:
default \encodingdefault,
active \cf@encoding,
\ensureascii{ensureascii \cf@encoding},
\textlatin{latinencoding \latinencoding}.

\LaTeX is toll

\ensureascii{abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ}

\ensureascii{0123456789 .,!?()}
\end{document}

**Comment by gmilde** [comment]
Thank you for the explanation. I am fine with T3.

I suggest adding the LGI encoding to the nonASCII list:
LGI is a nonASCII encoding from the ibycus-babel package

~~~
\documentclass{article}

% \usepackage[LGI,T1]{fontenc}
\usepackage[english,ibycus]{babel}

\begin{document}
\makeatletter

\textlatin{Compiled with format version \fmtversion{},
patch-level ***@***.***{}.}

\textlatin{Babel Version: \csname ***@***.***\endcsname}.

\ensureascii{ensureascii: ***@***.***},
\textlatin{latinencoding: \latinencoding, language: ibycus}

\medskip

Elleniki: Agapa'me \LaTeX (\textlatin{sic!})

\ensureascii{ensureascii: We love \LaTeX (\textlatin{sic!})}

\textlatin{textlatin: We love \LaTeX}

\foreignlanguage{english}{English: We love \LaTeX}

\end{document}

~~~
