### ISSUE TITLE
I made some modification to `babel-fa.ini` file for Persian language

### ISSUE THREAD

**Issue by farshadrasuli** [latex3/babel#271]
I am a native Persian narrator. There are some small mistakes in the `babel-fa.ini` file that need to be fixed. You can download the fixed file from here [babel-fa.zip](https://github.com/latex3/babel/files/13464338/babel-fa.zip). Modifications made are commented by ` % modified by farshad rasuli`.
 
 
Best wishes,
 
 
 
Farshad Rasuli

**Comment by jbezos** [comment]
@farshadrasuli Thank you. I’m taking a look at it and I was a bit puzzled by the spelling of پیش‌گفتار. Is this correct for the noun (not the verb) “preface”? There are currently some mistakes (صفحة) and in other cases the new strings just seem a stylistic or editorial variant (much like English «Contents» vs «Table of Contents»). I wouldn’t like to change variants except if there is a compelling to do so, so can you clarify which changes are actual errors, and which one are variants (and why to modify them, if necessary).

**Comment by farshadrasuli** [comment]
Thanks for taking the time to consider. I will provide explanations about these few things you said. First, let me say that these suggestions are syntactical (grammatical) and not editorial.
1. `ref`: reference means «مرجع», and the plural form (references) is «مرجع‌ها». The word «مراجع» is the Arabic plural form not Persian/Farsi plural form. On the other hand, «مرجع» is not the only word used for “reference”. Another word for “reference” is «منبع», which the correct plural form is «منبع‌ها». To clarify of the use of these two words in Persian/Farsi, it should be noted that «مرجع‌ها» refers to the sources **that are cited** in the manuscript and «منبع‌ها» refers to the sources **that are not cited but used**.
2. `contents`: contents refers to the list/table of headings of a manuscript. The best choice for this purpose is «فهرست» which means “List”, or “table”. If you insist on translating “content”, which means «مطلب», you must use the correct plural form for this word in Persian/Farsi: «مطلب‌ها» (Persian/Farsi plural form of «مطلب»). And “Table of Contents” means «فهرست مطلب‌ها».
3. `listfigure`: this and the next item in this list have one thing in common: the “list”. The word «لیست» is the pronunciation of the word “List” in English, which is a huge mistake used by Persian/Farsi speakers. The correct translations of this word are «فهرست», and «سیاهه». The word «فهرست» is more common. The word “figure” refers to the shape, which means «شکل» in Persian/Farsi and the plural form is «شکل‌ها». The word «تصاویر», which is the plural form of «تصویر», means “images/pictures”. Using «تصاویر» instead of «شکل‌ها» is wrong and misleading.
4. `listtable`: the plural form of «جدول» is «جدول‌ها». As with references, «جداول» is the Arabic plural form, which is incorrect.

I hope that my explanations were sufficient and clear.
 
 
 
Best wishes,
 
 
 
Farshad Rasuli
