### ISSUE TITLE
Shorthands create issues when creating new environments

### ISSUE THREAD

**Issue by rlkamalapurkar** [latex3/babel#282]
*I [asked this question on StackExchange](https://tex.stackexchange.com/questions/708581/how-to-handle-babel-active-characters-when-writing-a-package), and a suggestion was to reach out to you to see if shorthands can be protected.*

In the `bodeplot` package, I defined new environments using (defined like this to [avoid issues with externalization of `tikz` graphics](https://tex.stackexchange.com/q/15595/110602))
```
\documentclass{standalone}
\usepackage{pgfplots,xparse}
\pgfplotsset{compat=1.18}
\NewDocumentEnvironment{MyEnv}{O{}mm+b}{
  \begin{tikzpicture}
    \begin{semilogxaxis}[xmin={#2},xmax={#3},ymin=0,ymax=1]
      #4
    \end{semilogxaxis}
  \end{tikzpicture}
}{}
```
I want users to be able to use the new environment to do things like this
```
\begin{document}
  \begin{MyEnv}[]{1e-1}{1e4}
    \draw[thick,blue,dashed] (axis cs:1,0) -- (axis cs:100,1);
    \addplot[variable=t,domain=1e-1:1e4] gnuplot {(t>100)?0.2:0.5};
  \end{MyEnv}
\end{document}
```
All of this works out for English language documents. However, if a user uses `babel` with any language that uses some characters in `#4` as a shorthand, the document cannot be compiled. For example, if I add
```
\usepackage[french]{babel}
\usetikzlibrary{babel}
```
to the preamble, I get compilation errors. The errors persist even if I add `\csname @safe@activestrue\endcsname`.

I managed to make it work for the French language by checking for `frenchbsetup` and using
```
\AddToHook{env/MyEnv/begin}{\shorthandoff{;:!?}}
```
if it is detected. However, doing something like this for every shorthand in every language seems like the wrong approach to solve this issue.

Is there a better way detect and manage shorthands in macros like this that will work with all languages supported by `babel`?

**Comment by jbezos** [comment]
Related: #196.

**Comment by rlkamalapurkar** [comment]
@u-fischer the protection you outlined above seems to be incompatible with the `babel` `tikz` library. Adding `\usetikzlibrary{babel}` to your MWE above gives me 

`! File ended while scanning use of \path.`

I can confirm that the "collect all shorthands in a macro and disable them" approach, suggested by @jbezos on StackExchange, works fine with or without the `babel` library.

I do not know enough about `TeX` to understand why, but I figured letting you know would help!

**Comment by jbezos** [comment]
Glad it helped. As I said in stackexchange, a more user friendly way to switch all shorthands on or off can be useful. (Added to my todo list.)
