### ISSUE TITLE
Provide install instructions

### ISSUE THREAD

**Issue by elyahw** [latex3/babel#283]
I use ubuntu I use `sudo apt install texlive-full` to install the latex environment (along with texstudio).

There is a bug fix in babel which I would like to use, but `tex-live` is only updated once a year.

Can you please provide instructions how to install the babel package manually? It can be downloaded from https://ctan.org/pkg/babel but there are no instructions on how to install it..

**Comment by josephwright** [comment]
TeX Live is updated more-or-less _every day_: you mean rather that the Ubuntu version is rather slower. Most of the time, the advice if you want to use a more up-to-date system is to us 'vanilla' TeX Live from TUG rather than your system managed one (i.e. more or less the same was Windows and macOS users have anyway). See e.g. https://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu on this

That said: `babel` is no different to any other (La)TeX package for 'local' installation, so e.g. https://tex.stackexchange.com/questions/1137/where-do-i-place-my-own-sty-or-cls-files-to-make-them-available-to-all-my-te covers things.

**Comment by elyahw** [comment]
I also use archlinux and it is exactly the same situation, the packages are called `texlive-basic` and `texlive-latex` and they are rarely updated..

I will try what you suggested. Thanks for the links.

**Comment by FrankMittelbach** [comment]
@elyahw I wonder if these packages are real TL packages or largely crippled (beside not being updated more than once a year). If they are real, you probably have `tlmgr`  from TeX Live on your machine through which you can update your system yourself.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  no typically you can't use `tlmgr` (or only in limited ways) with a linux system texlive,  as that is set up to pull from a texlive repo but these have been re-packged to take part in a standard linux package management via apt or yum or whatever the distro uses which means that other linux applications with a depenency on tex can be tracked but relies on the system texlive packages being updated which is typically less frequent than the daily upstream tl updates.

**Comment by jbezos** [comment]
@elyahw There are minimal instructions [here](https://latex3.github.io/babel/#installation). Follow its advice and install TeXLive 🙂.

**Comment by elyahw** [comment]
I know this might be a separate issue but this is what happened:

I removed all **texlive/latex** installations on my system, and I installed **texlive** manually using the installation script, by following instructions here:
https://tug.org/texlive/quickinstall.html

Now I have the folder `/usr/local/texlive/2023/` on my system.

I appended `export PATH=/usr/local/texlive/2023/bin/x86_64-linux:/usr/local/texlive/2023/bin:$PATH` to `~/.bashrc`

I try to compile a minimalist tex file in **Texstudio**. I add the path `/usr/local/texlive/2023/bin/x86_64-linux:/usr/local/texlive/2023/bin` to the `$PATH` field (Settings -> Build). But I get the error:

```
Process started: lualatex -synctex=1 -interaction=nonstopmode "basic sample".tex

warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/bin:/usr/bin/share/texmf-local/web2c:/usr/bin/share/texmf-dist/web2c:/usr/bin/share/texmf/web2c:/usr/bin/texmf-local/web2c:/usr/bin/texmf-dist/web2c:/usr/bin/texmf/web2c:/usr:/usr/share/texmf-local/web2c:/usr/share/texmf-dist/web2c:/usr/share/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c://texmf-local/web2c:/://share/texmf-local/web2c://share/texmf-dist/web2c://share/texmf/web2c://texmf-local/web2c://texmf-dist/web2c://texmf/web2c.
kpathsea: Running mktexfmt lualatex.fmt
warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/bin:/usr/bin/share/texmf-local/web2c:/usr/bin/share/texmf-dist/web2c:/usr/bin/share/texmf/web2c:/usr/bin/texmf-local/web2c:/usr/bin/texmf-dist/web2c:/usr/bin/texmf/web2c:/usr:/usr/share/texmf-local/web2c:/usr/share/texmf-dist/web2c:/usr/share/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c://texmf-local/web2c:/://share/texmf-local/web2c://share/texmf-dist/web2c://share/texmf/web2c://texmf-local/web2c://texmf-dist/web2c://texmf/web2c.
/usr/local/texlive/2023/bin/x86_64-linux/mktexfmt: kpsewhich -var-value=TEXMFROOT failed, aborting early. BEGIN failed--compilation aborted at /usr/local/texlive/2023/bin/x86_64-linux/mktexfmt line 25.
Process exited with error(s)

Process started: makeindex "basic sample".idx

Input index file basic sample.idx not found. Usage: makeindex [-ilqrcgLT] [-s sty] [-o ind] [-t log] [-p num] [idx0 idx1 ...]
Process exited with error(s)

Process started: lualatex -synctex=1 -interaction=nonstopmode "basic sample".tex

warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/bin:/usr/bin/share/texmf-local/web2c:/usr/bin/share/texmf-dist/web2c:/usr/bin/share/texmf/web2c:/usr/bin/texmf-local/web2c:/usr/bin/texmf-dist/web2c:/usr/bin/texmf/web2c:/usr:/usr/share/texmf-local/web2c:/usr/share/texmf-dist/web2c:/usr/share/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c://texmf-local/web2c:/://share/texmf-local/web2c://share/texmf-dist/web2c://share/texmf/web2c://texmf-local/web2c://texmf-dist/web2c://texmf/web2c.
kpathsea: Running mktexfmt lualatex.fmt
warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/bin:/usr/bin/share/texmf-local/web2c:/usr/bin/share/texmf-dist/web2c:/usr/bin/share/texmf/web2c:/usr/bin/texmf-local/web2c:/usr/bin/texmf-dist/web2c:/usr/bin/texmf/web2c:/usr:/usr/share/texmf-local/web2c:/usr/share/texmf-dist/web2c:/usr/share/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c://texmf-local/web2c:/://share/texmf-local/web2c://share/texmf-dist/web2c://share/texmf/web2c://texmf-local/web2c://texmf-dist/web2c://texmf/web2c. /usr/local/texlive/2023/bin/x86_64-linux/mktexfmt: kpsewhich -var-value=TEXMFROOT failed, aborting early. BEGIN failed--compilation aborted at /usr/local/texlive/2023/bin/x86_64-linux/mktexfmt line 25.
Process exited with error(s)
```

Is this something anyone can help me with please?

**Comment by u-fischer** [comment]
> I know this might be a separate issue but this is what happened:

It is a separate issue and doesn't belong here. Ask on the texlive mailing list https://tug.org/mailman/listinfo/tex-live or on some general support site like tex.stackexchange for help.
