### ISSUE TITLE
Interaction between babel and ltxtable

### ISSUE THREAD

**Issue by SverreStausland** [latex3/babel#284]
Consider this MWE:

```
\documentclass{article}
\usepackage[main = american, norsk]{babel}
\usepackage{array, ltxtable}

\begin{document}

\begin{filecontents}[overwrite]{testing.tex}
\begin{longtable}{p{3em}X}
9999 & {\begin{otherlanguage}{norsk}Foo bar baz\end{otherlanguage}}\\
9999 & Foo bar baz\\
\end{longtable}
\end{filecontents}
\LTXtable{\linewidth}{testing.tex}

\end{document}
```
With `babel` v. 3.92 (compiled in Overleaf, pdflatex 2023), it produces this output:

![babel01](https://github.com/latex3/babel/assets/4471032/c1a0c672-bb21-4eb1-a2d4-11d0d3e7f81a)

With `babel` v. 24.1 (compiled in texlive with pdflatex), it produces this output:

![babel02](https://github.com/latex3/babel/assets/4471032/bf3653bf-f54d-4e3e-a6eb-5822707ef4b5)

The version numbers of `array`, `tabularx`, `longtable` , and `ltxtable` are the same for both compilations, and both are compiled with the same version of `pdflatex`, so the observed difference is due to changes in the `babel` package.

I don't know if this is to be considered a bug or not, but the current outcome is surely not the desired one in my case. Can this be fixed, or is some other solution to be preferred?

**Comment by davidcarlisle** [comment]
As I explained on tex.sx chat this is unrelated to the table packages,

```
\documentclass{article}
\usepackage[main = american, norsk]{babel}


\begin{document}


xxx \parbox[t]{5cm}{%
  \begin{otherlanguage}{norsk}Foo bar baz\end{otherlanguage}}

\bigskip


xxx \parbox[t]{5cm}{%
  \leavevmode\begin{otherlanguage}{norsk}Foo bar baz\end{otherlanguage}}

\end{document}
```

produces

![image](https://github.com/latex3/babel/assets/1268738/72ee58ed-b033-4f28-acff-203539929928)


due to a  `\write` whatsit at the start of the language swich.

**Comment by jbezos** [comment]
It seems there is a change in behavior in the LaTeX kernel, which now enters in vertical mode (formerly it didn’t; or exists horizontal mode, I’m not yet sure). The following test file prints ‘Vertical’ in current LaTeX, while Overleaf prints ‘Horizontal’:
```\documentclass{article}

\usepackage{array, ltxtable}

\begin{document}

\begin{filecontents}[overwrite]{testing.tex}
\begin{longtable}{p{3em}X}
9999 & {\ifhmode Horizontal\else Vertical\fi}\\
9999 & {\ifhmode Horizontal\else Vertical\fi}\\
\end{longtable}
\end{filecontents}
\LTXtable{\linewidth}{testing.tex}

\end{document}
```

**Comment by jbezos** [comment]
@SverreStausland Just read David’s message, which gave me the workaround: use `\leavevmode`.

**Comment by davidcarlisle** [comment]
longtable now follows array

`% \changes{v4.18}{2023/08/25}{Use \cs{everypar} to match array package, github 1128}% `

so the strut is delayed in everypar (so if the p-entry starts wih a list you don't have a paragraph with just an invisible strut before the list

so while you see a change in behaviour for longtable it would always have been this way in a tabular using the array package, or as shown above in a standard parbox

**Comment by davidcarlisle** [comment]
@jbezos  you could try to delay the write with `\ifvmode\everypar{...}\else...}` but it's a tricky area to ensure everypar survives at starts of sections and places.

In color.sty I just documented that `\color` may do this (footnote page 7 of grfguide) and made `\textcolor` always have `\leavevmode` so it does not have the issue, but always starts a paragraph so can not surround lists etc

**Comment by jbezos** [comment]
@davidcarlisle So `longtable` did change (@SverreStausland said the version was the same).

**Comment by jbezos** [comment]
As `otherlanguage` can be used in many contexts, I can’t change it hastly. I have to investigate.

**Comment by davidcarlisle** [comment]
> @davidcarlisle So `longtable` did change (@SverreStausland said the version was the same).

https://chat.stackexchange.com/transcript/message/32722915#32722915  :-)

**Comment by SverreStausland** [comment]
@jbezos I looked through my two log files twice to make sure that the package versions were the same, and now that I'm doing the same one more time, I notice that the versions for `longtable` are indeed different ... Sorry! 😖

**Comment by SverreStausland** [comment]
@davidcarlisle @jbezos Can someone explain how exactly one should "use `\leavemode" as a workaround?

**Comment by davidcarlisle** [comment]
@SverreStausland  as I showed just make sure you don't start a vbox with `\begin{otherlanguage}` so use `\leavevmode\begin{otherlanguage}` or `\mbox{}\begin{otherlanguage}`  in such a context.

**Comment by SverreStausland** [comment]
If I understood it correctly, @jbezos will investigate and see if there's a solution that doesn't require the user to insert `\leavemode` before `\begin{otherlanguage}` whenever it's used in a table. Did I understand that correctly?

**Comment by jbezos** [comment]
I’ll investigate, but this doesn’t mean there will be a general solution. An option is to document `\leavevmode` will be necessary in some cases. Interestingly, the `babel` manual explains neither `\foreignlanguage` nor `otherlanguage*` enter in horizontal mode, but I missed a similar remark in `otherlanguage`. Very likely, and for compatibility reasons. the current behavior will stay (as `\foreignlanguage` stayed), but, well, I'd like to investigate.

**Comment by jbezos** [comment]
Finally the current behavior will stay for a couple of reasons: (1) backwards compatibility; (2) `otherlanguage` is the environment version of `\selectlanguage` and entering in horizontal mode doesn’t make much sense. I even considered and option to change the behavior, but I discarded it for reason 2. If a `\leavevmode` is always required in `otherlanguage`, there is the possibility to add it with:
```tex
\AddToHook{env/otherlanguage/before}{\leavevmode}
```
So, I’ll just document neither `\selectlanguage` nor `otherlanguage` change the current mode.
