### ISSUE TITLE
Rollback option for .ldf files

### ISSUE THREAD

**Issue by Udi-Fogiel** [latex3/babel#293]
I would like to change the behavior of the `hebrew` interface, and after 20+ years being untouched it is virtually impossible to do so without having some breaking changes. It would be nice to be able to rollback so I could safety edit the definition file without any worries.

**Comment by Udi-Fogiel** [comment]
@jbezos in the specific context of Hebrew, Im also OK (and maybe it is even better) with add a new value to the `bidi` option (say `rlbabel`), so that I could stop using it, but still let people load it if they want to. 

Now that I think about it, I could  also simply test if `rlbabel` was `\input`ed before, loading the language, and ask people that want to use to input that themselves, not sure what is the best option here.

**Comment by Udi-Fogiel** [comment]
> Now that I think about it, I could also simply test if `rlbabel` was `\input`ed before loading the language, and ask people that want to use to input that themselves, not sure what is the best option here.

I think I'll just do that, so I'll close for now.. Sorry for the noise.

**Comment by jbezos** [comment]
@Udi-Fogiel What a short-lived issue. But now you raised this question — Hebrew is the only language (besides `polutonikogreek`) with an additional setting in the babel core (to load another file, `rlbabel`). I would like to get rid of it, so we can seize the opportunity, so that it’s entirely under the control of the Hebrew `ldf`.

**Comment by Udi-Fogiel** [comment]
@jbezos that would be great! Let me ship the next release to ctan first, so that no errors from missing file will happen?

**Comment by jbezos** [comment]
👍 Perfect. Once released a new `hebrew` I’ll modify `babel`.
