### ISSUE TITLE
Spurious space in welsh.ldf

### ISSUE THREAD

**Issue by cfr42** [latex3/babel#295]
There's a typo in the translation of `\ccname`. The current translation is `copï au` but neither `copï` nor `au` is a word. `copïau` must be intended here. It means 'copies'. 

Note that nobody who knows Welsh could fail to notice this is wrong. It isn't just that these don't happen to be words. They are both _prima facie_ implausible. You wouldn't get `ï` as the last character here, but only in the middle, as there's no need for it at the end. E.g. `copi` is the singular; `copïau` is the plural.

I was involved in getting this file revised a few years ago and it is _much_ better than it used to be - so good, I no longer have a corrected copy in TEXMFHOME. Thank-you! But it would be great if this could be corrected, too.

Overkill for a space, but in case Welsh is too much trouble without it:

[welsh.patch.txt](https://github.com/latex3/babel/files/15137022/welsh.patch.txt)

**Comment by jbezos** [comment]
I’ve just submitted a fix to CTAN.

**Comment by cfr42** [comment]
Wow! That was quick - thank you. 

[I'm not sure I should post this. Apologies if not.]

**Comment by jbezos** [comment]
Feedback is welcome, particularly when it’s positive 🙂.
