### ISSUE TITLE
\babelfont fails with some fonts as of recent update

### ISSUE THREAD

**Issue by d125q** [latex3/babel#296]
(I don’t have a lot of time to troubleshoot, but leaving this here just in case.  I began observing this behavior after a recent update.)

`\babelfont{sf}{URW Classico}` fails with
```
Illegal parameter number in definition of \l__exp_internal_tl.
<to be read again> 
1
l.76 \babelfont{sf}{URW Classico}
```
yet `\babelfont{rm}{TeX Gyre Pagella}` and `\babelfont{tt}{IBM Plex Mono}` work without any problems.  Using the original `fontspec` commands (e.g., `\setsansfont`) also works just fine.

I am compiling with
```
% lualatex --version
This is LuaHBTeX, Version 1.18.1 (TeX Live 2025/dev)
Development id: 7616

Execute  'luahbtex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2022 Taco Hoekwater and the LuaTeX Team.
```
and
```tex
\ProvidesPackage{babel}[2024/04/20 v24.4 The Babel package]
```

**Comment by u-fischer** [comment]
That is a fontspec issue and will hopefully be resolved in 1-2 days. See https://github.com/latex3/fontspec/issues/513

**Comment by d125q** [comment]
Thanks @u-fischer! I thought something was off with `babel` as I could use the `fontspec` commands.  Closing this issue.
