### ISSUE TITLE
Change first item in  abjad alph counter for  Algeria, Morocco and Tunisia. 

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#297]
In  North African countries we usually use  letter ` أ ` rather then `ا` as first element in arabic alph counter, please kindly take this into consideration.    

```latex
\documentclass{article}
\usepackage[bidi=basic]{babel}
\babelprovide[import,main,alph=abjad]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\localenumeral{abjad}{1} % this should be أ not ا 

\end{document}
```

**Comment by jbezos** [comment]
@seloumi The locales ar-MA, ar-DZ and ar-TN define two counters:
```ini
abjad = ا ب ج د ه‍ و ز ح ط ي ك ل م ن س ع ف ص ق ر ش ت ث خ ذ ض ظ غ
maghrebi.abjad = ا ب ج د ه‍ و ز ح ط ي ك ل م ن ص ع ف ض ق ر س ت ث خ ذ ظ غ ش
```
Do I have to change it in both?

**Comment by seloumi** [comment]
Yes, the first alph letter  `ا` is   used only in eastern countries: Egypt, Jordan, Iraq, ....
