### ISSUE TITLE
Incompatibility with igo gameborard typesetting package

### ISSUE THREAD

**Issue by jaypeeds** [latex3/babel#299]
I started to use the IGO package to document the Go board game, in combination with babel, that was back in 2004. I only have a PDF showing this.
Today, 20 years later, I had to create some new document using the same environment.
It appears that without the use of babel package the gameboards are typeset properly, but when some localisation is required, an error arises :
Incomplete \ifhmode 
... and no explicit reference to this can be found in the .tex being composed.

Environment : macOS Sonoma, MacMini 32Go RAM
 IGO : https://ctan.org/pkg/igo it includes a documentation igo.tex in English that composes well without babel, but fails with the above mentioned error when babel is added.

**Comment by u-fischer** [comment]
The igo package is incompatible with LaTeX. See https://tex.stackexchange.com/a/652011/2388

**Comment by jaypeeds** [comment]
Thanks a lot,
I confirm that the incompatibility is caused by IGO code, not babel.
Please close this issue.
