### ISSUE TITLE
LuaLaTeX + babel + hyperref:  extraneous =

### ISSUE THREAD

**Issue by GMS103** [latex3/babel#302]
The following
```
\documentclass[french]{article}

\usepackage{babel}

\usepackage{hyperref}

\begin{document}

\section{A section{\NoAutoSpacing:} Blah}

Blah blah.

\end{document}
```
when compiled with LuaLaTeX gives
<img width="998" alt="Screenshot 2024-06-13 at 23 18 03" src="https://github.com/latex3/babel/assets/47718744/43b1f93d-b7d8-4162-9be6-f62e1e9be9cb">

(With XeLaTeX it works as expected.)

**Comment by u-fischer** [comment]
That is something babel-french would have to correct. They could e.g. do something like this

~~~~
\documentclass[french]{article}


\usepackage{babel}
\providecommand\texorpdfstring[2]{#1}
\makeatletter
\DeclareRobustCommand*{\NoAutoSpacing}{%
  \texorpdfstring{\FB@spacing@off
  \ifFB@active@punct\shorthandoff{;:!?}\fi}{}%
}
\makeatother
\usepackage{hyperref}

\begin{document}

\section{A section{\NoAutoSpacing:} Blah}

Blah blah.

\end{document}
~~~~

**Comment by GMS103** [comment]
Thanks, Ulrike, I have sent a message to Daniel Flipo.

**Comment by dflipo** [comment]
Thanks, I will include your patch asap, not before end of June as I am currently on holidays far away from home :-)

**Comment by GMS103** [comment]
Merci beaucoup !
