### ISSUE TITLE
Fix Finnish typo

### ISSUE THREAD

**Issue by mjnykanen** [latex3/babel#304]
The file "finnish.lbx" has a typo: "kirjottanut" should be "kirjoittanut". (*)

This typo has these two occurrences:

line
160:                      {toimittanut ja kommentaarin kirjottanut}},
308:  withintroduction = {{johdannon kirjottanut}{johdannon kirjottanut}},

How should this very minor thing be fixed? I have never ever patched anything 
LaTeX-related myself...

(*) To be precise, dropping the second "i" would be ok in colloquial Finnish, but not in the kind of academic writing which needs a bibliography. This is probably why this particular typo has not been detected earlier.

**Comment by mjnykanen** [comment]
Ok, all it took was to edit the file and run "texhash".

How can I propose the change to the next official TeXLive distro?

**Comment by jbezos** [comment]
`finnish.lbx` doesn’ belong to the `babel` bundle, but to `biblatex`: https://github.com/plk/biblatex/issues.
