### ISSUE TITLE
Languages switches create whitespaces when using \babelfont and LuaLaTeX

### ISSUE THREAD

**Issue by LupinoTech** [latex3/babel#31]
The following code is producing unwanted whitespace in the texlive2019-version of the babel package when compiled using lualatex:

```
\documentclass[english]{book}

\usepackage{babel}
\babelprovide{da}

\babelfont{rm}[BoldFont=SourceSerifPro-Bold.otf,%
FontFace={sb}{n}{SourceSerifPro-Semibold.otf},%
]{SourceSerifPro-Regular.otf}

\begin{document}

\begin{thebibliography}{0}
\bibitem{bib-41}Marshall\foreignlanguage{da}{, Thomas Humphrey. }Citizenship and Social Class and Other Essays. Cambridge: Cambridge University Press, 1950.
\end{thebibliography}
\end{document}
```
((proposed fix was wrongfully releated to an old version of the file. deleted.))

**Comment by u-fischer** [comment]
As has been discussed in the chat this is probably due to outdated package versions. The problem can't be reproduced in a current system.
