### ISSUE TITLE
Better handling of class options

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#312]
The issue is primarily related to the LaTeX kernel and how class options are (were) processed. However, `babel` requires some readjustments (presumably to use the new `\@raw@classoptionslist`).

See [How does package babel find and process the language list without it being explicit?](https://topanswers.xyz/tex?q=8039).

**Comment by davidcarlisle** [comment]
It should be possible to locally substitute  `\@classoptionslist` by `\@raw@classoptionslist` to avoid things breaking in the edef, but a more radical but long term better change might be to switch from `\ProcessOptions` to `\ProcessKeyOptions` this uses `\@raw@classoptionslist` internally but gives more direct control over key-value otions and avoids the option clash error if babel is loaded twice.

**Comment by jbezos** [comment]
@davidcarlisle Sure, but because of the way `babel` handles the class and package options I haven’t managed to do it, yet (lots of things must be rewritten). But I'm on it.

**Comment by davidcarlisle** [comment]
the simplest fix would be to locally (or if brave, globally) define `\@classoptionlist`  to still be processed with edef and space removal (for compatibility) but without dropping braces.   here the `\@classoptionlist` is `foo=english,french` so babel sees `french` but with the redefinition it is `foo={english,french}` and the inner options stay braced.

```
\documentclass[foo= {english,french}]{article}

\makeatletter
\let\saved@clslist\@classoptionslist
\let\zap@\doublehyphendemerits
\let\zap@end\finalhyphendemerits

\def\zap@spaceb#1 {%
  \expandafter\ifx\expandafter\zap@end\@gobble#1\else
  \@gobble#1%
  \expandafter\zap@spaceb\expandafter\zap@\fi
  }

 
\expanded{\noexpand\protected@edef\noexpand\@classoptionslist{%
    \noexpand\expandafter\noexpand\zap@spaceb\noexpand\expandafter\zap@\@raw@classoptionslist\space\zap@end\space}}


\usepackage{babel}

\let\@classoptionslist\saved@clslist
\makeatother

\begin{document}

\end{document}
```

**Comment by jbezos** [comment]
It seems the issue is a little more far reaching:
```tex
\documentclass[hi, x = {a,b,c}, bye]{article}
\begin{document}
Hi
\end{document}
```
shows:
```
LaTeX Warning: Unused global option(s):
    [hi,x,b,c,bye].
```
