### ISSUE TITLE
Faulty Rendering of accented Hebrew with combining characters in newer TeXLive (2022 and later)

### ISSUE THREAD

**Issue by LupinoTech** [latex3/babel#313]
The following MEW yields different output with TeXlive (2021 or earlier) versus newer TeXlive (2022 and later, including a freshly updated one):
``` latex
\documentclass[UKenglish]{article}

\usepackage[bidi=basic]{babel}
\babelfont[hebrew]{rm}{SBL_Hbrw.ttf}
\parindent0pt

\begin{document}
Letters without Sheva: \foreignlanguage{hebrew}{בּשׂ}\\
Letters with Sheva: \foreignlanguage{hebrew}{בְּשְׂ}\\
Moar Context: \foreignlanguage{hebrew}{בְּנוֹת יִשְׂרָאֵל}
\end{document}
```
The used font file `SBL_Hbrw.ttf` can be found [here](https://www.sbl-site.org/educational/biblicalfonts_sblhebrew.aspx).

Older TeXLive renders the code as
![hebrew_2021](https://github.com/user-attachments/assets/d1d4ba2c-96bd-49eb-9554-199747f40ef7)
while newer TeXLive renders
![hebrew_newest](https://github.com/user-attachments/assets/273e44f4-d184-423e-b16f-37c3073b64ba)
Note the positions of the "dots" above `ש` and inside `ב`.

If it helps, here are the log files for both tex runs:
[tl2021.log](https://github.com/user-attachments/files/17276945/tl2021.log)
[newest.log](https://github.com/user-attachments/files/17276944/newest.log)

**Comment by LupinoTech** [comment]
Short update: If I use [Noto Serif Hebrew Regular](https://fonts.google.com/noto/specimen/Noto+Serif+Hebrew) instead of SBL Hebrew, the rendering is correct even in newer TeXLive, but it would be great to get it correctly with SBL-Hebrew, as well.

**Comment by jbezos** [comment]
I’m not sure where the problem is (`babel` or `luaotfload`), but with the Harfbuzz renderer it seems to work:
```tex
\babelfont[hebrew]{rm}[Renderer=Harfbuzz]{SBL_Hbrw.ttf}
```

**Comment by jbezos** [comment]
The issue can be reproduced without `babel` (the same behavior – fails now, worked in 2021), so the problem is the default renderer in `luaotfload`. 
```
\documentclass{article}

\parindent0pt
\usepackage{fontspec}
\setmainfont[Script=Hebrew]{SBL_Hbrw.ttf}

\begin{document}

{\textdir TRT בְּשְׂ}

\end{document}
```
