### ISSUE TITLE
New Italian language file defines \?

### ISSUE THREAD

**Issue by vigna** [latex3/babel#314]
I just updated my texlive installation and all my Italian files are not compiling anymore because, apparently, the language file for Italian (and only that one) now defines a command `\?`. I'm pretty sure this wasn't happening before because I use `\?` a bit everywhere.

Is there any suggested workaround? Will a `\renewcommand` solve the problem (or screw up something inside Babel)?

**Comment by jbezos** [comment]
Yes, it seems now `italian` defines `\?`. To be honest, I don’t know its purpose, but apparently is it’s related to a feature named ‘intelligent comma’. Please, contact its maintainer, Claudio Beccari.

**Comment by vigna** [comment]
Ok but... How? Do you have an email?

**Comment by eg9** [comment]
@vigna 

I sent mail to Claudio about the issue.

**Comment by vigna** [comment]
Oops, gli ho scritto anch'io.

**Comment by eg9** [comment]
Version v.1.5.01 of `italian.ldf`, released 2024/10/10, has removed `\?`.
