### ISSUE TITLE
Greek: stigma used instead of small stigma

### ISSUE THREAD

**Issue by nplatis** [latex3/babel#316]
In some places I see that stigma is used instead of small stigma:
https://github.com/latex3/babel/blob/ed9532b287c38de8b1582fcf8f525dd23f418b37/locale/el/babel-el-polyton.ini#L199
https://github.com/latex3/babel/blob/ed9532b287c38de8b1582fcf8f525dd23f418b37/locale/el/babel-el.ini#L203
https://github.com/latex3/babel/blob/ed9532b287c38de8b1582fcf8f525dd23f418b37/locale/el/babel-polytonicgreek.tex#L44
https://github.com/latex3/babel/blob/ed9532b287c38de8b1582fcf8f525dd23f418b37/locale/el/babel-greek.tex#L44

(I hope I have not missed any such occurence.)

Is this intended?

**Comment by jbezos** [comment]
Good catch. It's simply a typo that was propagated by copy-pasting.
