### ISSUE TITLE
active : and other shorthands in \label

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/babel#32]
https://tex.stackexchange.com/questions/511030/another-babel-french-incompatibility-with-crossreftools/512104#512104

shows that some uses of active shorthand characters, notably french `:` fail in \label.  I suggest there  adding another test to `\active@prefix` to test `\ifincsname` and use `\string`  in that case.

That would be consistent with the `\ifcsname` test added to the UTF-8 handling to make non ascii characters safe in labels and filenames in the last release, so would fit well here I think.

**Comment by jbezos** [comment]
Yes, indeed. Already done here (commit https://github.com/latex3/babel/commit/1d1c18073b54908fc7d827d337a73676285b82b2 ). I'll upload it to CTAN very likely tomorrow.
