### ISSUE TITLE
option provide

### ISSUE THREAD

**Issue by hvoss49** [latex3/babel#320]
The following example is from the documentation:

```
\documentclass[]{article}
\usepackage[dutch,ngerman,thai,%provide=*
  ]{babel}
\babelfont{rm}{Norasi}
\begin{document}
"o Thai"=language: \prefacename, \alsoname, \today.
\selectlanguage{dutch}
"o Dutch"=language: \prefacename, \alsoname, \today.
\end{document}
```

I do not understand the difference in using `provide=*`  The documentation (page 9) stated that it is needed for activating the `german.ldf`

**Comment by jbezos** [comment]
Perhaps I have to point out more clearly `provide=*` and `provide+=*` in multilingual documents apply to mixed modes, ie, ‘classical’ (ldf) or ‘modern’ (ini) depending on the language.

So:
```tex
\usepackage[dutch,ngerman,thai]{babel}
```
means `dutch`=classsical, `ngerman`=classical, `thai`=classical. It happens there is a `thai.ldf`, but in Unicode engines it’s not really useable (even if captions and date are printed).

```tex
\usepackage[dutch,ngerman,thai,provide=*]{babel}
```
means `dutch`=classsical, `ngerman`=classical, `thai`=modern. The result is (I’ve added `ngerman`):
![image](https://github.com/user-attachments/assets/d77ef597-b45b-4ed8-9567-7d0a1767084b)


```tex
\usepackage[dutch,german,thai,provide*=*]{babel}
```
means `dutch`=modern, `german`=modern, `thai`=modern. Note with the modern way, the name is `german`, not `ngerman`.

The option `\usepackage[dutch,german,thai,provide+=*]{babel}` doesn’t make much sense here.

**Comment by hvoss49** [comment]
Understood ...
