### ISSUE TITLE
Inconsequent handling of shorthands in table of contents

### ISSUE THREAD

**Issue by wehro** [latex3/babel#34]
If a shorthand is switched off, this has no consequences for the table of contents. This may lead to inconsistent results for section headings.
In the following example, the heading of the second section is **"O** in the document, but **Ö** in the table of contents.
```
\documentclass{article}
\usepackage[german]{babel}

\begin{document}
\tableofcontents
\section{"A}
\shorthandoff{"}
\section{"O}
\end{document}
```

**Comment by jbezos** [comment]
The same applies to any protected macro or redefinable element. To synchronise the TOC with these redefinitions, just use `\addtocontents`.
