### ISSUE TITLE
Documentation errors: East Asia scripts

### ISSUE THREAD

**Issue by aminophen** [latex3/babel#36]
> \item[East Asia scripts] Settings for either Simplified of Tradicional

Typo: Tradicional -> Traditional

> this is what the |ldf| does in |japanese| with \luatex, because the
> following piece of code loads \textsf{luatexja}:

Wrong; japanese.ldf does not load luatexja.sty, and japanese.ldf does nothing about Japanese text setup. (all that does is to translate "section" -> "節", etc.) ltjbook.cls is part of luatexja package, and it loads luatexja.sty.

**Comment by jbezos** [comment]
Bad explanation, indeed. I'll fix it in the next version.
