### ISSUE TITLE
In spanish babel, shorthands=off breaks non-break space

### ISSUE THREAD

**Issue by Rmano** [latex3/babel#38]
Consider the following code: 
```latex
\documentclass[12pt,]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english, spanish, shorthands=off]{babel}

\begin{document}
\today
\end{document}
```

produces: 

![2019-11-27_17-52](https://user-images.githubusercontent.com/6414907/69745779-2f2a3e00-1143-11ea-8e7c-99508df22452.png)

As you can see, the two `~` in `27~de noviembre~2019` are not working anymore. 

I have TeXLive 2017 on Ubuntu 2019, but I confirmed that the problem is still present: https://chat.stackexchange.com/transcript/message/52716006#52716006

**Comment by jbezos** [comment]
It's bug, indeed. As a workaround, use:
```
\usepackage[english, spanish, es-noshorthands, shorthands=off]{babel}
````

**Comment by jbezos** [comment]
This issue belongs to babel-spanish.

**Comment by Rmano** [comment]
Thanks! Can you tell me where can I report the bug?

**Comment by jbezos** [comment]
I myself opened the issue here: https://github.com/jbezos/babel-spanish/issues/6 . So, no additional action is required from your part.

**Comment by Rmano** [comment]
Thanks!
