### ISSUE TITLE
Arabic text within main LTR paragraph issue 

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#41]
Short Arabic text within LTR text produce correct text direction but Arabic characters are not connected.

```latex
\documentclass{article}
\usepackage[bidi=basic-r,nil]{babel}
\babelprovide[import, main]{arabic}
\babelfont{rm}{Amiri}
\begin{document}

Text from left to right  نص من اليمين لليسار  text from left to right.

\bigskip 

{\selectlanguage{nil}
Text from left to right  نص من اليمين لليسار  text from left to right. 
}

\end{document}
 ```

![image](https://user-images.githubusercontent.com/8249073/71304630-cfcdef80-23c9-11ea-8364-c1e70b3bdc93.png)

**Comment by jbezos** [comment]
This is the expected and documented behaviour (see sec. 1.20). Use `bidi=basic` for both R and L texts.
