### ISSUE TITLE
newish bidi code in babel conflict with pdflscape & rotating packages

### ISSUE THREAD

**Issue by vinoruto** [latex3/babel#42]
For the shown MWE, there are 2 issues for the same example as shown in 

https://tex.stackexchange.com/questions/520471/table-does-not-appear-in-landscape-environment

https://tex.stackexchange.com/questions/521796/contents-of-sidewaystable-do-not-appear/521799?noredirect=1#comment1319557_521799

Tables do not apear in "Landscape" environment neither in "sidewaystable" environment, I do not know whether the issue is in the babel package or in the rotating or pdf landscape package, there seems to be some kind of incompatibility. While in portrait view the table apears normally without any issues.

```javascript
\documentclass[a4paper,12pt,twoside]{book}
\usepackage[a4paper,top=2.5cm,bottom=2.5cm,margin=2.5cm,bindingoffset=0.5cm]{geometry} 
\usepackage{pdflscape}
\usepackage[hidelinks,colorlinks=true,breaklinks,allcolors=blue]{hyperref} 

\usepackage[bidi=basic,layout=lists.tabular]{babel}
\babelprovide[import=ar,mapdigits,main]{arabic}
\babelprovide[import=en,language=Default]{english}

\babelfont{rm}{Latin Modern Roman}
\babelfont[arabic]{rm}{amiri}
\babelfont[english]{rm}{Times New Roman}

\usepackage[table]{xcolor} 
\usepackage{tabu,multirow} 
\usepackage{array} 
\newcolumntype{?}[1]{!{\vrule width #1}} 
\usepackage{booktabs}
\setlength{\belowrulesep}{0pt}
\setlength{\belowbottomsep}{0pt}
\setlength{\aboverulesep}{0pt}
\setlength{\belowrulesep}{0pt}
\setlength{\abovetopsep}{0pt}
\usepackage{makecell} 
\usepackage{boldline} 


\title{jhhjjhhj}
\author{}
\date{}

\begin{document}

\chapter{شكر وتقدير} 

\begin{landscape}
\begin{table}[htbp]
\setlength\arrayrulewidth{1pt} 
\begin{center}
\caption{أمثلة لبعض الكلمات المتشابهة باللغات الناقلة}
\rowcolors{2}{white}{gray!25}
\begin{tabular}{?{1mm}c|c|c|>{\centering\arraybackslash}m{5cm}?{1mm}c|} 
\rowcolor{white}
\toprule[1mm] 
\multicolumn{3}{?{1mm}c|}{\textbf{اللغة}} & \multirow{2}{*}{} \\ \cmidrule[1.25pt]{1-3} 
\rowcolor{white} 
العربية &
العبرانية &
وجه التشابة &
\multirow{-2}{*}{\textbf{ملاحظات}} 
\\
\midrule[1.5pt]
مَلِك & ميلْخِ & الحروف والمعنى & -\\
\hline
مُلُوكْ & مَلاخيمْ  & الحروف والمعنى & -\\
\hline
نَفْسي & نَفْشِيْ   & الحروف والمعنى & -\\
\hline
سَبْعَة & شِبْعَاهْ & الحروف والمعنى & -\\
\hline
يَقُومُ & ياقُومْ   & الحروف والمعنى & -\\
\hline
يَرحَضُ & يِرْحَاصْ & الحروف والمعنى & -\\
\hline
ثَلاَثَةُ   & شَلوشَاهْ & الحروف والمعنى & -\\
\hline
مَلَك   & ماَلاَخْ  & الحروف والمعنى & -\\
\hline
يَدُهُ  & ياَدو & الحروف والمعنى & -\\
\hline
إِيْايَ & أوتِيْ    & المعنى & -\\
\hline
إِيَّاكَ    & أوتْخَ    & المعنى & -\\
\hline
أثنْاَنِ    & شَنَايِمْ & المعنى & -\\
\hline
يحرق    & يسْروفْ   & الوزن & على وزن "يَفْعُلُ" مع فرق بسيط\\
\hline
يغسل    & يَخَبْيسْ & الوزن & على وزن "يُفَعِلُ" مع فرق بسيط\\
\hline
تَكَلَّمْتُ & دَبَّرْتِيْ   & الوزن & على وزن "فَعْلْتُ" مع فرق بسيط\\
\hline
أنْقَطَعَ   & نِخْرَاتْ & المعنى & النون هي الزائدة في انفعل لفظاً ومعنى\\
\hline
يُصَلِي & يِتْپَلَيلْ   & الوزن & تقريباً على وزن "يَتَفَعْلُ" فهو في الأصل ثلاثي (أي من ثلاثة حروف) مع إضافة حرف المضارعة وحرف التاء بالإضافة لتشديد عين الفعل\\
\bottomrule[1mm] 
\end{tabular}
\label{tab}
\end{center}
\end{table}
\end{landscape}
\end{document}
```
![table - Landscape_Page_1](https://user-images.githubusercontent.com/45985381/71452035-e4730480-2788-11ea-8224-5cc9c3f0c5a3.jpg)
![table - Landscape_Page_2](https://user-images.githubusercontent.com/45985381/71452037-e50b9b00-2788-11ea-828c-7685ca7ae6cd.jpg)
![table - portrait](https://user-images.githubusercontent.com/45985381/71452040-feace280-2788-11ea-8ad3-3b24a804514f.jpg)

**Comment by davidcarlisle** [comment]
@vinoruto thanks for posting. 

@jbezos  sorry not had time to trace this today I think the issue is in the babel bidi code but it's not impossible it's the graphics rotation that's just not sufficiently right-to-left aware so we can change things there if needed.

**Comment by u-fischer** [comment]
@davidcarlisle  I would say that at the core of the problem is that under direction changes rotatebox doesn't correctly set the bounding box:

```
\documentclass[]{book}
\usepackage{graphicx}
\begin{document}
\textdir TRT \pardir TRT
\rule{3pt}{3pt}\fbox{\rotatebox{90}{xxxxxxxxxxx}}

\textdir TLT \pardir TLT

\rule{3pt}{3pt}\fbox{\rotatebox{90}{abc}}

\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/71472390-26c13380-27d3-11ea-90fb-65e7cf7cba3f.png)

**Comment by davidcarlisle** [comment]
@u-fischer  ooh so it's a graphics package issue, we can blame you not Javier then:-) We should also check what the l3 rotation code does here....

**Comment by u-fischer** [comment]
@davidcarlisle  the l3 code work in vmode but fails in hmode too:

~~~~
\documentclass[]{book}
\begin{document}
\ExplSyntaxOn
\textdir TRT \pardir TRT
\par
\hbox_set:Nn \l_tmpa_box{yyyy}
\box_rotate:Nn\l_tmpa_box{90}
\fbox{\box_use:N\l_tmpa_box}

\par
\leavevmode
\hbox_set:Nn \l_tmpb_box{yyyy}
\box_rotate:Nn\l_tmpb_box{90}
\fbox{\box_use:N\l_tmpb_box}
\ExplSyntaxOff

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/71473424-3b9fc600-27d7-11ea-8027-fc39ec1b2233.png)
