### ISSUE TITLE
Language 'nswissgerman' and isodate

### ISSUE THREAD

**Issue by FloMiLe** [latex3/babel#46]
I wish to use 'nswissgerman' as language and the package `isodate` to modify `\today`.

    \documentclass{article}
    \usepackage[nswissgerman]{babel}
    \RequirePackage[ngerman]{isodate}
    		\shortdate
    		\daymonthsepgerman{}\monthyearsepgerman{}{}
    \begin{document}
    Datum: \today
    \end{document}

However, `isodate` only has an effect in the MWE above, when `babel`'s language is set to 'ngerman' as well.

**Comment by jbezos** [comment]
It seems `isodate` does not recognize `nswissgerman`. As a workaround you may say:

     \documentclass{article}

     \usepackage[ngerman,nswissgerman]{babel}

     \RequirePackage[ngerman]{isodate}
       \shortdate
       \daymonthsepgerman{/}\monthyearsepgerman{/}{/}

     \makeatletter
     \addto\datenswissgerman{%
       \renewcommand\today{%
         \foreignlanguage{ngerman}{\iso@printdate@ngerman{\year}{\month}{\day}}}}
     \makeatother

     \begin{document}

     Datum: \today

     \end{document}

But ultimately the solution is to add an option for `nswissgerman` in `isodate`, so you should contact its author (although I'm not sure he's currently reachable).
