### ISSUE TITLE
detection of \latinencoding is faulty

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#47]
babel tests for the loading of t1enc.def to decide if \latinencoding should be set to T1. This fails with the new format at \usepackage[T1]{fontenc} doesn't load t1enc.def anymore:

~~~~
\documentclass{article}
\usepackage[T1,T2A]{fontenc}
\usepackage[french,russian]{babel}

\begin{document}
\makeatletter
\show\latinencoding 
\show\f@encoding

\selectlanguage{french}
\makeatletter\show\f@encoding

\end{document}
~~~~

I'm not quite sure what is the best here - perhaps fontenc should set \latinencoding instead?

A second problem is that babel sets \latinencoding to TU only if fontspec is loaded. Imho it would be more sensible to simply test if `\UTFencname` is defined.

**Comment by FrankMittelbach** [comment]
Given that with both encodings in the kernel there is not even the need to use `fontenc` to witch to a Latin encoding. I can use that any time just by doing `\fontencoding{T1}\selectfont`. 

But I'm not sure I see the problem you see: I get
```
> \latinencoding=macro:
->T1.
l.7 \show\latinencoding
                       
? 
> \f@encoding=macro:
->T2A.
l.8 \show\f@encoding
                    
? 
> \f@encoding=macro:
->T1.
l.11 \makeatletter\show\f@encoding
```
which looks good to me (and sensible). And if I remove T1 from the fontenc call I get OT1 as \latinencoding

**Comment by u-fischer** [comment]
@FrankMittelbach  really? I get (with pdflatex)

~~~
> \latinencoding=macro:
->OT1.
l.9 \show\latinencoding
~~~

And the OP here too:
https://tex.stackexchange.com/questions/527278/output-encoding-change-with-new-latex-2020-02-02

**Comment by FrankMittelbach** [comment]
Really:
```
LaTeX2e <2020-02-02>
L3 programming layer <2020-02-03>
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/size10.clo)) (./fontenc.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/t1enc.def)
(/usr/local/texlive/2019/texmf-dist/tex/latex/cyrillic/t2aenc.def
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/t2aenc.dfu))
(/usr/local/texlive/2019/texmf-dist/tex/latex/cyrillic/t2acmr.fd))
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel/babel.sty
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel/switch.def)
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel-french/french.ldf
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel/babel.def
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel/txtbabel.def)))
(/usr/local/texlive/2019/texmf-dist/tex/generic/babel-russian/russianb.ldf))
(/usr/local/texlive/2019/texmf-dist/tex/latex/carlisle/scalefnt.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)
(./Untitled.aux)
> \latinencoding=macro:
->T1.
l.9 \show\latinencoding
                       
? 
> \f@encoding=macro:
->T2A.
l.10 \show\f@encoding
                     
? 
> \f@encoding=macro:
->T1.
l.13 \makeatletter\show\f@encoding
                                  
? 
(./Untitled.aux)

 *File List*
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
 fontenc.sty
   t1enc.def    2020/01/25 v2.0m Standard LaTeX file
  t2aenc.def    2005/09/27 v1.0i Cyrillic encoding definition file
  t2aenc.dfu    2019/11/14 v1.2k UTF-8 support for inputenc
  t2acmr.fd    2001/08/11 v1.0a Computer Modern Cyrillic font definitions
   babel.sty    2020/02/03 3.39 The Babel package
  french.ldf    2020/01/30 v3.5g French support from the babel system
russianb.ldf
scalefnt.sty    
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
l3backend-pdfmode.def    2020-02-03 L3 backend support: PDF mode
 ***********

 )
No pages of output.
Transcript written on Untitled.log.
```
nothing obviously local or bad in my output

**Comment by u-fischer** [comment]
You are loading a local fontenc: `./fontenc.sty`, and this seems still to load also t1enc.def.

**Comment by FrankMittelbach** [comment]
bloody obvious if you look more carefully ... hmm

**Comment by FrankMittelbach** [comment]
ok to come back to my earlier thought (before I thought it was no longer a problem). Given that \latinencoding is there to be able to switch to a latin encoding in document I see only 2 options 

 - always use T1 (which we know is there, and essentially supported by every font family)
 - invent some heuristic but will never be totally right (using fontenc isn't maybe it was in the past but only barely if it missed LY1 and these days you don't need to give OT1 or T1 unless you want to make it the default.
 - make it OT1 and leave the user a choice to overwrite
 - set it when the encoding changes, eg set it in \T@OT1 \T@T1 \T@LY1

**Comment by u-fischer** [comment]
well option 1 is possible - it will give T1 in some places where now OT1 was used, but probably it won't harm much.

I'm not quite sure that I understand when option 4 will kick in. Does "encoding change" mean everytime it is changed in the document or only if \usepackage[..]{fontenc} is called? The second case would probably do the right thing (but it must be restricted to the three encodings that count as "latin").

**Comment by u-fischer** [comment]
thinking about it, option 1 is perhaps not a so good idea: the encoding could switch mid-document from OT1 to T1 after a language switch and this could disturb authors which normally don't set T1 in their document.

**Comment by FrankMittelbach** [comment]
The sample document you gave could do that too (in the old setup) because you could always have something that explicitly or implicitly said `\fontencoding{OT1}` though perhaps not so likely. 

This is why I thought of using the `\T@...`.  Then the first use of a Latin-based language would set \latinencoding and if the document language is then it becomes that.
But most documents that use Latin-based languages other than English have T1 loaded I would guess and it could be resolved by explicitly setting \latinencoding to OT1 if really needed.

**Comment by jbezos** [comment]
Formerly, encoding preferences were always set with the optional argument of `fontspec`, so that 

    \usepackage[T2A]{fontenc}

could mean ‘I want T2A, but for the rest I prefer to stick to pure ASCII’.

However, there is a problem: the trick in `fontenc` to allow multiple loadings:

    \global\expandafter\let\csname opt@fontenc.sty\endcsname\relax

This means the user preferences are lost forever. So, what `babel` did (and still does) is to apply a simple rule: if the user requested T1, then it's an acceptable Latin encoding, and this explains the test for `t1enc.def`. But T1 is now preloaded (let me say I don't like the idea, which is a bit Eurocentric, but it's a matter of taste), and apparently there is no hint at all about which encodings has been requested by the user.

So, 1 should be discarded because it just ignores the user setting; 3, for the same reasons. Also, 4 may not be triggered at all (by comparing the traced logs with and without T1 you will see they are exactly the same after loading `fontenc`), and 2 has a similar problem.

Except if a missed something, I think the solution is ultimately to cure `fontenc`'s amnesia.

**Comment by jbezos** [comment]
@u-fischer 

> A second problem is that babel sets \latinencoding to TU only if fontspec is loaded. Imho it would be more sensible to simply test if \UTFencname is defined.

Currently, it would be more sensible, indeed. The test for `fontspec` code made sense for old versions of this package.

**Comment by u-fischer** [comment]
@jbezos yes I think the change revealed that an ordered list of requested / loaded encodings is missing. With such a list interested packages could check for latin encodings,  or cyrillic without having to guess by testing if some def has been loaded.

**Comment by davidcarlisle** [comment]
> But T1 is now preloaded (let me say I don't like the idea, which is a bit Eurocentric, but it's a matter of taste), and apparently there is no hint at all about which encodings have been requested by the user.

actually T1 has always been preloaded into the 2e format, what has changed this time is that fontenc doesn't re-load a def file if it has already been loaded. This does mean that currently you don't have much of a clue about what are the preferred latin encoding (since T1 and OT1 are always both known)
It would be possible to look at the fontenc options via \@ifpackagewith or directly at \opt@fontec.sty (perhaps) but a new user level declaration on preferred encodings may be better?

**Comment by u-fischer** [comment]
> a new user level declaration on preferred encodings may be better?

a  user interface  
   `latinencoding=T1, cyrillicencoding=T2A,greekencoding=LGR` would be imho quite sensible and babel could then also issue the suitable fontenc calls. 

But we probably need also to address documents which do `\usepackage[T1,LGR,T2A]{fontenc}`  and where the user more or less assume that this declare these encodings. 

If there were a tl with e.g. `\do{T1}\do{OT1}...\do{T1}\do{T2A}`  which records the kernel encodings and the fontenc calls then language packages and files could make quite good guesses about the encodings in such documents too.

**Comment by jbezos** [comment]
@davidcarlisle 

> It would be possible to look at the fontenc options via @ifpackagewith or directly at `\opt@fontec.sty`

But not `\relax`ing `\opt@fontec.sty` would break a lot of existing code, except if the mechanism to avoid multiple loadings is modified, instead of relying on a trick (and even so, because 
`\opt@fontec.sty` will contain only the encodings in the last call).

**Comment by davidcarlisle** [comment]
@jbezos  yes sorry, was just musing on possible implementations without actually having a fully worked out plan.....

As @u-fischer  says it would be possible for fontenc to construct a separate list of all encodings specified in order that you could then use. Which is perhaps the most compatible thing to do?

But longer term re-using the fontenc options for this seems a slightly strange interface and some explicit declaration of the preferred encoding for each language script would perhaps be more natural?

**Comment by jbezos** [comment]
Here is a concrete proposal. Replace in `fontenc`:

    \global\expandafter\let\csname opt@fontenc.sty\endcsname\relax

with something like:

    \ifx\RequestedFontEncodings\@undefined
      \xdef\RequestedFontEncodings{\csname opt@fontenc.sty\endcsname}
    \else
      \xdef\RequestedFontEncodings{\RequestedFontEncodings,\csname opt@fontenc.sty\endcsname}
    \fi
    \global\expandafter\let\csname opt@fontenc.sty\endcsname\relax

With this piece of code and some changes in `babel`, I've managed to make the minimal example work as before (and as I would expect).

I had plans to release a new version of `babel` in a week or so (mainly to add a few `ini` files for Greek and Latin). It would be great if I could fix it in time for TeXLive 2020.

**Comment by FrankMittelbach** [comment]
I opened an issue https://github.com/latex3/latex2e/issues/273 for this. Once this is distributed it can be used by babel to correctly set the \latinencoding
