### ISSUE TITLE
frenchspacing Icelandic and Dutch

### ISSUE THREAD

**Issue by floriandk** [latex3/babel#49]
`babel` uses `\nonfrenchspacing` when Icelandic or Dutch are used. Afaik both printing traditions have long ago abandoned double-spacing (in as far they ever used it at all) and I'd suggest to make frenchspacing the standard in `babel`, too.

**Comment by jbezos** [comment]
Makes sense. I'll study it.

**Comment by jbezos** [comment]
I‘m closing this issue because it’s now listed in [Enhancements requests](https://github.com/latex3/babel/projects/1). This doesn’t mean it’s rejected, just moved to a specific page for enhancements.
