### ISSUE TITLE
babel french breaks pdflatex with english references in biblatex

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/babel#50]
The following (not-so-)minimal example:
```latex
\documentclass{article}
\usepackage[T1]{fontenc}% Only to silence warning
\usepackage{csquotes}% Only to silence warning
\usepackage[french]{babel}
\usepackage[
  language=auto,
  autolang=other,
  bibstyle=authoryear,
  ]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\textcite{worman}
\end{document}
```
breaks when run with `pdflatex`. I'm reporting here because the issue
_seems_ to be at the `babel` side, and not `biblatex`'s. Apologies if
I'm wrong.

I traced the issue back to the definition of `\bbl@read@ini` and
`\bbl@iniline`. While reading the `babel-en.ini` file, `\bbl@iniline`
checks if the line starts with a `;` using:  
    `\@ifnextchar;\bbl@iniskip\bbl@inipreread`.
However since `french` is loaded, `;` is an active character and the
test takes the false branch, and then it breaks. Since the `.ini` file
doesn't do any typesetting, there should be no need for active
characters there, so I think they could be made catcode-other there.

**Comment by jbezos** [comment]
From your description (not yet tested), I'd say the problem is in `babel`, indeed. I'm somewhat busy right now, but I'll try to fix it in a few days (in time for TeXLive, I hope).
