### ISSUE TITLE
Locale is not switched correctly with COMBINING characters

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#54]
Because by default they belong to no script block. So, very likely combining characters must be assigned to the locale of the previous letter.

**Comment by u-fischer** [comment]
For combining chars using the locale of the previous letter is imho the right thing (and for once it is actually useful that combining chars are behind the base letter). But beside this there are other chars which don't belong to a script block and where the decision to which locale they belong and how to implement this isn't so easy. 

For example take this slightly adapted example from the luaotfload documentation (the colors represent scripts):

~~~~
\documentclass[12pt]{report}
 \directlua{
     luaotfload.add_multiscript
       ("cyrlgrekbeng",
        {
          cyrl = "DejaVuSans:mode=node;script=cyrl;color=FF0000;",
          grek = "texgyreheros:mode=harf;script=grek;color=0000FF;",
          beng = "NotoSansBengali:mode=harf;script=bng2;color=00FF00"
        }
       )
      }
\begin{document}

\font\test={name:DejaVuSans:mode=node;multiscript=cyrlgrekbeng;}

  {\Large \font\test={name:DejaVuSans:mode=node;multiscript=cyrlgrekbeng;}\test
   „a^^^^0301123!?“  „π^^^^0301123!?“ „a!?“  „Б123!?“ a „\char"0995\char"09BF 123“
   a 123π123 
  }

\end{document}  
~~~~

![image](https://user-images.githubusercontent.com/4047173/76681813-36dcf800-65f7-11ea-9889-b8442fbd43d9.png)

**Comment by jbezos** [comment]
> and where the decision to which locale they belong

I play with advantage ;-), because with `babel` there is always an active locale which serves as default. Furthermore, with `\babelcharproperty` you can (re)assign a char to a certain locale. Note with luatex `babel` decouples the language in the TeX sense (ie, `\language` or `<node>.lang`) and the locale (which is stored as a node attribute).

I wonder if LaTeX itself should provide some kind of built-in locale identifier.

**Comment by car222222** [comment]
What type of things is this ‘locale’ used for in babel?

**Comment by u-fischer** [comment]
@jbezos  the problem is not a missing default. We could probably force the quotes and the digits to always use the latin font, but this is probably not what the user want. Normally I would expect they  want punctuations and quotes to use the font of the current script. For example in the  example above I would expect at least some users to want black (latin) quotes around the `a` and  blue (greek) quote symbols around the pi. And I expect that other users actually would want black latin quotes everywhere. And others will perhaps want latin quotes at the outside but greek codes inside such quotes.

**Comment by jbezos** [comment]
@car222222 Currently, line breaking, with 3 types: Western (which relies on hyphenation), South East Asian (like Thai, with a mixture of hyphenation and some lua code), and CJK (pure lua, based on Unicode). Indirectly, bidi writing, too.

**Comment by jbezos** [comment]
@u-fischer There is no way to know just by the context which is the correct locale/script for a punctuation mark, because it could depend on the semantics. Quotes around Arabic words are Latin if you are just listing these words in an English text, but they are Arabic if these words form a sentence (eg, an Arabic quotation). In your example, if you are listing non-German strings in a German text, then clearly the quotes are those from the German font. But there is no general rule even in a single document, and at some point you may need to set the locale explicitly.
