### ISSUE TITLE
babel hook for \select@language

### ISSUE THREAD

**Issue by moewew** [latex3/babel#55]
Following on from https://github.com/plk/biblatex/issues/970.

For `biblatex` it would be extremely convenient to have a hook that is executed every time `babel` switches languages. At the moment we patch (`\pretocmd`) `\select@language` for that, but that has proven tricky for catcode reasons.

I may well be missing something with the existing hooks, so I will list what I think are our desiderata for that hook
* executed every time `babel` switches languages (I notice that currently there seems to be an inconsistency connected to on-the-fly loading of languages: https://github.com/plk/biblatex/issues/964, but I have yet to get to the bottom of this)
* ideally the hook would get the language name as an argument (best case in its expanded form and not as `\languagename`); if that is not possible it would be useful to have a documented macro that is guaranteed to have the correct language name at that point (would `\languagename` be safe?)
* the hook can write to `\extras<languagename>` and `\noextras<languagename>`
* the hook is executed before `\extras<languagename>` is used
* ideally the hook is executed at a grouping level more or less equal to `\select@language` which means, we don't need `\global` to (re)define a macro for the duration of the selected language.

Obvisouly the real 'minimal example' I'm interested in involves `biblatex`, so here is an example that shows basically what we are doing at the moment.

```latex
\documentclass[dutch,ngerman,magyar,french,british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{etoolbox}

\usepackage{xcolor}

\makeatletter
\pretocmd\select@language{\myfakehook{#1}}
  {}{\fail}

\newcommand*{\myfakehook}[1]{%
  \edef\mylanguagename{#1}%
  \begingroup
  \edef\my@tempa{%
    \endgroup
    \csgappto{extras#1}{%
      \noexpand\typeout{selecting #1}%
      \noexpand\@ifundefinedcolor{col@#1}
        {\noexpand\normalcolor}
        {\noexpand\color{col@#1}}}%
    \csgappto{noextras#1}{%
      \noexpand\typeout{deselecting #1}%
    }}%
  \my@tempa
}

\definecolor{col@british}{rgb}{0,0,1}
\definecolor{col@ngerman}{rgb}{1,0,1}
\definecolor{col@dutch}{HTML}{FFA500}
\makeatother

\begin{document}
Lorem \mylanguagename\ (british)

\selectlanguage{ngerman}
ipsum \mylanguagename\ (ngerman)

\selectlanguage{french}
dolor \mylanguagename\ (french)

\selectlanguage{dutch}
sit \mylanguagename\ (dutch)

% the uses of \foreignlanguage are interesting:
% they call \extras<...>
% but not \select@language
% so the outcome depends on whether or not
% the language has been used (with \select@language) before

% was used before: extras contain something
% and are used, but \mylanguagename is off
\foreignlanguage{french}{amet \mylanguagename\ (french)}

% wasn't used before: extras empty (so we keep)
\foreignlanguage{magyar}{consectur \mylanguagename\ (magyar)}
\end{document}
```

Conceptually it may be much nicer to split what we are doing into two hooks:
* One hook that is only executed once when a language is loaded for the first time (either via a preamble option or via on-the-fly loading): Here we would populate `\extras<language>` and `\noextras<language>`.
* One hook that is executed any time a language is selected: Here we would do very little (except set our version of `\languagename`).

**Comment by jbezos** [comment]
This a possible how, but the why could be more useful. Eg, why do you need to modify `\extras<language>`? Note there is a way to inject code to be executed at this point even if the language has not been defined:

```
\documentclass{article}

\usepackage[english]{babel}

\AddBabelHook[danish]{bltx}{beforeextras}{\Large}

\begin{document}

English \foreignlanguage{danish}{Danish} English.

\end{document}
```
So, by knowing the why, we could determine the how.

**Comment by moewew** [comment]
`biblatex` has always stored all of its language definitions (strings *and* 'extras' like date handling but also other language-dependent stuff) in `\extras<language>`.

**Comment by jbezos** [comment]
Like this?
```
\documentclass{article}

\usepackage[english]{babel}

\makeatletter
\AddBabelHook[danish]{bltx}{beforeextras}{%
  \ifx\myextrasdanish\undefined
    \gdef\myextrasdanish{\Large}%
    \g@addto@macro\extrasdanish{\myextrasdanish}%
  \fi}
\makeatother

\begin{document}

\show\extrasdanish

English \foreignlanguage{danish}{Danish} English.

\show\extrasdanish

English \foreignlanguage{danish}{Danish} English.

\show\extrasdanish

\end{document}
```

Very likely there are better options. This is the first one that has occurred to me.

**Comment by moewew** [comment]
Sort of. `beforeextras` looks very promising, I guess the only thing I need is an argument `#1` that contains the language name (like for example in `adddialect`, if I understand correctly). We don't know which languages are going to be loaded beforehand (unless there is a hook for that), so we need a hook that works for all languages alike and we need access to the actual language name.

**Comment by u-fischer** [comment]
@moewew  You have access to lots of info about the language inside the hook. And the language name is optional, so you can add something to all languages:

~~~~
\documentclass{article}

\usepackage[english]{babel}

\BabelEnsureInfo
\begin{document}

\AddBabelHook{bltx}{beforeextras}{\languagename, \localeinfo {tag.bcp47}, \localeinfo{script.tag.bcp47}}
\selectlanguage{english}
English 

\foreignlanguage{danish}{Danish} 

English.

\foreignlanguage{ngerman}{German}

\end{document}
~~~~

**Comment by moewew** [comment]
@u-fischer Ah, I didn't realise `\languagename` was safe to use inside that hook. Thanks for pointing that out.

Yes, I guess that should get me pretty far. At least my example from the first post becomes
```latex
\documentclass[dutch,ngerman,magyar,french,british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{etoolbox}

\usepackage{xcolor}

\makeatletter
\AddBabelHook{bltx}{beforeextras}{%
  \myfakehook{\languagename}%
}

\newcommand*{\myfakehook}[1]{%
  \edef\mylanguagename{#1}%
  \begingroup
  \edef\my@tempa{%
    \endgroup
    \csgappto{extras#1}{%
      \noexpand\typeout{selecting #1}%
      \noexpand\@ifundefinedcolor{col@#1}
        {\noexpand\normalcolor}
        {\noexpand\color{col@#1}}}%
    \csgappto{noextras#1}{%
      \noexpand\typeout{deselecting #1}%
    }}%
  \my@tempa
}

\definecolor{col@british}{rgb}{0,0,1}
\definecolor{col@ngerman}{rgb}{1,0,1}
\definecolor{col@dutch}{HTML}{FFA500}
\makeatother

\begin{document}
Lorem \mylanguagename\ (british)

\selectlanguage{ngerman}
ipsum \mylanguagename\ (ngerman)

\selectlanguage{french}
dolor \mylanguagename\ (french)

\selectlanguage{dutch}
sit \mylanguagename\ (dutch)

\foreignlanguage{french}{amet \mylanguagename\ (french)}

\foreignlanguage{magyar}{consectur \mylanguagename\ (magyar)}
\end{document}
```
which looks pretty good.

**Comment by moewew** [comment]
Since https://github.com/plk/biblatex/commit/02d50647aa4b0000e33be2eaa6b83ee6adcd738b `biblatex` is using `\AddBabelHook`. Fingers crossed I didn't break anything.

Thank you very much for your help and sorry for opening an issue for what turned out to have been a feature for about seven years.

**Comment by jbezos** [comment]
You are welcome and I'm glad this solved it. If not, just let me know what you need. In a future release there will be a new hook to provide an official way to do things like that: https://tex.stackexchange.com/questions/527949/babel-define-language-synonym-for-ieeetran/527991#527991 , which I think may be useful to you.
