### ISSUE TITLE
Definition of \bbl@cs missing in switch.def

### ISSUE THREAD

**Issue by moewew** [latex3/babel#57]
Consider the following example document
```latex
\documentclass{article}

\makeatletter
\begin{document}
\adddialect\l@austrian\l@german
\end{document}
```
With `babel` 3.42 (2020/03/22) this document fails for me with the following error
```
! Undefined control sequence.
\adddialect ...####1####2####3####4{}\fi }\bbl@cs 
                                                  {languages}\endgroup 
l.5 \adddialect\l@austrian\l@german
```
A short look at `switch.def` (which is baked into the LaTeX format) shows that the definition of `\adddialect` indeed involves `\bbl@cs`, but that command is only defined in `babel.sty`/`babel.def` (which aren't baked into the format) and not in `switch.def`.
 
Granted, the example may not be particularly true to life, but this causes real-world issues with `polyglossia` (v1.47), see https://github.com/reutenauer/polyglossia/issues/400 (v1.48 of `polyglossia` will have an emergency fix here, so the example may not reproduce the issue in the near future).
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage[variant=australian]{english}

\begin{document}
Lorem
\end{document}
```

---

I guess this issue is structurally similar to https://github.com/latex3/latex2e/issues/17.

**Comment by jbezos** [comment]
Argh! I've some test files for `polyglossia` but they didn't catch it. :-(

**Comment by moewew** [comment]
Oh yes, you have to put in a bit of work to reproduce the issue. (I found the example above by searching for uses of the problematic command from the error message in https://github.com/reutenauer/polyglossia/issues/400.)

While I grepped for `\bbl@cs` I also found a call to `\bbl@csarg` in `switch.def`, but like `\bbl@cs` `\bbl@csarg` appears to be defined only in `babel.def`/`babel.sty`. I didn't manage to follow the chain of definitions back to a what looked like an official (non-`@`) command I could use in an MWE, but it may be something you'd like to have a look at as well.

Is there documentation somewhere about what LaTeX packages can expect from `switch.def`? It is baked into the kernel, but there is nothing about `\adddialect` in `source2e` and from the `babel` documentation it is not quite clear to me which bits depend on `babel.sty` and which bits are free to use for packages like `polyglossia`.

The following (probably nonsensical) example
```latex
\documentclass{article}

\begin{document}
\selectlanguage{french}
Lorem
\end{document}
```
fails with
```
 Undefined control sequence.
\reserved@a ->\babelprovide 
                            {\languagename }
l.5 \selectlanguage{french}
```
for me. Which suggests `\selectlanguage` and some of the machinery are available, but then at some point `\babelprovide` is used, which is not defined.

**Comment by reutenauer** [comment]
That’s fine, and we’ve added a stopgap in the release we made for TeX Live 2020, but we need to discuss about a long-term solution, because this is not the first time it happens.

**Comment by jbezos** [comment]
@reutenauer IMO, the best option is to copy `switch.def` in `polyglossia` with the necessary changes to suit the needs of the package. I'll extend and refactor several macros in `switch.def` in a few weeks, after the release of TeXLive.

**Comment by jbezos** [comment]
@moewew Although in passing, the `babel` manual mentions the possibility of loading a different version of a `switch.def` (or nothing). There is a hook for this purpose (`loadkernel`).

**Comment by reutenauer** [comment]
> @reutenauer IMO, the best option is to copy `switch.def` in `polyglossia` with the necessary changes to suit the needs of the package.

  Well, that’s just it: we don’t need any change to the macros from switch.def, we just need them to work.  At the moment they don’t really, since they may depend on other parts of Babel.  What Moritz and I are asking for is some sense of whether we can rely on them or not.

**Comment by jbezos** [comment]
I'm still studying how to reorganize the files and the code, so I'm not yet sure. But if you send to me a set of test files, there will be more chances  that the changes won't break polyglossia.

**Comment by moewew** [comment]
Leaving aside the question which commands `polyglossia` actually needs I would have naively assumed that all 'user-level commands' (by that I mean all commands without `@` in the name) in `switch.def` work as documented.

As far as I can tell that are
* `\adddialect`
    ```latex
    \documentclass{article}

    \makeatletter
    \begin{document}
    \adddialect\l@austrian\l@german
    \end{document}
    ``` 
* `\iflanguage`
    ```latex
    \documentclass{article}
    \begin{document}
    \iflanguage{english}{Y}{N}

    \iflanguage{dutch}{Y}{N}
    \end{document}
    ``` 
* `\selectlanguage`
* `\otherlanguage`, `\endotherlanguage`
* `\otherlanguage*`, `\endotherlanguage*`
* `\foreignlanguage`
* `\hyphenrules`, `\endhyphenrules`
    ```latex
    \documentclass{article}

    \begin{document}
    \begin{hyphenrules}{english}
    Leberwurst \showhyphens{Leberwurst}
    \end{hyphenrules}

    \begin{hyphenrules}{ngerman}
    Leberwurst \showhyphens{Leberwurst}
    \end{hyphenrules}
    \end{document}
    ``` 
* `\providehyphenmins`

Now it may turn out that it is simply not sensible to expect some of these macros to work properly if the full `babel` machinery (`babel.sty`) is not loaded – and that is absolutely fine. (I added short MWEs to the macros that I expected to/could see working without `babel.sty`.) Conceptually it would feel nicer to me if macros that "don't make sense" without `babel.sty` were defined in a different file that is not loaded into the kernel. Since `switch.def` is usually baked into the kernel, all of these commands currently feel like they are part of the LaTeX core and thus usable (to some extent) without `\usepackage{babel}`.

**Comment by jbezos** [comment]
I've gone back to 1999 and `hyphen.cfg` already contained macros defined in `babel.def`, and I've even actually tested the switching commands with a ’demo’ version of TeXLive 2003, and as I expected they didn't work. In some old documents I found, these macros are always described as part of `babel`, and its loading in the format has been considered optional.

So, there are two ways to avoid problems in the future: either copy `switch.def` or send to me some test files for `polyglossia`. Otherwise, I can't guarantee it will continue to work without loading `babel`.

**Comment by u-fischer** [comment]
@jbezos imho @moewew has a point: The public user commands defined in switch.def should at least not error when used together with the base babel. That means that this here should compile:

~~~~
\documentclass{article}
\usepackage[base]{babel}
\makeatletter
\begin{document}
 \selectlanguage{english} %fails because of \babelprovide
\providehyphenmins 234
\adddialect\l@austrian\l@german

\iflanguage{english}{Y}{N}

\iflanguage{dutch}{Y}{N}

\begin{hyphenrules}{english} %fails because of \languageshorthands
Leberwurst \showhyphens{Leberwurst}
\end{hyphenrules}
\end{document}
~~~~

**Comment by jbezos** [comment]
@u-fischer And this is a real bug, indeed.

**Comment by moewew** [comment]
You can use the three MWEs I posted above for testing if you like. I didn't add a test for `\selectlanguage` because I didn't expect it to work without full `babel` and I didn't have a test for `\providehyphenmins`, because I didn't know a good way to test it. (But Ulrike has combined all tests into one.)

But let me reiterate that that is just what I naively expected, so it would be OK if you say that this is not supported, but then I think it would make sense to move these commands to a different file.

**Comment by jbezos** [comment]
> I think it would make sense to move these commands to a different file.

I think so.

**Comment by jbezos** [comment]
I've marked this issue as `enhancement` and not as a `bug` because `switch.def` has never worked without loading `babel` (except some macros).

**Comment by reutenauer** [comment]
> So, there are two ways to avoid problems in the future: either copy `switch.def` or send to me some test files for `polyglossia`. Otherwise, I can't guarantee it will continue to work without loading `babel`.

  You lack imagination.  I have found a truly wonderful solution, which the margin of this issue tracker is unfortunately too narrow to contain ;-)  But here’s one simple idea to start with: what about giving a few days’ notice when you plan to make a Babel update?  That would be a forewarning, and a chance to test beforehand – already a considerable improvement on the current situation.

**Comment by jbezos** [comment]
Issues like this can be easily avoided with a set of test files. I have a few for `polyglossia`, but unfortunately it seems they are not enough (perhaps because I don't know well what to test). With test files I can catch possible errors and fix them even before I release anything, and any help at this regard will be very valuable.

GitHub contains the development version of babel, and in fact the conflicting change was pushed a couple of days before the final release.

**Comment by reutenauer** [comment]
> Issues like this can be easily avoided with a set of test files. I have a few for `polyglossia`, but unfortunately it seems they are not enough (perhaps because I don't know well what to test). With test files I can catch possible errors and fix them even before I release anything, and any help at this regard will be very valuable.

  Automated tests are always helpful, but we need to know what we’re testing for.  In the long run, I suspect that testing for the current behaviour would only make future development unnecessarily cumbersome.  Is that why Moritz’ tests are not satisfactory to you?

> GitHub contains the development version of babel, and in fact the conflicting change was pushed a couple of days before the final release. 

  I know that, that is not what I meant.  I meant a public announcement to give me (and others) a chance to visually inspect the latest changes.  There is only so much one can do with automated tests.

**Comment by jbezos** [comment]
See https://github.com/latex3/babel/wiki/What's-new-in-babel-3.43 .

> Is that why Moritz’ tests are not satisfactory to you?

I explained the reason in a previous post.

**Comment by jbezos** [comment]
@moewew @reutenauer Here an example of a test file for `babel`. It just uses some macros. Something like this, but loading `polyglossia` and using its macros will be helpful. That's all. I don't use `polyglossia`, so I don't know what to write.
```
\documentclass{article}

\usepackage[english,danish]{babel}

\babelprovide[import, main]{french}
\babelprovide[import]{polish}
\babelprovide[import=da]{danish}

\begin{document}

\day=25
\month=12
\year=1999

fr/fr: frenchdate{2016}{8}{2}

fr/pl: \polishdate{2010}{9}{3}

fr/da: \danishdate{\year}{\month}{\day}

\show\englishdate

fr: \today

\end{document}
```

**Comment by moewew** [comment]
@jbezos The new plan sounds good.

I must have missed your argument why my suggested test files are not adequate, so please accept my apologies when I write something you already discussed.

I think there are broadly two approaches you can have to testing.

You can test the core features directly in a very reduced setting. That's what I did. I just looked at `switch.def` and wrote down the commands that I naively expected to work and a very short test for them. Test files like that have the advantage that they test for one thing only (so if they break you have a good idea to look) and if you do it right, then chances are you cover most basic uses of those commands. This may be called an analytic approach.

Then there is the synthetic approach where you take a document that calls a variety of the commands in all sorts of different real-world scenarios. That's what you get when you test `switch.def` with a document loading `polyglossia` that using some of its features. The advantage is that you can catch problems that only come to light when the commands interact. The disadvantage is that you may not catch all commands systematically. (Just as an example `\adddialect`, the command that made me start all this in the first place, I used in quite a few places in the `polyglossia` code, but it took me quite a while to find a small example document that actually uses it), so things  may fall through the cracks unless the tests get very complex.

The other disadvantage I'm seeing here is conceptual. If you test only against `polyglossia` real-world examples, there is still no clearly defined set of commands that package authors can rely upon. What we are then essentially saying is that `polyglossia` should work, but there is no guarantee about the other commands not used by `polyglossia` or even what happens if `polyglossia` is not loaded. That may not be a big deal, after all why would you want things from `switch.def` unless you are using `babel` or `polyglossia`? But I imagine it could make the interplay between `babel` and `polyglossia` development tricky if there is no well-defined line as to what should work and what shouldn't.

**Comment by jbezos** [comment]
The point is some of those examples never worked. I'm aware test files cannot catch everything, of course, but having some of them will be _very very very_ useful. There will be mistakes, and bugs, because we all are human, and all I'm asking for is a little help. Could you prepare a few files following the “synthetic approach”?

**Comment by reutenauer** [comment]
But some of them did work – until last month: `\adddialect` in particular was used in Polyglossia for ten years (since [this commit](/reutenauer/polyglossia/commit/86d49e7) in case anyone’s interested).

What I think you mean is that none of these macros were ever _guaranteed_ to work.  If that’s the case that’s fine, but we need to know what is supposed to work and what isn’t, otherwise there’s no point in even thinking of tests.  And if some macros are not meant to be used outside of Babel, I think you should remove them from the format.  The announcement you’re preparing for 3.43 is not completely clear about that.

Does the above make sense?

**Comment by moewew** [comment]
I'm not an avid `polyglossia` user, so I don't have examples using many features lying around, but I can offer the example from the first post as an example of `polyglossia` using both `\adddialect` and `\providehyphenmins` (those two commands appear to be the only commands without an `@` in the name from `switch.def` that `polyglossia` uses directly without redefinition)
```latex
\documentclass{article}

\usepackage{polyglossia}
\setdefaultlanguage[variant=australian]{english}

\begin{document}
Lorem
\end{document}
```

**Comment by jbezos** [comment]
Thank you, @moewew . Thinks like that are what I'm looking for. My test files are not using `variant`, which seems to be an important part of `polyglossia` syntax. I'll add it to my test files with some additions (`\chaptername`, `today`, etc.), so that if I make an unintentional change in those macros by mistake (as I did in `\adddialect`  because of a ‘replace all’, a very dangerous idea!)  it can be caught. I also thought I could look for examples in tex.stackexchange.

**Comment by jbezos** [comment]
@reutenauer These few macros will be preserved for backwards compatibility with minimal definitions. I've searched TeXLive for possible issues, but it seems they are enough (I'm still testing). If `polyglossia` uses another macro (or you know of a package using it), just let me know and I'll add it.

**Comment by moewew** [comment]
Oh, one thing: Does "minimal definitions" mean "the macros work as advertised even without loading `babel`" or does it mean "the macros do something (which may not be what people expect) but don't error when `babel` is not loaded"?

I'm surprised that there are many cases where it really is necessary to retain `switch.def` commands. I had thought most people would use `babel` or `polyglossia` for language stuff. And if I understand you correctly, many of the macros haven't worked properly for ages (in that case not defining the macro at all may actually be a step up: it makes it absolutely clear that the thing isn't there and is not supposed to work). So that only leaves us with a number of people who say `\renewcommand` instead of `\def` when they redefine their own version of `\adddialect` and friends, I'd have thought that that would be *extremely* few cases (if any at all).

W.r.t. the `polyglossia` examples it should be pointed out that `polyglossia` has added some code to avoid some of the errors that people would face when the use the commands as shown in my minimal examples in https://github.com/latex3/babel/issues/57#issuecomment-606837990, so testing against `polyglossia` alone in those matters and not testing truly minimal documents may give the wrong impression.

**Comment by jbezos** [comment]
> Oh, one thing: Does "minimal definitions" mean "the macros work as advertised even without loading `babel`" or does it mean "the macros do something (which may not be what people expect) but don't error when `babel` is not loaded"?

Good point. I'll modify the wiki to add a more precise explanation. But after receiving lots of bug reports, it's clear “what people expect“ could be quite unpredictable.

> I'm surprised that there are many cases where it really is necessary to retain `switch.def` commands.

Me too. And even loading `switch.def` or `babel.def`directly!

> [...] so testing against `polyglossia` alone in those matters and not testing truly minimal documents may give the wrong impression.

Sure. I have test files for Plain and other cases I've found.

**Comment by jbezos** [comment]
I've retouched the text:

>  Some `babel` commands have been loaded with the LaTeX format for years, but most of them didn't work without `\usepackage{babel}` and raised some cryptic errors. Now in the format some of them have minimal definitions (`\addlanguage`, `\adddialect`, `\iflanguage`, `\providehyphenmins`) and others raise a more explanatory error (`\selectlanguage` and other selectors). The macros in the format with minimal definitions behave as described in the `babel` manual, but without some additional internal actions added by and specific to the `babel` package (for example, it adds code for `\AddBabelHook{..}{adddialect}{..}` to work).

**Comment by reutenauer** [comment]
On Thu, Apr 16, 2020 at 08:37:16AM -0700, Javier Bezos wrote:
> I've retouched the text:
> 
>>  Some `babel` commands have been loaded with the LaTeX format for years, but most of them didn't work without `\usepackage{babel}` and raised some cryptic errors. Now in the format some of them have minimal definitions (`\addlanguage`, `\adddialect`, `\iflanguage`, `\providehyphenmins`) and others raise a more explanatory error (`\selectlanguage` and other selectors). The macros in the format with minimal definitions behave as described in the `babel` manual, but without some additional internal actions added by and specific to the `babel` package (for example, it adds code for `\AddBabelHook{..}{adddialect}{..}` to work). 

  Looks great, thanks!  For completeness this paragraph should probably be referred to from source2e, but we can take that later :-)
