### ISSUE TITLE
problem with latest update

### ISSUE THREAD

**Issue by hvoss49** [latex3/babel#6]
With latest update of babel and lualatex 1.10.0 I run into trouble.
It works well with pdflatex and xelatex.
------------------------------------------------------------

```
\listfiles
\documentclass[english]{article}
\usepackage{babel}
\usepackage{amsmath}
\begin{document}

\begin{flalign}
y &= f(x)
\end{flalign}
\end{document}

```
--------------------------------------------------------------

> 
> ! Missing number, treated as zero.
> <to be read again>
> \relax
> l.10 \end{flalign}
> 
> ?
> ! Illegal unit of measure (pt inserted).
> <to be read again>
> \relax
> l.10 \end{flalign}
> 
> 

--------------------------------------------------------------

```
*File List*
 article.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
   babel.sty    2019/04/01 3.28 The Babel package
 english.ldf    2017/06/06 v3.3r English support from the babel system
 amsmath.sty    2018/12/01 v2.17b AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
 ***********
```

--------------------------------------------------------------

> voss@shania:~/Links/texmf-local-latex/firamath-otf$ lualatex test.tex
> This is LuaTeX, Version 1.10.0 (TeX Live 2019)
>  restricted system commands enabled.
> (./test.tex
> LaTeX2e <2018-12-01>

--------------------------------------------------------------

**Comment by jbezos** [comment]
`Babel` is executing some code related to `bidi`, which is being activated by mistake (the version of `luatex` is not relevant, the bug is pure `babel`). I'll fix it asap.

**Comment by jbezos** [comment]
The problem was with the fix for boxes inside math with `bidi=basic(-r)`. I've uploaded to CTAN a new version removing this fix (a need to investigate a better one).
