### ISSUE TITLE
Please change the Finnish \contentsname to "Sisällys"

### ISSUE THREAD

**Issue by tlikonen** [latex3/babel#61]
In the Finnish language the most common name for table of contents is "Sisällys" (sometimes longer form "Sisällysluettelo"). However, the Babel package defines name ”Sisältö" which means the same but is rarely used in this context.

I suggest changing the definition of `\contentsname` command to "Sisällys".

**Comment by tlikonen** [comment]
I filed the same issue to Polyglossia: https://github.com/reutenauer/polyglossia/issues/403

**Comment by jbezos** [comment]
Thank you. I'll modify the finnish style after the release of TeXLive 2020. I'll also fix the corresponding value in the `ini` locale file.

**Comment by jbezos** [comment]
Submitted the `finnish` style to CTAN. It should be available in a couple of days.
