### ISSUE TITLE
Spurious space in \foreignlaguage is some cases…

### ISSUE THREAD

**Issue by cgnieder** [latex3/babel#62]
I'm not sure if this counts as a bug (maybe not), but I wanted to let you know, anyway.

This produces no error but  a whitespace for languages that have not been given as option:

```latex
\documentclass{article}
\usepackage[german,english]{babel}
\begin{document}
+\foreignlanguage{german}{}+  % no space
+\foreignlanguage{french}{}+  % space
+\foreignlanguage{english}{}+ % no space
+\foreignlanguage{spanish}{}+ % space
\end{document}
```

**Comment by jbezos** [comment]
Which version are you using? It's supposed to be fixed in 3.42.

**Comment by cgnieder** [comment]
Sorry, I meant to give the version...
I still have 2020/02/28 3.41. This is can probably be closed then.

**Comment by jbezos** [comment]
Let's wait before closing it. For several reasons I can't run tex right now and I'd like to be sure.

**Comment by u-fischer** [comment]
I have 2020/03/22 3.42 and I see no spurious spaces:

![image](https://user-images.githubusercontent.com/4047173/78563062-a9b64900-781a-11ea-8d8a-4e2083d6635d.png)

**Comment by jbezos** [comment]
@u-fischer Thank you, Ulrike. Then I close it. (These days of lockdown are being crazy.)
