### ISSUE TITLE
Babel syriac

### ISSUE THREAD

**Issue by lyndondrake** [latex3/babel#64]
Hi,

Ages ago I did a very simple `.ini` file for Syriac, which seems to produce the intended results for my texts.

I wondered what I should do in order to get this integrated into the main babel distribution?

Best,
Lyndon

**Comment by jbezos** [comment]
Thank you. Currently there is an `ini` file for Syriac, but without captions. So, yes, either create a pull request or just copy here the file. I've planned a new release for the next week, and it would be great if I could include it.

**Comment by lyndondrake** [comment]
Actually yours is more complete than mine already. I was just using the wrong bcp47 code for it so i can easily switch to yours. I'm not sure where to find a good source for the captions – I don't know any modern Syriac-speakers

**Comment by jbezos** [comment]
Thank you anyway. And if you find a good source, just let me know.
