### ISSUE TITLE
Automatic unbreakable space between number and percentage

### ISSUE THREAD

**Issue by jeromevillebrun** [latex3/babel#65]
Hello,

In French, the typographic rules say that there should be a space between the number and the percentage (in fact, between the number and any unit of measure). It looks like this has not yet been implemented by the babel package for the French language.

MWE (compiled with xelatex) :
```
\documentclass{article}
\usepackage[french]{babel}

\begin{document}
Without a space between the number and the sign, it doesn't insert any (breakable or unbreakable) space : 5\%

Even with a space, it does not replace it with an unbreakable space : aaaa 5 \%.
\end{document}
```

![image](https://user-images.githubusercontent.com/63289526/80799888-554b8280-8ba8-11ea-9efb-69e89217296e.png)

The strange thing is that it already does it for Spanish. The same piece of code gives : 

![image](https://user-images.githubusercontent.com/63289526/80800144-0d792b00-8ba9-11ea-8462-f30a9984583d.png)

Here, using `\usepackage[spanish]{babel}`, contrary to what the text says, an unbreakable space is inserted when there isn't any before the percent sign, and if there is already a breakable space it is replaced by an unbreakable one (which is exactly what should be done for french too).

**Comment by u-fischer** [comment]
The french module is maintained by Daniel Flipo (http://daniel.flipo.free.fr/babel-french/). Feature requests should be sent to him.  Beside this I recommend to use a package like siunitx to format units.

**Comment by jeromevillebrun** [comment]
Ok, thank you. I sent him an email.
