### ISSUE TITLE
Word separators in Amharic

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#66]
The default hyphenation patterns for Ethiopic script do not properly treat ፡  as a word separator. See
https://www.w3.org/TR/elreq/#ethiopic_hyphenation and https://tex.stackexchange.com/questions/541648/how-to-use-fontspec-to-typeset-amharic-text-in-latex/541725#541725 .

A working example by Davislor is (adapted to babel):
```
\documentclass[12pt]{article}

\usepackage[english]{babel}

\usepackage{newunicodechar}

\babelprovide[import, hyphenrules=ethiopic]{amharic}

\babelfont[amharic]{rm}{FreeSerif}

\newunicodechar{፡}{፡\ }
\newunicodechar{።}{\@{።} }
\newunicodechar{፣}{፣ }
\newunicodechar{፤}{፤ }
\newunicodechar{፥}{፥ }
\newunicodechar{፦}{፦ }
\newunicodechar{፧}{\@{፧} }
\newunicodechar{፨}{\@{፨} }
\newunicodechar{፠}{\@{፠} }

\begin{document}

This is english text.

\selectlanguage{amharic}

በዩኔስኮ፡ተ

በዩኔስኮ፡ተዘጋጅቶ፡በኢትዮጵያ፡ብሄራዊ፡ኮሚሽን፡ተተረጎመ

የሰው፡ልጅ፡ሁሉ፡ሲወለድ፡ነጻና፡በክብርና፡በመብትም፡እኩልነት፡ያለው፡ነው።፡የተፈጥሮ፡ማስተዋልና፡ሕሊና፡ስላለው፡አንዱ፡ሌላውን፡በወንድማማችነት፡መንፈስ፡መመልከት፡ይገባዋል።

እያንዳንዱ፡ሰው፡የዘር፡የቀለም፡የጾታ፡የቋንቋ፡የሃይማኖት፡የፖለቲካ፡ወይም፡የሌላ፡ዓይነት፡አስተሳሰብ፡የብሔራዊ፡ወይም፡የኀብረተሰብ፡ታሪክ፡የሀብት፡የትውልድ፡ወይም፡የሌላ፡ደረጃ፡ልዩነት፡ሳይኖሩ፡በዚሁ፡ውሳኔ፡የተዘረዘሩት፡መብቶችንና፡ነጻነቶች፡ሁሉ፡እንዲከበሩለት፡ይገባል።

ከዚህም፡በተቀረ፡አንድ፡ሰው፡ከሚኖርበት፡አገር፡ወይም፡ግዛት፡የፖለቲካ፡የአገዛዝ፡ወይም፡የኢንተርናሽናል፡አቋም፡የተነሳ፡አገሩ፡ነጻም፡ሆነ፡በሞግዚትነት፡አስተዳደር፡ወይም፡እራሱን፡ችሎ፡የማይተዳደር፡አገር፡ተወላጅ፡ቢሆንም፡በማንኛውም፡ዓይነት፡ገደብ፡ያለው፡አገዛዝ፡ሥር፡ቢሆንም፡ልዩነት፡አይፈጸምበትም።

እያንዳንዱ፡ሰው፡የመኖር፣፡በነጻነትና፡በሰላም፡የመኖሩ፡መጠበቅ፡መብት፡አለው።

\end{document}
```

**Comment by jbezos** [comment]
With luatex it can be easily emulated with either South East Asia or CJK linebreaking. After some experiment, I'll opt for CJK, because it requires no hyphenation rules at all. Only for luatex. For xetex very likely the proper solution must be based on intercharclasses, but this will be added later.

**Comment by khaledhosny** [comment]
For XeTeX you should try `\XeTeXlinebreaklocale`.

**Comment by jbezos** [comment]
Yes, I tried, but sadly line breaking is wrong.

**Comment by khaledhosny** [comment]
Ah, right. XeTeX will do the line breaking, but it will not consider it a stretchable space so you end up with overfull lines.
