### ISSUE TITLE
Discretionaries between letter and diacritic

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#68]
When adapting an example from tex.stackexchange to babel, I've found a surprising result in diacritic positioning  in luatex (the post is https://tex.stackexchange.com/questions/543601/how-do-i-stack-accents-in-ancient-greek ; in xetex it woks as expected). Here the adapted example:
```
\documentclass{article}

\usepackage[english]{babel}

\babelprovide[import]{ancientgreek}
\babeltags{greek=ancientgreek}

% With the following setting works:
% \babelpatterns[ancientgreek]{ε4^^^^0304}

\babelfont{rm}{Times New Roman}
\babelfont[ancientgreek]{rm}[Renderer=Harfbuzz]{Gentium}
\babelfont{gralt}{Junicode}

\begin{document}

\begin{greek}

ἀσστοῖ[ς] καὶ χσε̄́νοισι ξείνοισι φανε̄̀ς φίλος̣ [εἰμὶ \textgralt{⏑} – ×]

[ὅ]ς πο[τ’] ἀρισστεύο̄ν ἐν προμάχοις [ἔθανεν].
\end{greek}

\end{document}
```
When run with luatex, diacritics are not stacked, and they overlap.

In luatex combining chars are kept and there is a pattern `ε1`, which means a discretionary is inserted between this letter and the diacritic (I presume xetex combines them before the hyphenation pass). By adding a rule to prevent this discretionary it works as expected.

I'm not sure this issue must be addresses by the hyphenation rules, by luaotfload or by babel itself. What do think, @u-fischer?

**Comment by u-fischer** [comment]
My hunch would be that it is a pattern problem (and I have a faint memory of having seen this already) but I think we should ask @zauguin ;-).

**Comment by jbezos** [comment]
This is what I thought. In fact this is how I fixed it, but I wanted to be sure 😉.

**Comment by zauguin** [comment]
I agree that it is a pattern issue, but I'm about to upload [lua-uni-algos](https://github.com/zauguin/lua-uni-algos) to CTAN which implements grapheme breaking. So if we want to, we could easily add a run dropping such discretionaries if we want to. (That would avoid such issues in the future if this turns out to be a problem for many pattern files)

**Comment by jbezos** [comment]
> (That would avoid such issues in the future if this turns out to be a problem for many pattern files)

Thinking a little more about this, I think it's a general issue with combining chars, requiring a pass before `lang.hyphenation`. It's not only about dropping bad discretionaries, but also about inserting them. Here is a test file:
```

\documentclass{article}

\newlanguage\testl
\language\testl

\usepackage{fontspec}

\ifcase0
  \setmainfont[Renderer=Harfbuzz]{FreeSerif}
  \patterns{á3é}
\or
  \setmainfont{FreeSerif}
  \patterns{á3é}
\or
  \setmainfont[Renderer=Harfbuzz]{FreeSerif}
  \patterns{á3é a^^^^03013e^^^^0301}
\or
  \setmainfont{FreeSerif}
  \patterns{á3é a^^^^03013e^^^^0301}
\fi

\directlua{
function test (head)
  texio.write_nl('====')
  texio.write_nl('')
  for item in node.traverse(head) do
    if item.id == node.id'glyph' then
      texio.write('<' .. unicode.utf8.char(item.char) .. '>')
    elseif item.id == node.id'disc' then
      texio.write('[==]')
    else
      texio.write('[' ..  item.id .. ']')
    end
  end
  texio.write_nl('')
  return head
end

luatexbase.add_to_callback("pre_linebreak_filter", test, "test")
}

\begin{document}

\hsize1pt

xxxáéxxx

xxxa^^^^0301e^^^^0301xxx

\end{document}
```

With Harfbuzz and case 0 I get (where `[==]` is a disc):
```
====
[9][0]<x><x>[==]<x><x>[14][12]
====
[9][0]<x><x><x>[13]<á>[13]<é>[13]<x><x><x>[14][12]
```
Without it (case 1):
```
====
[9][0]<x><x><x>[13]<á>[==]<é>[13]<x><x><x>[14][12]
====
[9][0]<x><x><x>[13]<a><́><e><́><x><x><x>[14][12]
```
[I'm puzzled by the missing chars with harf, but the resulting pdf shows them!, so for the moment I'm ignoring it.]

**Comment by zauguin** [comment]
> > (That would avoid such issues in the future if this turns out to be a problem for many pattern files)
> 
> Thinking a little more about this, I think it's a general issue with combining chars, requiring a pass before `lang.hyphenation`. It's not only about dropping bad discretionaries, but also about inserting them. Here is a test file:
> 
> [SKIP]
> 
> With Harfbuzz and case 0 I get (where `[==]` is a disc):
> 
> ```
> ====
> [9][0]<x><x>[==]<x><x>[14][12]
> ====
> [9][0]<x><x><x>[13]<á>[13]<é>[13]<x><x><x>[14][12]
> ```
> 
> Without it (case 1):
> 
> ```
> ====
> [9][0]<x><x><x>[13]<á>[==]<é>[13]<x><x><x>[14][12]
> ====
> [9][0]<x><x><x>[13]<a><́><e><́><x><x><x>[14][12]
> ```
> 
> [I'm puzzled by the missing chars with harf, but the resulting pdf shows them!, so for the moment I'm ignoring it. Perhaps they have been moved into the disc?]

Yes, they are moved into the disc because of the kerning.

I am failing to see right now what you are trying to demonstrate here. What would be your expected behavior?

**Comment by jbezos** [comment]
@zauguin My point is twofold.

1. If combining chars are to be taken into account in patterns files, many of them must be modified to consider every possible case, which, in addition, could lead to a combinatorial explosion.

2. In my test file, the only ‘well-formed’ node list with the required discretionaries is that without harf and with composed chars: `[9][0]<x><x><x>[13]<á>[==]<é>[13]<x><x><x>[14][12]` (the contents of the disc is not shown by the test I posted, bit it's replace=kern, pre=-, and post is empty). The rest, IMO, are not the expected node lists. In particular, I think only the kern must be moved into the discretionary.

**Comment by zauguin** [comment]
> @zauguin My point is twofold.
> 
>     2. In my test file, the only ‘well-formed’ node list with the required discretionaries is that without harf and with composed chars: `[9][0]<x><x><x>[13]<á>[==]<é>[13]<x><x><x>[14][12]` (the contents of the disc are not shown by the test I posted, but it's replace=kern, pre=-, and post is empty). The rest, IMO, are not the expected node lists. In particular, I think only the kern must be moved into the discretionary.

Feel free to open an issue about that in [luaotfload](/latex2e/luaotfload/issues), but it doesn't have a high priority because it doesn't really make a difference anyway. (Except if your issue is that this suppresses other discretionaries, but that problem is much more fundamental and not generally fixable in TeX style, discretionary based, linebreaking.)

> 
>     1. If combining chars are to be taken into account in patterns files, many of them must be modified to consider every possible case, which, in addition, could lead to a combinatorial explosion.

The alternative would be to normalize the input before hyphenating it and after hyphenation suppressing discretionaries in the middle of grapheme clusters. That's probably quite slow. The question is if we could just normalize the input buffer instead, then the nodes should still be normalized if the user didn't do something odd.

**Comment by jbezos** [comment]
@zauguin Issue open. Actually it suppresses hyphenation points.

**Comment by jbezos** [comment]
As to point 1, I've add to the latest news a workaround: https://github.com/latex3/babel/wiki/What's-new-in-babel-3.44#example-2-combining-chars .
