### ISSUE TITLE
"Command \bbl@foreign@x already defined" since version 3.44

### ISSUE THREAD

**Issue by yguilhem** [latex3/babel#69]
Since last 3.44 update, I get an error if I use babel package:
```log
! LaTeX Error: Command \bbl@foreign@x already defined.
               Or name \end... illegal, see p.192 of the manual.
```
It can be reproduced with the following MWE:
```latex
\documentclass{article}           % without any language specified
%\documentclass[english]{article} % with language specified
\usepackage{babel}
\begin{document}
Hello world !
\end{document}
```
More info about my distribution:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020)
(preloaded format=pdflatex 2020.4.10)  20 MAY 2020 14:53
```
I tried to update/reinstall babel through `tlmgr` but it did not change anything.

**Comment by jbezos** [comment]
It looks as if there is some old file left somewhere. Could you post the log file?

**Comment by yguilhem** [comment]
Here is the log. Generated with `pdflatex -interaction batchmode babel.tex`.
That might be `.../tex/generic/babel/babel.def`?
[babel.log](https://github.com/latex3/babel/files/4657985/babel.log)

**Comment by jbezos** [comment]
Have you rebuilt the formats?

**Comment by yguilhem** [comment]
No I did not. It is usually automatically done by `tlmgr` when needed.
After doing
```shell
fmtutil -user --all
```
Problem solved! Thank you a lot and sorry for bothering.

**Comment by jbezos** [comment]
You are welcome. Usually rebuilding is not necessary, but in the latest releases the internal structure has been modified.
