### ISSUE TITLE
Hyphenation in Macedonian in pdfLatex

### ISSUE THREAD

**Issue by tstojan** [latex3/babel#70]
The hyphenation in Macedonian language seems to work nicely with LuaLaTeX and XeLaTeX (talked and communicated with Mojca and Arthur back in October 2019 and this was added with an appropriate Macedonian patterns file). However, hyphen support in pdfLaTeX seems to not work in Macedonian. 

I see files (Miktex in particular):
`MiKTeX 2.9\tex\generic\hyph-utf8\loadhyph\loadhyph-mk.tex` and
`MiKTeX 2.9\tex\generic\hyph-utf8\patterns\tex\hyph-mk.tex`
are all there/installed (or at least copied) as it is for other languages, so all necessary files should be there. Quickly tried some manual edits, but it didn't work.
Also when I go to `MikTeX console -> Settings -> Languages`, I see all the languages (including Macedonian), but the loader, pattern and "installed tick" are shown for all except Macedonian.

Since the languages are similar, I briefly tried in Bulgarian and the hyphen works. Can we enable Macedonian hyphen support in pdfLaTeX?

Edit: I see `mk `folder is missing here: `https://github.com/latex3/babel/tree/master/locale`
I am willing to make a PR on this.

Stojan Trajanovski
-babel contributor for Macedonian

**Comment by u-fischer** [comment]
this is a miktex issue and not a babel issue.  In texlive the patterns are there. Open an issue here that the entry is missing in the language.ini/dat: https://github.com/MiKTeX/miktex/issues.

**Comment by tstojan** [comment]
Thank you for you response. Done that and the language was added in `language.ini`. And I can see it now in `Settings -> Languages`:
![language_added](https://user-images.githubusercontent.com/13030630/83028319-28648100-a029-11ea-804d-47c664049867.png)

However, when I turn on macedonian in babel, it doesn't work:
![macedonian_hyphen](https://user-images.githubusercontent.com/13030630/83028352-33b7ac80-a029-11ea-8957-fc9ad84699cb.png)

But when I switch to bulgarian it works (only babel language change):
![bulgarian_hyphen](https://user-images.githubusercontent.com/13030630/83028379-3fa36e80-a029-11ea-8235-8d970b2ea8e3.png)

Any idea how can this be resolved?

**Comment by u-fischer** [comment]
Work ok for me. If I compile

~~~~
\documentclass{book}
\usepackage[macedonian,showlanguages]{babel}

\begin{document}
blblb
\end{document}
~~~~

I see the language in the log, both in miktex and texlive  (the number can differ):

46	macedonian	loadhyph-mk.tex
