### ISSUE TITLE
babel doesn't work anymore after latest TeXLive update

### ISSUE THREAD

**Issue by andalou** [latex3/babel#73]
When updating TeXLive 2020 and using babel 3.44, the following code throws error:

    \documentclass{article}
    \usepackage[spanish]{babel}
    \begin{document}
    Esto es solo una prueba
    \end{document}

I get:

    This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX) (preloaded format=pdflatex)
    restricted \write18 enabled.
    entering extended mode
    (./hh.tex
    LaTeX2e <2020-02-02> patch level 5
    L3 programming layer <2020-04-06>
    (c:/texlive/2020/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
    (c:/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
    (c:/texlive/2020/texmf-dist/tex/generic/babel/babel.sty
    (c:/texlive/2020/texmf-dist/tex/generic/babel/babel.def
    
    ! LaTeX Error: Command \bbl@foreign@x already defined.
    Or name \end... illegal, see p.192 of the manual.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
    ...
    
    l.745   \endgroup}
    
    ? x
    No pages of output.
    Transcript written on hh.log.

With babel 3.43, it's working fine.

**Comment by jbezos** [comment]
See https://github.com/latex3/babel/issues/72 .

**Comment by andalou** [comment]
After doing

    fmtutil-user --all

it worked.
Sorry for the noise

**Comment by jbezos** [comment]
You are welcome (and sorry for being telegraphic - I was somewhat busy).
