### ISSUE TITLE
\localedate{YYYY}{MM}{DD} just prints YYYYMMDD

### ISSUE THREAD

**Issue by dbitouze** [latex3/babel#76]
In [What's new in babel 3.44](https://github.com/latex3/babel/wiki/What's-new-in-babel-3.44), it's written:

>`\localedate{year}{month}{day}` prints the date for the current locale. 

but the following MCE:
```latex
\documentclass[english]{article}
\usepackage{babel}
\begin{document}
\localedate{2020}{06}{11}
\end{document}
```
just prints "20200611".

Here is my *File List*
```
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
   babel.sty    2020/06/10 3.45 The Babel package
 english.ldf    2017/06/06 v3.3r English support from the babel system
l3backend-pdfmode.def    2020-06-03 L3 backend support: PDF mode
 ***********
```
Am I missing something?

BTW, the `babel`'s documentation 3.45 displays a strange "ø" on page 34:

> `\localedate` øcalendar=.., variant=..⟨year⟩⟨month⟩⟨day⟩

**Comment by jbezos** [comment]
It's explained in the manual - `\localedate` is defined with `\babelprovide`. I've edited the wiki and I'll see if I can modify the macro to raise an error in cases like this.

And thank you for spotting the typo.

**Comment by dbitouze** [comment]
OK, thanks. A complete example in the "1.18 Dates" section, e.g.
```latex
\documentclass[hungarian]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\babelprovide[import=hu]{hungarian}
\begin{document}
\localedate{2020}{06}{10}
\end{document}
```
would be welcome :)

BTW, if this example misses `\usepackage[T1]{fontenc}`, LaTeX  emits the warning: 

> Please use \usepackage{t1enc} with \usepackage[hungarian]{babel}, to get accented chars hyphenated.

But (according to `l2tabu`, among others) `t1enc.sty` is obsolete and should be replaced by `fontenc.sty`, hence `\usepackage{t1enc}` should be replaced by `\usepackage[T1]{fontenc}`.
