### ISSUE TITLE
Missing packages in distributions

### ISSUE THREAD

**Issue by albert-github** [latex3/babel#77]
On the edge of being at the wrong place to ask:

Is there a reason why the languages like Korean and Chinese are not present in the (recent) LaTeX distributions for MikTex and TexLive  (Cygwin) ?

**Comment by josephwright** [comment]
Sorry, this is entirely out of our control: packaging issues are not part of the macro layer.

**Comment by albert-github** [comment]
The total generation procedure of the distribution packages is unknown to me, but it is a bit strange for me that Japanese runs but Korean doesn't and I get the error:
```
! Package babel Error: Unknown option `korean'. Either you misspelled it
(babel)                or the language definition file korean.ldf was not found
```

**Comment by jbezos** [comment]
This is because `japanese` is supported while `korean` is not (at least with the standard `ldf`  mechanism; there is some partial support with an `ini` file loaded with `\babelprovide`).

**Comment by albert-github** [comment]
Any chance that korean and chinese with the standard `.ldf`?

**Comment by jbezos** [comment]
This largely depends on the Korean and Chinese communities, which have opted for dedicated frameworks.

**Comment by albert-github** [comment]
OK Thanks a pity as for Chinese I have not found something yet that translates e.g. the chapter name, for Korean it is possible to use polyglossia.

**Comment by jbezos** [comment]
This is one of the reasons I'm currently working on improving the `ini` files.
