### ISSUE TITLE
USenglish and UKenglish unqueryable on case-sensitive filesystems

### ISSUE THREAD

**Issue by spakin** [latex3/babel#80]
It's not possible to query locale information when specifying `USenglish` or `UKenglish` as the babel language on a case-sensitive filesystem.  The babel-english package provides `USenglish.ldf` and `UKenglish.ldf` (mixed case) while the babel base package provides `babel-usenglish.tex` and `babel-ukenglish.tex` (lower case).  This isn't a problem on case-insensitive filesystems such as Windows's NTFS, but the US/UK `babel-*.tex` files aren't found on a case-sensitive filesystem such as Linux's ext4 because babel is looking for `babel-USenglish.tex` and `babel-UKenglish.tex`.  Here's a minimal reproducer:
```LaTeX
\documentclass{article}
\usepackage[USenglish]{babel}
\BabelEnsureInfo
\begin{document}
I speak language ``\localeinfo{tag.bcp47}''.
\end{document}
```
The error message I receive on Linux is as follows:
```
! Package babel Error: I've found no info for the current locale.
(babel)                The corresponding ini file has not been loaded
(babel)                Perhaps it doesn't exist.
```

The simplest solution seems to be for babel to rename `babel-usenglish.tex` and `babel-ukenglish.tex` to `babel-USenglish.tex` and `babel-UKenglish.tex`, respectively.

— Scott

**Comment by u-fischer** [comment]
I thought the  kpsewhich search were now case-insensitive on linux. Are you using a current tex live? And does e.g. `\documentclass{ARTICLE}` fail for you too?

**Comment by jbezos** [comment]
Very likely all we need is to lowercase the name before loading the file (in fact, I was convinced this was already done).
