### ISSUE TITLE
Definition of "caption names" for mostly monolingual documents when another language is selected

### ISSUE THREAD

**Issue by dbitouze** [latex3/babel#81]
The following MCE:

```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}

\begin{document}
\begin{abstract}
  Plus ça change, plus c'est la même chose!
\end{abstract}
{\selectlanguage{english}
  \begin{abstract}
    I can resist everything except temptation!
  \end{abstract}
}
\end{document}
```
leads to the warning:
```
Package babel Warning: \englishabstractname not set. Please, define
(babel)                it in the preamble with something like:
(babel)                \renewcommand\englishabstractname{..}
(babel)                Reported on input line 27.
```
(BTW, shouldn't it be `{...}` instead of `{..}`?) and indeed, instead of the "Abstract" title for the abstract in English, we get "?abstractname?". But the advised procedure is wrong since it leads to:

`! LaTeX Error: Command \englishabstractname undefined.` 

Okay, let us try with `\newcommand\englishabstractname{..}` instead of `\renewcommand\englishabstractname{..}`. No error anymore but it hasn't any effect since the following MCE:

```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}

\newcommand\englishabstractname{Abstract}

\begin{document}
\begin{abstract}
  Plus ça change, plus c'est la même chose!
\end{abstract}
{\selectlanguage{english}
  \begin{abstract}
    I can resist everything except temptation!
  \end{abstract}
}
\end{document}
```

leads to the abstract in English entitled as the one in French: "Résumé" instead of "Abstract".

**Comment by dbitouze** [comment]
I just noticed this wouldn't be an issue anymore if the advised procedure would be something like:

> Please, define it NOT in the preamble with something like: `\renewcommand\englishabstractname{...}`

instead of:

> Please, define it in the preamble with something like: `\renewcommand\englishabstractname{..}`

**Comment by jbezos** [comment]
This message comes from an age where languages couldn't be loaded on the fly. I must rewrite it.

**Comment by jbezos** [comment]
As to the possibility to change the behavior of languages loaded on the fly, there is `\babeladjust{ autoload.options = import }`, but once I've added `provide=*`, `provide+=*`, `provide*=*`, I'm doing some experiments with something similar (`provide@=*`). It's available in the current version in GitHub, but I'm not very convinced.

**Comment by dbitouze** [comment]
Well, I'm sorry but I see no connection between this comment and the issue :confused:

**Comment by jbezos** [comment]
From the title I assumed you wanted to get the correct caption names of ‘mostly monolingual documents’, and that you found the wrong message when attempting to fix it with `\renewcommand\englishabstractname{..}`.
