### ISSUE TITLE
Include "caption names" in the basic settings loaded on the fly when another language is selected?

### ISSUE THREAD

**Issue by dbitouze** [latex3/babel#82]
It is a very nice feature that, for mostly monolingual documents, the basic settings are loaded on the fly when another language is selected.

But a typical use case is for abstracts of e.g. reports: it is not uncommon that, beside an abstract in the main language, it is required to provide its translation in English. If the `english` language isn't explicitly declared as secondary language, using:

```latex
{\selectlanguage{english}
  \begin{abstract}
    I can resist everything except temptation!
  \end{abstract}
}
```
leads to the error (related issue: #81):
```
Package babel Warning: \englishabstractname not set. Please, define
(babel)                it in the preamble with something like:
(babel)                \renewcommand\englishabstractname{..}
```
I would be nice, for mostly monolingual documents, that the basic settings loaded on the fly when another language is selected include the "caption names"

**Comment by jbezos** [comment]
The code for such a possibility is even partly written (search the source code for `autoload.options`), but there are still some loose ends. Anyway, autoloading is mainly meant for a few word and short texts, no estructural elements like the abstract.

**Comment by dbitouze** [comment]
>Anyway, autoloading is mainly meant for a few word and short texts, no estructural elements like the abstract.

Too bad! As said, it is not uncommon that mostly monolingual (even long) documents contain, as sole part written in a language other than the main one, just an abstract.

**Comment by jbezos** [comment]
I'll think about it. Makes sense.

**Comment by jbezos** [comment]
Related to #81, which I've closed. I'm making some tests with a new option `provide@=*`.

**Comment by jbezos** [comment]
I‘m closing this issue because it’s now listed in [Enhancements requests](https://github.com/latex3/babel/projects/1). This doesn’t mean it’s rejected, just moved to a specific page for enhancements.

**Comment by jbezos** [comment]
Done in v 24.14.
