### ISSUE TITLE
leaking of "This file is part of babel etc." in the body text

### ISSUE THREAD

**Issue by ralessi** [latex3/babel#83]
Something very strange happened with the latest babel, but I can't figure out what it is yet.

Here is what I did in my preamble:
````
\usepackage[no-math]{fontspec}
\usepackage[latin.classic,greek.ancient,american]{babel}
\babelfont{rm}[
   SlantedFont={Old Standard},
   SlantedFeatures={FakeSlant=0.25},
   BoldSlantedFont={Old Standard},
   BoldSlantedFeatures={FakeBold=1.5,FakeSlant=0.25}]{Old Standard}
\babelfont{sf}{NewComputerModern Sans}
\babelfont{tt}{NewComputerModern Mono}
\babelfont[greek]{rm}[
   Script=Greek, RawFeature={+ss05;+ss06},
   SlantedFont={Old Standard},
   SlantedFeatures={FakeSlant=0.25},
   BoldSlantedFont={Old Standard},
   BoldSlantedFeatures={FakeBold=1.5,FakeSlant=0.25}]{Old Standard}
\babelfont[greek]{sf}[Script=Greek]{NewComputerModern Sans}
\babelfont[greek]{tt}[Script=Greek]{NewComputerModern Mono}
\babeltags{ancientgreek = greek}
\def\sg#1{\textancientgreek{#1}}
\usepackage[Old Standard]{mathfont}
````

Then, in the body text, I just typed \sg{ἔκδοσις}, and I got the following in the PDF output:
![babel](https://user-images.githubusercontent.com/389498/87025061-31c13b80-c1da-11ea-91d1-f291324b1be2.png)

(See here http://mirrors.standaloneinstaller.com/ctan/macros/luatex/latex/ekdosis/ekdosis.pdf#section.1)

As said, I couldn't reproduce the problem, but what I can say is that reverting to the previous release of babel solved it.

If I succeed in reproducing this, I will update this report.  Meanwhile, any help would be much appreciated!

Thanks, Robert

**Comment by ralessi** [comment]
Some news: inserting `\BabelEnsureInfo` just below the line that loads `babel` solved the issue.

**Comment by jbezos** [comment]
If I add `\documentclass{article}`and a body with `\sg{ἔκδοσις}` everything seems fine. Can you complete the M(non)WE?

**Comment by jbezos** [comment]
I wondering if the problem is related to the catcode changes in % when dtx files are typeset. `\BabelEnsureInfo` is not required.

**Comment by ralessi** [comment]
> If I add `\documentclass{article}`and a body with `\sg{ἔκδοσις}` everything seems fine. Can you complete the M(non)WE?

I tried just the same with every single package as in the original .dtx loaded, but no avail.  On the other hand, this could be related to catcode changes.  I will try to build a mwe on this basis right away.

**Comment by ralessi** [comment]
Very well spotted!  Here is a (not so m)we:—

````
% \iffalse meta-comment
% This is a (not so)mwe.
% \fi
%
% \iffalse
%<*driver>
\ProvidesFile{mwe.dtx}
%</driver>
%<package>\NeedsTeXFormat{LaTeX2e}[2005/12/01]
%<package>\ProvidesPackage{mwe}
%<*package>
    [2020/07/09 v1.0 mwe file]
%</package>
%
%<*driver>
\documentclass{ltxdoc}
\usepackage{fontspec}
\usepackage[greek.ancient,english]{babel}
\babelfont{rm}{Old Standard}
\babelfont[greek]{rm}[RawFeature={+ss05;+ss06}]{Old Standard}
\babeltags{ancientgreek = greek}
\def\sg#1{\textancientgreek{#1}}
\begin{document}
  \DocInput{mwe.dtx}
\end{document}
%</driver>
% \fi
%
% \CheckSum{0}
%
% \CharacterTable
%  {Upper-case    \A\B\C\D\E\F\G\H\I\J\K\L\M\N\O\P\Q\R\S\T\U\V\W\X\Y\Z
%   Lower-case    \a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z
%   Digits        \0\1\2\3\4\5\6\7\8\9
%   Exclamation   \!     Double quote  \"     Hash (number) \#
%   Dollar        \$     Percent       \%     Ampersand     \&
%   Acute accent  \'     Left paren    \(     Right paren   \)
%   Asterisk      \*     Plus          \+     Comma         \,
%   Minus         \-     Point         \.     Solidus       \/
%   Colon         \:     Semicolon     \;     Less than     \<
%   Equals        \=     Greater than  \>     Question mark \?
%   Commercial at \@     Left bracket  \[     Backslash     \\
%   Right bracket \]     Circumflex    \^     Underscore    \_
%   Grave accent  \`     Left brace    \{     Vertical bar  \|
%   Right brace   \}     Tilde         \~}
%
%
% \changes{v1.0}{2004/11/05}{Initial version}
%
% \GetFileInfo{mwe.dtx}
%
%
% Test: \sg{ὁ βάρβαρος.}
%
%
% \StopEventually{}
%
% \Finale
\endinput
````

**Comment by jbezos** [comment]
👏👏 In fact, the same problem appears when _any_ file is loaded, even without `babel` (eg, with `\input`). I must investigate a little bit further, but I'd say there is a bug in the `doc` system. Anyway, to be on the safe side, I'll make sure `%` is the comment char when a locale is dynamically loaded.

**Comment by ralessi** [comment]
That is something!  I will try to investigate on my side, as I have myself a couple of `\input`, but without leading `%`.  Many thanks for looking into this.

**Comment by ralessi** [comment]
I just tried to insert a `%` at the beginning of one line in a file loaded by `\input`, and the `.dtx` failed to compile.  Did I misunderstand your point?

**Comment by jbezos** [comment]
Let's create a file named `blah.tex` with:
```
Hi
% Blah Blah
Bye
```
Then, with:
```
% \iffalse
%<*driver>
\ProvidesFile{mwe.dtx}
%</driver>
%<package>\NeedsTeXFormat{LaTeX2e}[2005/12/01]
%<package>\ProvidesPackage{mwe}
%<*package>
    [2020/07/09 v1.0 mwe file]
%</package>
%
%<*driver>
\documentclass{ltxdoc}
\begin{document}
  \DocInput{mwe.dtx}
\end{document}
%</driver>
% \fi
% \GetFileInfo{mwe.dtx}
%
% Input: \input{blah}.
%
% \StopEventually{}
% \Finale
\endinput
```
I'm getting:

> Input: Hi Blah Blah Bye .

The comment in the included file is not a comment anymore.

**Comment by ralessi** [comment]
You are correct!  I tried earlier with an `\input` inserted in the `<*driver></driver>` section of the `.dtx` file, not in the part that is loaded with `\DocInput{}`.

Do you think this should be reported?  I suppose you already figured out why `\BabelEnsureInfo` seems to solve this issue?

**Comment by FrankMittelbach** [comment]
I'm a bit confused. The example given by @jbezos seems to me doing absolutely the right thing, is it not? the `\input` happens inside the doc code and so it is expected that there is further "doc" material inside, so comments are ignored.

What seems to be the problem in the original post is that Babel loads support files in arbitrary places without ensure that the catcode settings are suitable for loading the file. Loading some greek support file on the fly needs to save and restore catcodes prior to loading the file, similar to what LaTex does when it loads .fd files (that can also happen in random places, e.g. inside verbatim etc)

Am I missing something?

**Comment by ralessi** [comment]
> I'm a bit confused. The example given by @jbezos seems to me doing absolutely the right thing, is it not? the `\input` happens inside the doc code and so it is expected that there is further "doc" material inside, so comments are ignored.

Uh, yes, obviously, that must be the expected behavior in `doc` material.  I must have been confused myself by these intricate comments!

**Comment by jbezos** [comment]
@FrankMittelbach Perhaps it's doing the right thing, but I think it's somewhat confusing and it should be documented somehow (maybe it is, but I haven't found it). I didn't report it as a bug because I still wasn't sure if it was an error or not.

**Comment by FrankMittelbach** [comment]
What exactly is confusing? If I have a file and I split it and and load the second part using \input I would expect that it works as before aind since that is a doc file I would expect splitting it means the second part is also a doc file. \input nowhere resetting catcode etc.  You wouldn't expect that if babel activates some character that this is undone just because you input another file, would you?

I really think there is somehting amiss if babel loads some support file somewhere inside a document without ensuring that the catcodes are in a defined state (not sure this is the case but it looks to me from the initial description.

**Comment by u-fischer** [comment]
A simple example is this here:

~~~~
\documentclass{article}
\usepackage{babel}
\begin{document}

\catcode`\%=11 

{\selectlanguage{greek} some greek}
\end{document}
~~~~

**Comment by jbezos** [comment]
I would expect conventions of `dtx` files to apply only to the `dtx` files themselves. Of course, the behavior of non `dtx` files inputted in a `dtx` file is more or less clear if you know what the `dtx`/`doc` system is doing internally (which is far from obvious, because a `dtx` file can be read in 3 different ways). As I said, I'll make sure the catcode of % is set to 14 when an ini file is read, but I still think the behavior of `\input` in a `dtx` file must be documented - nothing is lost.

**Comment by FrankMittelbach** [comment]
But Javier, nowhere does LaTeX inspect the extension of a file and adjusts or readjusts catcodes; \input just inputs in whatever state is active. But yes, we can add a note if you think it is helpful (but given that this case never cause anybody a headache in more than 30 years seems to indicate that it isn't really a problem for doument level (but okay not too many dtx files would \input another file :-) )
