### ISSUE TITLE
coordinating shorthands with hyperref

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#84]
hyperref detects a number of languages and redefines some of their shorthands for the bookmarks. This support is not complete, not really extensible (without patching the internal command) and it doesn't work properly if users redefine or add shorthands. It will fail completely if languages are loaded after hyperref. 

Imho it would make much more sense if such alternative  definitions (there are only needed for a few non expandable shorthand definitions) where added directly to the shorthand. babel only need to provide \texorpdfstring and encourage the language maintainers to make use of it:

~~~~
\documentclass{report}
\usepackage[ngerman]{babel}
\providecommand\texorpdfstring[2]{#1}

\makeatletter
\declare@shorthand{ngerman}{"~}{\texorpdfstring{\textormath{\leavevmode\hbox{-}}{-}}{~}}
\declare@shorthand{ngerman}{"|}{%
  \texorpdfstring{%
  \textormath{\penalty\@M\discretionary{-}{}{\kern.03em}%
              \bbl@allowhyphens}{}}{}}
\makeatother

\usepackage{hyperref}
 \makeatletter
 \def\HyPsd@babel@ngerman{}% disable the hyperref code
\makeatother

\begin{document}
\section{a"|ba"~b}


\end{document}
~~~~

What do you think?

**Comment by jbezos** [comment]
It would be nice if this was done by the `babel` himself. Of course, it remains to be seen it is possible. 🙂

**Comment by jbezos** [comment]
@u-fischer A question. Is the order `\texorpdfstring{\textormath{...}{...}}{...}` the only possible o recommended? Or is `\textormath{\texorpdfstring{...}{...}}{\texorpdfstring{...}{...}}` better, worse, irrelevant?

**Comment by u-fischer** [comment]
@jbezos Hm. Currently hyperref removes the math shift in pdf context. So `\section{$\textormath{text}{math}$}` prints `text` in the bookmarks. 

This means that `\texorpdfstring{\textormath{...}{...}}{...}` is in the current situation the shortest. But I'm not sure if this should/will stay this way. Perhaps the bookmarks can react to math here too. In this case the longer variant would probably be better (if it the bookmarks should do something different in math with the command, if not it shouldn't matter).

**Comment by jbezos** [comment]
@u-fischer One of the problems is the definition:
```
\textormath{\leavevmode\hbox{-}}{-}
```
doesn't make much sense to me. Replacing in a math context `"~` by a minus seems inconsistent. Furthermore, if this shorthands is converted to a minus in math mode, having a hyphen in a bookmark is doubly inconsistent.

**Comment by u-fischer** [comment]
@jbezos yes looks a bit odd to map `"~` to a minus. But this is not really a hyperref question, but one for the maintainer of the language files. They should decide what a shorthand should do in the contexts "text", "math", "pdf" (and perhaps "pdf+math" in future) and setup things accordingly.  (At least that is my wish: that language files not only think about "text" and "math" but also about "pdf" (in the sense of bookmarks and similar).) 

Btw: the (n)german case has been handled by the maintainer and is already on ctan - I hope other languages follow so that I can clean up hyperref in more places ;-)

**Comment by jbezos** [comment]
@u-fischer In most cases I'm the ‘deputy’ maintainer, so I must create a parallel structure with the files, revise the README's, create tests, and so on, so it's not a straightforward task. It may seem like an immediate change, but in fact I will have to spend quite a bit of time on it. For this reason I would like to take the opportunity to improve the code, or even, as I said, to find a general solution within babel itself.

**Comment by u-fischer** [comment]
@jbezos sorry that I sounded pushing, that wasn't intended. I'm quite happy that there is movement in the (in my opinion) right direction,  and I know that code that have been around for up to 30 years has many dependencies and can't be changed over night.

**Comment by jbezos** [comment]
@u-fischer 

> I sounded pushing

Not at all.

**Comment by u-fischer** [comment]
I would like to push the issue forward by starting to remove language patches from hyperref. 

In a first step the patches for danish, dutch and finnish. The removal will not affect the output in the bookmarks, but the users will see warnings in the log:

~~~~
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                \kern 0.29999pt
(hyperref)                removed on input line 39.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hbox' on input line 39.
~~~~

So if would be good if the three languages adapt the definitions. A suggestion how to do it is below. There are no git repos for the language files, so creating a pull request was no possible, but if needed I can send adapted dtx files. 

~~~~
\documentclass{article}
\usepackage[finnish,dutch,danish]{babel}
\usepackage{hyperref}
\makeatletter
% disable hyperref patch for a test:
\def\HyPsd@babel@danish{}% 
\def\HyPsd@babel@dutch{}%
\def\HyPsd@babel@finnish{}%
\makeatother
\begin{document}

\section{a"|b a"~b}
a"|b a"~b

\makeatletter
%suggested change in danish.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{danish}{"|}{%
  \texorpdfstring{\textormath{\discretionary{-}{}{\kern.03em}}{}}{}}
\declare@shorthand{danish}{"~}{%
  \texorpdfstring{\textormath{\leavevmode\hbox{-}}{-}}{-}}  
\makeatother    

\section{a"|b a"~b}
a"|b a"~b

\selectlanguage{dutch}
\section{a"|b a"~b}
a"|b a"~b

\makeatletter
% suggested change for dutch.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{dutch}{"|}{%
  \texorpdfstring{\textormath{\discretionary{-}{}{\kern.03em}}{}}{}}
\declare@shorthand{dutch}{"~}{%
  \texorpdfstring{\textormath{\leavevmode\hbox{-}}{-}}{-}}
\makeatother

\section{a"|b a"~b}
a"|b a"~b

\selectlanguage{finnish}

\section{a"|b}
a"|b 

\makeatletter
% suggested change for finnish.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{finnish}{"|}{%
  \texorpdfstring{\textormath{\discretionary{-}{}{\kern.03em}}{}}{}}
\makeatother

\section{a"|b}
a"|b 

\end{document}
~~~~

**Comment by u-fischer** [comment]
A second set are the languages usorbian, portugues and swedish. For them the same is true as for the other three languages: removing the hyperref patches doesn't affect the output, but produce warnings in the log. 

Side remark: usorbian contains a bug. It activates the shorthand in the extra command and then deactivates is directly again:

~~~~
\expandafter\addto\csname extras\CurrentOption\endcsname{%
  \bbl@activate{"}}
\expandafter\addto\csname extras\CurrentOption\endcsname{%
  \bbl@deactivate{"}}
~~~~ 


Suggested changes for this three languages:

~~~~
\documentclass{article}
\usepackage[usorbian,portuges,swedish]{babel}
\usepackage{hyperref}
\makeatletter
% disable hyperref patch for a test:
\def\HyPsd@babel@swedish{}% 
\def\HyPsd@babel@portuges{}%
\def\HyPsd@babel@usorbian{}%
\makeatother
\begin{document}

\section{a"|b a"~b}
a"|b a"~b

\makeatletter
%suggested change in swedish.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{swedish}{"|}{%
  \texorpdfstring{\textormath{\nobreak\discretionary{-}{}{\kern.03em}%
              \bbl@allowhyphens}{}}{}}
\declare@shorthand{swedish}{"~}{%
  \texorpdfstring{\textormath{\leavevmode\hbox{-}\bbl@allowhyphens}{-}}{-}}  
\makeatother

\section{a"|b a"~b}
a"|b a"~b

\selectlanguage{portuges}
\section{a"|b}
a"|b

\makeatletter
%suggested change in portuges.ldf and portuguese.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{portuges}{"|}{%
  \texorpdfstring{\textormath{\discretionary{-}{}{\kern.03em}}{}}{}}
\makeatother

\section{a"|b}
a"|b
 
 
\makeatletter %work around buggy usorbian.ldf
\expandafter\addto\csname extrasusorbian\endcsname{%
  \bbl@activate{"}}
 \makeatletter
    
\selectlanguage{usorbian}
 
\section{a"ff a"|b}
a"ff a"|b

\makeatletter
%suggested change in usorbian.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{usorbian}{"|}{%
  \texorpdfstring{\textormath{\bbl@disc f{ff}}{f}}{f}}
\declare@shorthand{usorbian}{"|}{%
  \texorpdfstring{\textormath{\nobreak\discretionary{-}{}{\kern.03em}%
              \allowhyphens}{}}{}}  
\makeatother

\section{a"ff a"|b}
a"ff a"|b

\end{document}
~~~~

**Comment by u-fischer** [comment]
A last simple case is slovene, which is quite similar:

~~~~
\documentclass{article}
\usepackage[slovene]{babel}
\usepackage{hyperref}
\makeatletter
% disable hyperref patch for a test:
\def\HyPsd@babel@slovene{}%
\makeatother
\begin{document}

\section{a"|b}
a"|b 

\makeatletter
%suggested change in slovene.ldf
\providecommand\texorpdfstring[2]{#1}
\declare@shorthand{slovene}{"|}{%
  \texorpdfstring{\textormath{\nobreak\discretionary{-}{}{\kern.03em}%
\allowhyphens}{}}{}}


\makeatother

\section{a"|b}
a"|b
\end{document}
~~~~

**Comment by u-fischer** [comment]
## spanish
spanish is more complicated: removing the patches in hyperref leads to errors and wrong output in the bookmarks if the commands/shorthands are used in section commands. So the patches can only be removed if/after spanish.ldf   includes the following changes. 

One patch (`\let\es@roman\@Roman`) is directly in \pdfstringsdef, testing what happens if it is removed requires to change hyperref.sty temporarly (which I did).  `\.` looks forward to the next char and is not expandable, so `\...` is not handled correctly by hyperref.  


~~~~
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[spanish]{babel}
\usepackage{hyperref}
\makeatletter
% disable hyperref patch for a test:
\def\HyPsd@babel@spanish{}%
\def\HyPsd@SpanishPatch{}
\makeatother
\begin{document}%
% hyperref patches
% 1. shorthands
%    \declare@shorthand{spanish}{<<}{\guillemotleft}%
%    \declare@shorthand{spanish}{>>}{\guillemotright}%
%    \declare@shorthand{spanish}{"=}{-}%
%    \declare@shorthand{spanish}{"~}{-}%
%    \declare@shorthand{spanish}{"!}{\textexclamdown}%
%    \declare@shorthand{spanish}{"?}{\textquestiondown}%
% 2. \. accent command
%    \let\.\es@save@dot
% 3. es@roman (not in a patch, but directly in \pdfstringdef):
%    \let\es@roman\@Roman

\makeatletter
% suggested changes for spanish.ldf
%.1 shorthands 
\es@declarealt{<<}{"`}{\texorpdfstring{\begin{quoting}}{\guillemotleft}}
\es@declarealt{>>}{"'}{\texorpdfstring{\end{quoting}}{\guillemotright}}
\es@declare{"=}{\texorpdfstring{\bbl@allowhyphens\es@chf\hskip\z@skip}{-}}
\es@declare{"~}
  {\texorpdfstring{\bbl@allowhyphens
   \discretionary{\es@chf}{\es@chf}{\es@chf}%
   \bbl@allowhyphens}{-}}
\es@declare{"!}
  {\texorpdfstring{\setbox\z@\hbox{!`}%
   \leavevmode\raise\dp\z@\box\z@}{\textexclamdown}}
\es@declare{"?}
  {\texorpdfstring{\setbox\z@\hbox{?`}%
   \leavevmode\raise\dp\z@\box\z@}{\textquestiondown}}
      
%2. for \., this doesn't help with \... (but this doesn't work now too)   
%\AtBeginDocument, if \pdfstringdefDisableCommands is defined:   
\pdfstringdefDisableCommands{\let\.\es@save@dot}
%3. for \es@roman, inside \es@romandef (#1 --> ##1):   
  % testing requires to disable \let\es@roman\@Roman in hyperref.sty
\def\es@roman#1{\texorpdfstring{\es@scroman{\romannumeral#1}}{\@Roman{#1}}}   
\makeatother


\newcounter{testroman} \setcounter{testroman}{123}
%       test         behaviour without patch
\section{ <<a>>      %errors needs handling
          "`a"'      %errors too, not handled by hyperref 
          a"=b a"~b  %wrong output
          "! "?      %only warnings
          \.a        % wrong output, accent missing  
          \...       % wrong output always
          \roman{testroman} %warnings, wrong output in the bookmarks (lowercase)
         }
         
<<a>> a"=b a"~b "! "? \.a \... \roman{testroman} 
\end{document}
~~~~

**Comment by jbezos** [comment]
I tried several solutions from within Babel, but they weren't satisfactory, so regrettably I'll have to change gradually the `.ldf` files. It's a laborious task, so expect a few months for it to be finished.

**Comment by u-fischer** [comment]
Well I think that the ldf-files are the right place.  How the shorthands behave in a text are defined there, so it should be defined there too how they behave in a bookmark or an alternate text. 

And as I wrote: I'm quite willing to insert the changes I suggested in the dtx-files, update the version and sent them too you.

**Comment by u-fischer** [comment]
I will update hyperref today. In the new version all language patches with the exception of the spanish ones have been removed. So this languages will probably see warnings.

**Comment by jbezos** [comment]
@u-fischer I take note.

**Comment by jbezos** [comment]
@u-fischer As a temporary solution I'll copy the relevant lines from hyperref.sty to babel. I presume the lines to be copied (I hope with minor changes) are those starting with
```
\def\HyPsd@BabelPatch{%
```
and ending with
```
\ltx@IfUndefined{usorbian@sh@"@sel}{}{%
  \def\HyPsd@babel@usorbian{%
    \declare@shorthand{usorbian}{"f}{f}%
    \declare@shorthand{usorbian}{"|}{}%
  }%
```
Am I right?

**Comment by u-fischer** [comment]
`\HyPsd@BabelPatch` is gone in hyperref, it will not be executed. The only patch still active is `\HyPsd@SpanishPatch`. 

You would have to add your own command to \pdfstringdef, at best with a babel name, and not something starting with HyPsd. 

But what is the problem with updating the languages as I suggested? It is only a few lines to add to the dtx. I can prepare them and sent them to you if you want.

**Comment by jbezos** [comment]
See https://github.com/latex3/babel/issues/84#issuecomment-707043616. Hard times for me, too. I even thought I would lose my job.

**Comment by u-fischer** [comment]
I'm sorry to hear that. 

You could tell ctan that I can upload these languages, then I would do it over the weekend.

**Comment by jbezos** [comment]
I wrote a macro named `\babel@texpdf` for this. From the `dtx`:
```
% The auxiliary macro |\babel@texpdf| improves the interoperativity with
% \textsf{hyperref} and takes 4 arguments: (1) The \TeX{} code in text
% mode, (2) the string for \textsf{hyperref}, (3) the \TeX{} code in
% math mode, and (4), which is currently ignored, but it's meant for a
% string in math mode, like a minus sign instead of an hyphen
% (currently \textsf{hyperref} doesn't discriminate the mode). This
% macro may be used in |ldf| files.

%    \begin{macrocode}
\def\babel@texpdf#1#2#3#4{%
  \ifx\texorpdfstring\@undefined
    \textormath{#1}{#2}%
  \else
    \texorpdfstring{\textormath{#1}{#3}}{#2}%
    % \texorpdfstring{\textormath{#1}{#3}}{\textormath{#2}{#4}}%
  \fi}
%
```
I think in a month or so I can have time again for the development of babel at the pace I wanted, fix bugs, and so on. This would include fixing these languages. If you can do it, great. If not, I can finish them myself before April (I'm aware TeXLive will be released soon).

**Comment by u-fischer** [comment]
I uploaded danish, finnish, portuges, slovene, sorbian and swedish with the suggested changes (one change in sorbian seemed to actually unneeded so I left it out).  So apart from spanish everything should now work as previously when the patches were in hyperref.
