### ISSUE TITLE
remove `\pdfstringdefDisableCommands{\languageshorthands{system}}%` from babel.sty

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#87]
The hyperref code contains the remark

```
% Since version 2008/03/16 v3.8j babel uses inside \cs{AtBeginDocument}:
%\begin{quote}
%\begin{verbatim}
%\pdfstringdefDisableCommands{%
%  \languageshorthands{system}%
%}
%\end{verbatim}
%\end{quote}
%    As consequence the shorthands are shown in the bookmarks,
%    not its result. Therefore \cs{languageshorthands} is
%    disabled before the user hook.
```

And then follows a rather long patch whose whole purpose is to make ` \languageshorthands{system}` a no-op in the pdfstringdef hook. If you remove the `\pdfstringdefDisableCommands{\languageshorthands{system}}` I can remove the patch and the behaviour will be the same as now.

**Comment by blefloch** [comment]
Ulrike, wouldn't

\tl_remove_all:Nn \pdfstringdefPreHook { \languageshorthands{system} }

be enough?

**Comment by u-fischer** [comment]
@blefloch  yes, lots of things work. But if adding the command is objectively wrong and removing it is the solution, then imho it should be removed at the source and not in a later clean-up step.

**Comment by blefloch** [comment]
On 7/24/20 3:57 PM, Ulrike Fischer wrote:
> @blefloch <https://github.com/blefloch> yes, lots of things work. But if adding
> the command is objectively wrong and removing it is the solution, then imho it
> should be removed at the source and not in a later clean-up step.

Agreed.

**Comment by jbezos** [comment]
Commented out. I've even marked it sometime ago with a ‘todo’.
