### ISSUE TITLE
mapdigits not working with XeLaTeX

### ISSUE THREAD

**Issue by NiranjanTambe** [latex3/babel#89]
This does not provide local numerals. Is it possible to make it compatible with XeLaTeX?
```
%!TeX Program = xelatex
\documentclass{article}
\usepackage{fontspec}
\usepackage{babel}
\babelprovide[import, main, maparabic, mapdigits]{marathi}
\defaultfontfeatures{Script=Devanagari}
\setmainfont{Shobhika}

\begin{document}
\title{नमुना}
\author{लेखक}
\maketitle
\end{document}
```

Note - This issue is related to [this](https://github.com/latex3/babel/issues/74#issuecomment-640625824) one. Thanks @davidcarlisle, @jbezos for the help.

**Comment by u-fischer** [comment]
This looks like a fontspec problem, it resets the mapping to tex-text. Using \defaultfontfeatures fails without babel too. `\setmainfont{Shobhika}[Mapping=devanagarinumerals]` works, as does with babel `\babelfont[marathi]{rm}[Mapping=devanagarinumerals]{Shobhika}`

**Comment by NiranjanTambe** [comment]
@u-fischer Do you mean this -

```
%!TeX Program = xelatex
\documentclass{article}
\usepackage{fontspec}
\usepackage{babel}
\babelprovide[import, main, maparabic, mapdigits]{marathi}
\defaultfontfeatures{Script=Devanagari,Mapping=devanagarinumerals}
\setmainfont{Shobhika}

\begin{document}
\title{नमुना}
\author{लेखक}
\maketitle
\end{document}
```

It doesn't work.

**Comment by u-fischer** [comment]
I know that this doesn't work, that is your example from above. defaultfontfeatures seems to be broken here.

**Comment by NiranjanTambe** [comment]
Oh. Actually I tried adding `Mapping=devanagarinumerals` in the `\defaultfontfeatures` but as it wasn't working, hence I dropped the that parameter.

Adding it to the `\setmainfont` works. Thanks.

Shall I post a `fontspec` issue for this? `\defaultfontfeatures` shouldn't be dropped, right?

**Comment by NiranjanTambe** [comment]
> I know that this doesn't work, that is your example from above. defaultfontfeatures seems to be broken here.

Yes I got it. Hence deleted the comment :)

**Comment by u-fischer** [comment]
> Shall I post a `fontspec` issue for this? `\defaultfontfeatures` shouldn't be dropped, right?

Well I normally wouldn't add such language settings to defaultfontfeatures - that doesn't work well if you have more than one language. But beside this it looks like a fontspec bug.
