### ISSUE TITLE
seeking advice for commands for new glyphs

### ISSUE THREAD

**Issue by antonis-tsolomitis** [latex3/babel#90]
Hi, I am developing the NewComputerModern fonts, and recently I added the block of Ancient Greek Numbers, 
which is u10140-u1018E. This is a text block (not a math block for Unicode). To access these glyphs some newcommands must be introduced. The question is where these commands should go. Is there a policy for this? How to add new glyphs? What is the proper place? Thank you.

**Comment by jbezos** [comment]
Since this font (like any other font) can be used without `babel`, very likely an external package is a better option (which doesn't mean they cannot be included in `babel`, of course). But to be honest, I don't know for sure where and how.

**Comment by antonis-tsolomitis** [comment]
Thanks. I will think what to do...

**Comment by jbezos** [comment]
Maybe @wspr (`fontspec') or @u-fischer (`luaoftload`) can help.
