### ISSUE TITLE
Error “\bbl@pop@lang has an extra }” in tabular environment

### ISSUE THREAD

**Issue by SverreStausland** [latex3/babel#93]
There's a line in my CV document that's been there for years, but now it causes an error message. I've stripped it down to the following MWE:

    \documentclass{article}
    
    \usepackage[main = american, ngerman]{babel}
    
    \begin{document}
    
    \begin{tabular}{l}
    	\begin{otherlanguage}{ngerman}foo\end{otherlanguage}
    \end{tabular}
    
    \end{document}

This gives the error `Argument of \bbl@pop@lang has an extra }`.

I'm running texlive 2020 in Windows with all packages updated Aug 31, 2020, and compiling with lualatex. It's clearly `babel` that's causing the error, but this has always compiled fine before. It also compiles if the offending line is not in a tabular environment.

**Comment by jbezos** [comment]
Thank you. I've found the error and a fix will be available in a few days.
