### ISSUE TITLE
\begin{otherlanguage}{<lang>} loaded with [main=<lang>] no longer works

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/babel#96]
Until the previous `babel` release this would work:
```latex
\documentclass{article}
\usepackage[main=brazil]{babel}
% \usepackage[brazil]{babel} % works
\begin{document}
\begin{otherlanguage}{brazil}
\end{otherlanguage}
\end{document}
```
but after today's (2020-10-05) update, it errors with:
```latex
! Package babel Error: You haven't defined the language brazil yet.
(babel)                Perhaps you misspelled it or your installation
(babel)                is not complete.
```

**Comment by jbezos** [comment]
Hopefully, not many people is using `babel` in this way. Anyway I'll try to fix it asap.

**Comment by PhelypeOleinik** [comment]
Yes, it's a slightly unusual setup I have for a two-language document, but still, `main=<lang>` doesn't set the language for the body of the document (`\languagename` is `nil`).  Thanks for looking into it!

**Comment by jbezos** [comment]
I'd say it's a severe bug because in many cases the language is silently ignored. Very likely I'll submit the fix to CTAN tomorrow.

**Comment by PhelypeOleinik** [comment]
Oh, that was fast :-)
Thank you!
