### ISSUE TITLE
layout=graphics doesn't work with latest LaTeX (pict2e)

### ISSUE THREAD

**Issue by jbezos** [latex3/babel#98]
With:
```
\documentclass{report}
\usepackage{tikz}
\usepackage[bidi=basic, layout=graphics]{babel}
\babelprovide[import, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}
text
\end{document}
```
the following error is raised:
```
! A <box> was supposed to be here.
```

**Comment by jbezos** [comment]
I'm investigating, but with the lastest changes in LaTeX (2020-10) `\put` seems almost unpatchable. So very likely the only real solution is to add by hand the language at every `\put` or create something like `\localeput`.

**Comment by FrankMittelbach** [comment]
@jbezos I haven't followed the context of this issue, but can you explain a bit why you need to patch `\put`? Depending on the use case maybe providing a suitable hook instead of that patching would be a better option?

**Comment by jbezos** [comment]
@FrankMittelbach Graphics are intrinsically LTR, so mixing them with RTL text requires direction changes. What `babel` attempts is (conceptually): ‘save the current direction’ when the `picture` starts, ’change to LTR’, and then in `\put` ’change to the saved direction’, because it may consist in text. A suitable hook would be a better option, and not only here, but also at some other places (do you remember our discussion about math mode in `tabular`?).

**Comment by FrankMittelbach** [comment]
> @FrankMittelbach Graphics are intrinsically LTR, so mixing them with RTL text requires direction changes. What `babel` attempts is (conceptually): ‘save the current direction’ when the `picture` starts, ’change to LTR’, and then in `\put` ’change to the saved direction’, because it may consist in text. 

Well, it is debateable whether a directoin change should happen by `\put` or by boxes inside its argument (because officially there should not be any direct text inside that argument). On the other hand I guess people do that, so one probably has to account for it. And the switch to LTR at  start (and saving the current direction) would also require a hook.

> A suitable hook would be a better option, and not only here, but also at some other places (do you remember our discussion about math mode in `tabular`?).

dimely :-) we need hooks in many places and now with the machinery in place the next task is to add them --- but in a consistent way. So this doesn't really belong to this issue here, but just to mention it it would be important to get an overview about where you see the need for direction hooks (and other language related hooks).

**Comment by jbezos** [comment]
> Well, it is debateable whether a directoin change should happen by `\put` or by boxes inside its argument (because officially there should not be any direct text inside that argument).

Should not? “The picture-object  can be arbitrary text, which is typeset in LR mode, or else one [...]” (Lamport, 221) 🙂. And indeed there is an example on p 120. I understand here LR mode in the original sense roughly equivalent to horizontal mode.

**Comment by FrankMittelbach** [comment]
Am 10.10.20 um 12:59 schrieb Javier Bezos:
> Should not? “The picture-object can be arbitrary text, which is typeset 
> in LR mode, or else one [...]” (Lamport, 221) 🙂. And indeed there is an 
> example on p 120. I understand here LR mode in the original sense 
> roughly equivalent to horizontal mode.
> 
ups, you are right; wonder why I thought he required a \makebox in the 
spec, maybe because they exist with picture versions with ().

So it does need hook in both places.

**Comment by seloumi** [comment]
Maybe  this helps, disabling bidi with picture env 

```latex
\documentclass{article}
\usepackage[bidi=basic,nil]{babel}
\babelprovide[import,main]{arabic}
\babelfont{rm}{Amiri}
             
\makeatletter
\let\bbl@pictresetdir\relax
   \def\bbl@pictsetdir{%
     \ifcase\bbl@thetextdir
       \let\bbl@pictresetdir\relax
     \else
       \textdir TLT\relax
       \def\bbl@pictresetdir{\textdir TRT\relax}%
     \fi}%
   \let\bbl@OL@@picture\@picture
   \bbl@sreplace\@picture{\hskip-}{\bbl@pictsetdir\hskip-}%
\makeatother             
             
\begin{document}
\setlength{\unitlength}{.5cm}
\thicklines

قبل%
\directlua{Babel.bidi_enabled = false}%
\begin{picture}(9,6)
\put(1.5,0){\line(1,0){6}}
\put(1.5,0){\circle{1.5}}
\put(6,0){\oval(4,2)[r]}
\end{picture}%
\directlua{Babel.bidi_enabled = true}%
بعد

\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/95865103-8e4a6e80-0d66-11eb-93fc-932e40fc0a3d.png)

**Comment by jbezos** [comment]
🤔 Interesting approach. I was attempting to make changes with `\textdir` and the like, but your proposal makes sense (which doesn't mean it will work, of course 😉). I'll investigate. Thank you.

**Comment by jbezos** [comment]
It seems the problem is not in LaTeX, but in `pict2e` 0.4. I've done some tests, and it works if I downgrade  `pict2e` to 0.3.

**Comment by jbezos** [comment]
@seloumi I think I managed to fix the issue. The solution is somewhat more convoluted than I expected (and wanted), but in my tests seems to work. If you find more problems, just let me know and re-open the issue.
