### ISSUE TITLE
intraspace = 0 .1 0 in japanese incompatible with current color syntax in tikz?

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#99]
The following document 

~~~~
\documentclass{article}
\usepackage{babel}
\babelprovide{japanese}

\usepackage{tikz}
\begin{document}
\tikz\draw[.!50](1,1);
\end{document}
~~~~

errors with lualatex with 

~~~~
warning  (hyphenation): bad specification: [\directlua]:1: attempt to index a ni
l value
.
\endpgfpicture ...globally \endgroup \hss \egroup 
                                                  \pgf@restore@layerlist@fro...
l.25 \tikz\draw[.!50](1,1);
                         
~~~~

The error can be avoided by removing in `babel-ja.ini` the setting `intraspace = 0 .1 0`, or by not using a period in the color setting, so e.g. `[red!50]` instead of `[.!50]`.

**Comment by jbezos** [comment]
A quite interesting bug. For some reason, `tikz` is adding the string `!50` to the node list as a glyph with a ‘null’ font. With
```
\documentclass{article}
\usepackage{tikz}

\begin{document}
\tikz\draw[.!50](1,1);
\end{document}
```
the log shows:
```
Missing character: There is no ! (U+0021) in font nullfont!
Missing character: There is no 5 (U+0035) in font nullfont!
Missing character: There is no 0 (U+0030) in font nullfont!
```

`babel` assumes a well formed node glyph, with actual fonts. I'll modify it to catch nullfonts, but the bug is ultimately in `tikz`.

**Comment by u-fischer** [comment]
yes, it is known that tikz quite often produce missing character lists for nullfont. This can happen through internal errors, but also by user input, e.g. a semicolon too much or some stray text:

~~~~
\documentclass{article}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
some stray text
\draw[red!50](1,1);;
\end{tikzpicture}

\end{document}
~~~~

gives 

~~~~
....
Missing character: There is no t in font nullfont!
Missing character: There is no e in font nullfont!
Missing character: There is no x in font nullfont!
Missing character: There is no t in font nullfont!
Missing character: There is no ; in font nullfont!
~~~~

So I think it would be good if babel wouldn't error when it encounters nullfont.
